import type { ComponentType } from 'react';

type PageModule = { default: ComponentType };
type PageLoader = () => Promise<PageModule>;

const loadMigratedPage: PageLoader = () => import('./migrated-dashboard-page');

export const dashboardPageLoaders: Readonly<Record<string, PageLoader>> = {
  '/autoTag/dayPartCreate': loadMigratedPage,
  '/autoTag/dayPartIndex': loadMigratedPage,
  '/autoTag/dayPartShow': loadMigratedPage,
  '/autoTag/joinRoomCreate': loadMigratedPage,
  '/autoTag/joinRoomIndex': loadMigratedPage,
  '/autoTag/joinRoomShow': loadMigratedPage,
  '/autoTag/keywordCreate': loadMigratedPage,
  '/autoTag/keywordIndex': loadMigratedPage,
  '/autoTag/keywordShow': loadMigratedPage,
  '/channelCode/index': loadMigratedPage,
  '/channelCode/statistics': loadMigratedPage,
  '/channelCode/store': loadMigratedPage,
  '/chatTool/customer': loadMigratedPage,
  '/chatTool/enhance': loadMigratedPage,
  '/contactField/index': loadMigratedPage,
  '/contactMessageBatchSend/index': loadMigratedPage,
  '/contactMessageBatchSend/show': loadMigratedPage,
  '/contactMessageBatchSend/store': loadMigratedPage,
  '/contactTransfer/resignAllotRecord': loadMigratedPage,
  '/contactTransfer/resignIndex': loadMigratedPage,
  '/contactTransfer/workAllotRecord': loadMigratedPage,
  '/contactTransfer/workIndex': loadMigratedPage,
  '/corp/index': loadMigratedPage,
  '/corpData/index': loadMigratedPage,
  '/department/index': loadMigratedPage,
  '/greeting/index': loadMigratedPage,
  '/greeting/store': loadMigratedPage,
  '/lossContact/index': loadMigratedPage,
  '/mediumGroup/index': loadMigratedPage,
  '/menu/index': loadMigratedPage,
  '/officialAccount/create': loadMigratedPage,
  '/officialAccount/index': loadMigratedPage,
  '/passwordUpdate/index': loadMigratedPage,
  '/role/index': loadMigratedPage,
  '/role/permissionShow': loadMigratedPage,
  '/roomMessageBatchSend/index': loadMigratedPage,
  '/roomMessageBatchSend/show': loadMigratedPage,
  '/roomMessageBatchSend/store': loadMigratedPage,
  '/roomTagPull/contactDetail': loadMigratedPage,
  '/roomTagPull/create': loadMigratedPage,
  '/roomTagPull/detail': loadMigratedPage,
  '/roomTagPull/index': loadMigratedPage,
  '/roomWelcome/create': loadMigratedPage,
  '/roomWelcome/index': loadMigratedPage,
  '/statistics/contact': loadMigratedPage,
  '/statistics/employee': loadMigratedPage,
  '/user/index': loadMigratedPage,
  '/workContact/contactFieldPivot': loadMigratedPage,
  '/workContact/index': loadMigratedPage,
  '/workContactTag/index': loadMigratedPage,
  '/workEmployee/index': loadMigratedPage,
  '/workFission/create': loadMigratedPage,
  '/workFission/dataShow': loadMigratedPage,
  '/workFission/edit': loadMigratedPage,
  '/workFission/invite': loadMigratedPage,
  '/workFission/taskpage': loadMigratedPage,
  '/workRoom/detail': loadMigratedPage,
  '/workRoom/index': loadMigratedPage,
  '/workRoom/statistics': loadMigratedPage,
  '/workRoomAutoPull/index': loadMigratedPage,
  '/workRoomAutoPull/store': loadMigratedPage,
};
