packages:
  - web/apps/*
  - web/e2e
  - web/packages/*
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  msw: true
overrides:
  '@typescript-eslint/tsconfig-utils': 8.55.0
  '@typescript-eslint/types': 8.55.0
autoInstallPeers: false
dedupePeerDependents: true
engineStrict: true
preferWorkspacePackages: true
saveExact: true
strictPeerDependencies: true
