packages:
  - web/apps/*
  - web/packages/*
allowBuilds:
  esbuild: true
autoInstallPeers: false
dedupePeerDependents: true
engineStrict: true
preferWorkspacePackages: true
saveExact: true
strictPeerDependencies: true
