packages:
  - web/apps/*
  - web/e2e
  - web/packages/*
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  msw: true
overrides:
  '@typescript-eslint/tsconfig-utils': 8.55.0
  '@typescript-eslint/types': 8.55.0
  brace-expansion@1.1.16: 1.1.18
  brace-expansion@2.1.2: 2.1.4
  js-yaml@4.3.0: 4.3.1
  nanoid@3.3.16: 3.3.18
autoInstallPeers: false
dedupePeerDependents: true
engineStrict: true
preferWorkspacePackages: true
saveExact: true
strictPeerDependencies: true
