import type { InsightStatus, SessionInsightFilters, SmartInsightFilters } from './ai-insight-workspace-api';

function positive(value: string | null): number | undefined { if (!value) return undefined; const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined; }
function validDate(value: string | null): string | undefined { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : undefined; }
function readCommon(params: URLSearchParams): SessionInsightFilters { const conversationType = params.get('conversationType'); const status = params.get('status'); const filters: SessionInsightFilters = { page: positive(params.get('page')) ?? 1 }; const employeeId = positive(params.get('employeeId')); if (employeeId !== undefined) filters.employeeId = employeeId; const customerName = params.get('customerName') || ''; if (customerName) filters.customerName = customerName; const targetId = params.get('targetId') || ''; if (targetId) filters.targetId = targetId; const keyword = params.get('keyword') || ''; if (keyword) filters.keyword = keyword; if (conversationType === 'direct' || conversationType === 'group') filters.conversationType = conversationType; if (['pending', 'running', 'succeeded', 'failed'].includes(status ?? '')) filters.status = status as InsightStatus; const startDate = validDate(params.get('startDate')); if (startDate) filters.startDate = startDate; const endDate = validDate(params.get('endDate')); if (endDate) filters.endDate = endDate; return filters; }
export function readSessionFilters(input: string | URL = window.location.href): SessionInsightFilters { return readCommon(new URL(input, window.location.origin).searchParams); }
export function readSmartState(input: string | URL = window.location.href): { filters: SmartInsightFilters } { const url = new URL(input, window.location.origin); return { filters: { ...readCommon(url.searchParams) } }; }
function writeCommon(params: URLSearchParams, filters: SessionInsightFilters): void { params.delete('page'); if (filters.page > 1) params.set('page', String(filters.page)); for (const key of ['employeeId', 'customerName', 'conversationType', 'targetId', 'keyword', 'status', 'startDate', 'endDate'] as const) { params.delete(key); const value = filters[key]; if (value !== undefined && value !== '') params.set(key, String(value)); } }
export function writeSessionFilters(filters: SessionInsightFilters, input: string | URL = window.location.href): string { const url = new URL(input, window.location.origin); writeCommon(url.searchParams, filters); return url.toString(); }
export function writeSmartState(state: { filters: SmartInsightFilters }, input: string | URL = window.location.href): string { const url = new URL(input, window.location.origin); url.searchParams.delete('tab'); url.searchParams.delete('ruleVersionId'); writeCommon(url.searchParams, state.filters); return url.toString(); }
