import { useEffect, useState, type ReactNode } from 'react';
import { DashboardPagination } from '../../components/dashboard-pagination';
import type { AiInsightWorkspaceApi, InsightDetail, InsightPage, InsightRunStatus, SessionInsightFilters, SessionInsightRow, SmartInsightFilters, SmartInsightRow } from './ai-insight-workspace-api';
import { readSessionFilters, readSmartState, writeSessionFilters, writeSmartState } from './ai-insight-url-state';

export function AiInsightHeader({ title, description, actions }: { title: string; description: string; actions?: ReactNode }) { return <header className="ai-insight-header"><div><h1>{title}</h1><p>{description}</p></div><div className="ai-insight-actions">{actions}</div></header>; }
export function AiInsightQueryBar({ children, onSubmit, onReset, onRefresh, extraActions }: { children: ReactNode; onSubmit: () => void; onReset: () => void; onRefresh: () => void; extraActions?: ReactNode }) { return <form className="ai-insight-query" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><div className="ai-insight-fields">{children}</div><div className="ai-insight-query-actions">{extraActions}<button type="button" className="ai-insight-secondary" onClick={onReset}>重置</button><button type="button" className="ai-insight-secondary" onClick={onRefresh}>刷新</button><button type="submit" className="ai-insight-primary">查询</button></div></form>; }
export function AiInsightField({ label, children }: { label: string; children: ReactNode }) { return <label><span>{label}</span>{children}</label>; }
export function AiInsightStatusStrip({ status }: { status?: InsightRunStatus | undefined }) { const run = status?.run; if (!run || (run.status !== 'failed' && run.backlogCount <= 0 && status?.provider.state === 'ready')) return null; const messages: string[] = []; if (run.status === 'failed') messages.push(`最近一次分析失败${run.errorSummary ? `：${run.errorSummary}` : ''}`); if (run.backlogCount > 0) messages.push(`还有 ${run.backlogCount} 个会话等待分析`); if (status?.provider.state !== 'ready') messages.push('AI 服务暂不可用，已保留历史结果'); return <div className="ai-insight-status" role="status">{messages.join('；')}</div>; }
export function Avatar({ name, avatar }: { name: string; avatar: string }) { const fallback = name.trim().slice(0, 1) || '客'; return avatar ? <img className="ai-insight-avatar" src={avatar} alt="" /> : <span className="ai-insight-avatar ai-insight-avatar-fallback" aria-label={name}>{fallback}</span>; }
export function InsightPagination({ page, total, onChange }: { page: number; total: number; onChange: (page: number) => void }) { return <DashboardPagination page={page} pageSize={20} total={total} onPageChange={onChange} ariaLabel="AI 洞察分页" />; }
function resultLevel(value: unknown): string { const raw = typeof value === 'string' ? value : ''; return raw === 'high' ? '高' : raw === 'medium' ? '中' : raw === 'low' ? '低' : '证据不足'; }
function score(value: unknown): string { return typeof value === 'number' ? `${value}分` : '证据不足'; }
export function SessionTable({ page, onOpen }: { page: InsightPage<SessionInsightRow>; onOpen: (id: number) => void }) { return <div className="ai-insight-table-wrap"><table className="ai-insight-table"><thead><tr><th>沟通人</th><th>客户 / 群聊</th><th>分析结果</th><th>来源</th><th>分析时间</th><th>操作</th></tr></thead><tbody>{page.items.map((item) => <tr key={item.id} onClick={() => onOpen(item.id)}><td><span className="ai-insight-person"><Avatar {...item.employee} /><span>{item.employee.name}</span></span></td><td><span className="ai-insight-person"><Avatar {...item.target} /><span>{item.target.name}<small className="ai-insight-subline">{item.target.type === 'group' ? '群聊' : '客户'}</small></span></span></td><td><span className="ai-insight-summary">{item.summary || '暂无摘要'}</span><small className="ai-insight-subline">购买意向：{resultLevel(item.result?.customer && (item.result.customer as Record<string, unknown>).purchaseIntent && ((item.result.customer as Record<string, unknown>).purchaseIntent as Record<string, unknown>).level)} · 员工质检：{score(item.result?.employeeQa && (item.result.employeeQa as Record<string, unknown>).score)}</small></td><td>{item.sourceWindow.messageCount} 条消息</td><td>{formatTime(item.analysisAt)}</td><td><button className="ai-insight-secondary" type="button" onClick={(event) => { event.stopPropagation(); onOpen(item.id); }}>查看详情</button></td></tr>)}</tbody></table></div>; }
export function SmartTable({ page, onOpen }: { page: InsightPage<SmartInsightRow>; onOpen: (id: number) => void }) { return <div className="ai-insight-table-wrap"><table className="ai-insight-table"><thead><tr><th>沟通人</th><th>客户 / 群聊</th><th>关联规则</th><th>分析结果概述</th><th>分析时间</th><th>操作</th></tr></thead><tbody>{page.items.map((item) => <tr key={item.id} onClick={() => onOpen(item.id)}><td><span className="ai-insight-person"><Avatar {...item.employee} /><span>{item.employee.name}</span></span></td><td>{item.target.name}<small className="ai-insight-subline">{item.target.type === 'group' ? '群聊' : '客户'}</small></td><td>{item.rule?.name}<small className="ai-insight-subline">v{item.rule?.version}</small></td><td><span className="ai-insight-pill ai-insight-pill-neutral">{item.result?.matched === true ? '已命中' : '未命中'}</span><span className="ai-insight-summary">{item.summary || '暂无结论'}</span></td><td>{formatTime(item.analysisAt)}</td><td><button className="ai-insight-secondary" type="button" onClick={(event) => { event.stopPropagation(); onOpen(item.id); }}>查看详情</button></td></tr>)}</tbody></table></div>; }
export function InsightDrawer<T extends SessionInsightRow>({ detail, onClose, onNavigate }: { detail: InsightDetail<T>; onClose: () => void; onNavigate?: ((path: string) => void) | undefined }) { useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [onClose]); const result = detail.result ?? {}; const customer = (result.customer ?? {}) as Record<string, unknown>; const purchase = (customer.purchaseIntent ?? {}) as Record<string, unknown>; const churn = (customer.churnRisk ?? {}) as Record<string, unknown>; return <div className="ai-insight-drawer-layer"><button className="ai-insight-drawer-overlay" aria-label="关闭详情" onClick={onClose} /><aside className="ai-insight-drawer" role="dialog" aria-modal="true" aria-label="分析详情"><header className="ai-insight-drawer-header"><div><h2>分析详情</h2><p>{detail.target.name} · {detail.employee.name}</p></div><button className="ai-insight-close" type="button" onClick={onClose} aria-label="关闭">×</button></header><div className="ai-insight-drawer-body"><section className="ai-insight-detail-card"><h3>分析摘要</h3><p>{detail.summary || '暂无摘要'}</p><p>购买意向：{resultLevel(purchase.level)} {score(purchase.score)} · 流失风险：{resultLevel(churn.level)} {score(churn.score)}</p></section><section className="ai-insight-detail-card"><h3>来源窗口</h3><p>{formatTime(detail.sourceWindow.startedAt)} — {formatTime(detail.sourceWindow.endedAt)}，共 {detail.sourceWindow.messageCount} 条消息</p><p>模型：{detail.model || '未记录'} · 提示词版本：{detail.promptVersion || '未记录'}</p></section><section className="ai-insight-detail-card"><h3>证据消息</h3><ul className="ai-insight-evidence">{detail.messages.length ? detail.messages.map((message) => <li key={message.id}><small>{message.senderName} · {formatTime(message.time)} · {message.direction === 'outbound' ? '员工发送' : '客户发送'}</small><span>{message.content || '（非文本消息）'}</span></li>) : <li>暂无可展示的证据消息</li>}</ul></section><div className="ai-insight-rule-actions"><button className="ai-insight-secondary" type="button" onClick={() => { onNavigate?.(detail.conversationUrl); if (!onNavigate) window.location.href = detail.conversationUrl; }}>查看原会话</button><button className="ai-insight-primary" type="button" onClick={onClose}>完成</button></div></div></aside></div>; }
export function formatTime(value: string): string { if (!value) return '--'; return value.replace('T', ' ').slice(0, 16); }
export function useFilters<T extends SessionInsightFilters>(smart: boolean): [T, (value: T) => void] { const initial = smart ? readSmartState().filters : readSessionFilters(); const [filters, setFilters] = useState<T>(initial as T); const set = (value: T) => { setFilters(value); const url = smart ? writeSmartState({ filters: value as SmartInsightFilters }) : writeSessionFilters(value as SessionInsightFilters); window.history.replaceState({}, '', url); }; return [filters, set]; }
export type WorkspaceProps = { api: AiInsightWorkspaceApi; navigate?: (path: string) => void };
