CREATE TABLE IF NOT EXISTS `mochat_go_saas_billing_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '租户 ID',
  `event_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'renewal' COMMENT '账单事件类型',
  `package_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '套餐编码',
  `package_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '套餐名称',
  `previous_expires_at` timestamp NULL DEFAULT NULL COMMENT '续费前到期时间',
  `new_expires_at` timestamp NULL DEFAULT NULL COMMENT '续费后到期时间',
  `amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '金额，单位分',
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `paid_at` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `payment_method` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '支付方式',
  `external_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '外部订单号',
  `actor_user_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作人用户 ID',
  `actor_tenant_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '操作人租户 ID',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '备注',
  `metadata_json` json DEFAULT NULL COMMENT '扩展元数据',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mochat_go_saas_billing_tenant_time` (`tenant_id`, `created_at`),
  KEY `idx_mochat_go_saas_billing_event_time` (`event_type`, `created_at`),
  KEY `idx_mochat_go_saas_billing_actor_time` (`actor_user_id`, `created_at`),
  KEY `idx_mochat_go_saas_billing_order` (`external_order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 账单事件表';
