CREATE TABLE IF NOT EXISTS `mochat_go_saas_payment_orders` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台内部支付订单号',
  `tenant_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '租户 ID',
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'gateway' COMMENT '支付网关或供应商',
  `provider_order_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '支付供应商订单号',
  `idempotency_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建订单幂等键',
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/paid/failed/canceled',
  `package_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '套餐编码快照',
  `package_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '套餐名称快照',
  `billing_cycle` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'custom' COMMENT 'monthly/yearly/custom/lifetime',
  `service_expires_at` timestamp NULL DEFAULT NULL COMMENT '支付成功后服务期截止时间',
  `amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '应收金额，单位分',
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `checkout_url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '外部收银台 URL',
  `checkout_expires_at` timestamp NULL DEFAULT NULL COMMENT '订单支付截止时间',
  `attempt_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付状态事件次数',
  `dunning_attempts` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '已生成催收次数',
  `max_dunning_attempts` int(10) unsigned NOT NULL DEFAULT '3' COMMENT '最大催收次数',
  `next_dunning_at` timestamp NULL DEFAULT NULL COMMENT '下次催收时间',
  `last_dunning_at` timestamp NULL DEFAULT NULL COMMENT '最近催收时间',
  `latest_webhook_event_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `billing_event_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `paid_at` timestamp NULL DEFAULT NULL,
  `failed_at` timestamp NULL DEFAULT NULL,
  `canceled_at` timestamp NULL DEFAULT NULL,
  `failure_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `failure_message` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `version` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '乐观锁版本',
  `created_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `created_by_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `metadata_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_orders_no` (`order_no`),
  UNIQUE KEY `uni_mochat_go_saas_payment_orders_idempotency` (`tenant_id`, `idempotency_key`),
  UNIQUE KEY `uni_mochat_go_saas_payment_orders_provider_no` (`provider`, `provider_order_no`),
  KEY `idx_mochat_go_saas_payment_orders_tenant_status` (`tenant_id`, `status`, `created_at`),
  KEY `idx_mochat_go_saas_payment_orders_status_expiry` (`status`, `checkout_expires_at`, `id`),
  KEY `idx_mochat_go_saas_payment_orders_dunning` (`status`, `next_dunning_at`, `dunning_attempts`, `id`),
  KEY `idx_mochat_go_saas_payment_orders_package` (`package_code`, `status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 支付订单表';

CREATE TABLE IF NOT EXISTS `mochat_go_saas_payment_webhook_events` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'gateway',
  `event_id` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '供应商事件 ID',
  `event_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `order_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `order_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `provider_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'received' COMMENT 'received/processed/ignored/failed',
  `payload_sha256` char(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `signature_timestamp` bigint(20) NOT NULL DEFAULT '0',
  `attempts` int(10) unsigned NOT NULL DEFAULT '1',
  `occurred_at` timestamp NULL DEFAULT NULL,
  `processed_at` timestamp NULL DEFAULT NULL,
  `last_error` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `payload_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_webhook_event` (`provider`, `event_id`),
  KEY `idx_mochat_go_saas_payment_webhook_order_time` (`order_no`, `created_at`),
  KEY `idx_mochat_go_saas_payment_webhook_status_time` (`status`, `created_at`),
  KEY `idx_mochat_go_saas_payment_webhook_order_id` (`order_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 支付回调事件账本';
