ALTER TABLE `mochat_go_saas_payment_orders`
  ADD COLUMN `invoice_pending_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '已申请但未开具的蓝票预占金额，单位分' AFTER `refunded_amount_cents`,
  ADD COLUMN `invoiced_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '已开具蓝票金额，单位分' AFTER `invoice_pending_amount_cents`,
  ADD COLUMN `credit_pending_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '已申请但未开具的红票预占金额，单位分' AFTER `invoiced_amount_cents`,
  ADD COLUMN `credited_amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '已开具红票金额，单位分' AFTER `credit_pending_amount_cents`,
  ADD COLUMN `latest_invoice_document_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '最近发票单据 ID' AFTER `latest_refund_id`,
  ADD KEY `idx_mochat_go_saas_payment_orders_invoice` (`status`, `invoice_pending_amount_cents`, `credit_pending_amount_cents`, `id`);

CREATE TABLE IF NOT EXISTS `mochat_go_saas_billing_profiles` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `invoice_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal' COMMENT 'normal/special',
  `invoice_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tax_identifier` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `phone` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `registered_address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `bank_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `bank_account` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `recipient_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `updated_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `updated_by_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_billing_profiles_tenant` (`tenant_id`),
  KEY `idx_mochat_go_saas_billing_profiles_status` (`status`, `updated_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 租户开票资料';

CREATE TABLE IF NOT EXISTS `mochat_go_saas_invoice_documents` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `document_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台内部发票单据号',
  `tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `payment_order_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `order_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `kind` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'invoice' COMMENT 'invoice/credit_note',
  `original_document_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '红票对应的原蓝票 ID',
  `idempotency_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'requested' COMMENT 'requested/processing/issued/failed/canceled',
  `amount_cents` bigint(20) unsigned NOT NULL DEFAULT '0',
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY',
  `invoice_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  `invoice_title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tax_identifier` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `phone` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `registered_address` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `bank_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `bank_account` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `recipient_name` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'manual',
  `provider_document_no` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `document_url` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `operation_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `requested_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `requested_by_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `processed_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `processed_by_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `requested_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `processing_at` timestamp NULL DEFAULT NULL,
  `issued_at` timestamp NULL DEFAULT NULL,
  `failed_at` timestamp NULL DEFAULT NULL,
  `canceled_at` timestamp NULL DEFAULT NULL,
  `failure_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `failure_message` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `metadata_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_invoice_documents_no` (`document_no`),
  UNIQUE KEY `uni_mochat_go_saas_invoice_documents_idempotency` (`tenant_id`, `idempotency_key`),
  UNIQUE KEY `uni_mochat_go_saas_invoice_documents_provider_no` (`provider`, `provider_document_no`),
  KEY `idx_mochat_go_saas_invoice_documents_order_status` (`payment_order_id`, `kind`, `status`, `id`),
  KEY `idx_mochat_go_saas_invoice_documents_tenant_status` (`tenant_id`, `status`, `created_at`, `id`),
  KEY `idx_mochat_go_saas_invoice_documents_original` (`original_document_id`, `kind`, `status`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 蓝票与红票单据账本';
