CREATE TABLE IF NOT EXISTS `mochat_go_saas_payment_settlement_batches` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `batch_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台结算批次号',
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '支付渠道',
  `provider_settlement_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '渠道结算批次号',
  `period_start` timestamp NULL DEFAULT NULL,
  `period_end` timestamp NULL DEFAULT NULL,
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY',
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'reconciled' COMMENT 'reconciled/closed',
  `source_sha256` char(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始导入内容摘要',
  `entry_count` int(10) unsigned NOT NULL DEFAULT '0',
  `payment_count` int(10) unsigned NOT NULL DEFAULT '0',
  `refund_count` int(10) unsigned NOT NULL DEFAULT '0',
  `matched_count` int(10) unsigned NOT NULL DEFAULT '0',
  `issue_count` int(10) unsigned NOT NULL DEFAULT '0',
  `open_issue_count` int(10) unsigned NOT NULL DEFAULT '0',
  `resolved_issue_count` int(10) unsigned NOT NULL DEFAULT '0',
  `ignored_issue_count` int(10) unsigned NOT NULL DEFAULT '0',
  `total_amount_cents` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道交易金额合计，收款为正、退款为负',
  `total_fee_cents` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道手续费合计',
  `total_net_cents` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道净结算金额合计',
  `difference_amount_cents` bigint(20) NOT NULL DEFAULT '0' COMMENT '渠道金额与内部账本差额合计',
  `imported_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `imported_by_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `imported_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `reconciled_at` timestamp NULL DEFAULT NULL,
  `closed_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `closed_at` timestamp NULL DEFAULT NULL,
  `close_reason` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `remark` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_batch_no` (`batch_no`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_provider_no` (`provider`, `provider_settlement_no`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_source` (`provider`, `source_sha256`),
  KEY `idx_mochat_go_saas_payment_settlement_status_time` (`status`, `imported_at`, `id`),
  KEY `idx_mochat_go_saas_payment_settlement_provider_time` (`provider`, `period_end`, `id`),
  KEY `idx_mochat_go_saas_payment_settlement_issues` (`status`, `open_issue_count`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 支付渠道结算批次';

CREATE TABLE IF NOT EXISTS `mochat_go_saas_payment_settlement_entries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `batch_id` bigint(20) unsigned NOT NULL,
  `line_no` int(10) unsigned NOT NULL,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_transaction_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '渠道交易流水号',
  `transaction_type` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'payment/refund',
  `order_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `provider_order_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `refund_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `provider_refund_no` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `amount_cents` bigint(20) NOT NULL COMMENT '收款为正、退款为负',
  `fee_cents` bigint(20) NOT NULL DEFAULT '0',
  `net_amount_cents` bigint(20) NOT NULL COMMENT '必须等于 amount_cents + fee_cents',
  `currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CNY',
  `occurred_at` timestamp NULL DEFAULT NULL,
  `matched_payment_order_id` bigint(20) unsigned DEFAULT NULL,
  `matched_refund_id` bigint(20) unsigned DEFAULT NULL,
  `matched_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `matched_internal_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `expected_amount_cents` bigint(20) NOT NULL DEFAULT '0',
  `expected_currency` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `expected_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `reconciliation_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'missing_internal' COMMENT 'matched/missing_internal/identifier_conflict/status_mismatch/currency_mismatch/amount_mismatch',
  `difference_amount_cents` bigint(20) NOT NULL DEFAULT '0',
  `issue_codes_json` json DEFAULT NULL,
  `issue_message` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `handling_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open' COMMENT 'none/open/resolved/ignored',
  `handled_by_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `handled_by_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `handled_at` timestamp NULL DEFAULT NULL,
  `handling_reason` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `raw_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_line` (`batch_id`, `line_no`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_transaction` (`provider`, `provider_transaction_no`, `transaction_type`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_order_match` (`matched_payment_order_id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_refund_match` (`matched_refund_id`),
  KEY `idx_mochat_go_saas_payment_settlement_entry_batch_status` (`batch_id`, `reconciliation_status`, `handling_status`, `line_no`),
  KEY `idx_mochat_go_saas_payment_settlement_entry_order` (`order_no`, `provider_order_no`),
  KEY `idx_mochat_go_saas_payment_settlement_entry_refund` (`refund_no`, `provider_refund_no`),
  KEY `idx_mochat_go_saas_payment_settlement_entry_tenant` (`matched_tenant_id`, `occurred_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 支付渠道结算明细';
