CREATE TABLE IF NOT EXISTS `mochat_go_saas_payment_settlement_sync_states` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '支付渠道',
  `cursor` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'Bridge 增量游标',
  `active_run_id` bigint(20) unsigned DEFAULT NULL COMMENT '当前运行中的同步记录',
  `last_attempt_at` timestamp NULL DEFAULT NULL,
  `last_success_at` timestamp NULL DEFAULT NULL,
  `last_error` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_sync_provider` (`provider`),
  KEY `idx_mochat_go_saas_payment_settlement_sync_active` (`active_run_id`, `last_attempt_at`),
  KEY `idx_mochat_go_saas_payment_settlement_sync_success` (`last_success_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 支付结算同步游标';

CREATE TABLE IF NOT EXISTS `mochat_go_saas_payment_settlement_sync_runs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `run_no` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '平台同步运行号',
  `provider` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '支付渠道',
  `source` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'cron/manual',
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'running' COMMENT 'running/succeeded/previewed/failed',
  `dry_run` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `cursor_before` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `cursor_after` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `fetched_page_count` int(10) unsigned NOT NULL DEFAULT '0',
  `fetched_batch_count` int(10) unsigned NOT NULL DEFAULT '0',
  `imported_batch_count` int(10) unsigned NOT NULL DEFAULT '0',
  `idempotent_batch_count` int(10) unsigned NOT NULL DEFAULT '0',
  `entry_count` int(10) unsigned NOT NULL DEFAULT '0',
  `issue_count` int(10) unsigned NOT NULL DEFAULT '0',
  `open_issue_count` int(10) unsigned NOT NULL DEFAULT '0',
  `started_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` timestamp NULL DEFAULT NULL,
  `error_message` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `actor_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `actor_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `operation_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uni_mochat_go_saas_payment_settlement_sync_run_no` (`run_no`),
  KEY `idx_mochat_go_saas_payment_settlement_sync_run_provider` (`provider`, `started_at`, `id`),
  KEY `idx_mochat_go_saas_payment_settlement_sync_run_status` (`status`, `started_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Go 独立版 SaaS 支付结算同步运行记录';
