CREATE TABLE IF NOT EXISTS `mochat_go_saas_admin_audit_anchor_checkpoints` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `checkpoint_no` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `checkpoint_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `chain_version` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `anchor_log_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `anchor_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `legacy_log_count` bigint(20) unsigned NOT NULL DEFAULT '0',
  `chain_head_log_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `chain_head_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `signed_log_count` bigint(20) unsigned NOT NULL DEFAULT '0',
  `signature_algorithm` varchar(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'hmac-sha256',
  `key_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `signature` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `artifact_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `artifact_sha256` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `artifact_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'pending/exported/failed',
  `artifact_error` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `verification_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending' COMMENT 'pending/passed/failed',
  `verification_error` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `source` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'admin_manual',
  `actor_user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `actor_tenant_id` int(10) unsigned NOT NULL DEFAULT '0',
  `signed_at` char(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `exported_at` datetime DEFAULT NULL,
  `last_verified_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mochat_go_saas_audit_anchor_no` (`checkpoint_no`),
  UNIQUE KEY `uk_mochat_go_saas_audit_anchor_fingerprint` (`checkpoint_fingerprint`),
  KEY `idx_mochat_go_saas_audit_anchor_tenant` (`tenant_id`, `id`),
  KEY `idx_mochat_go_saas_audit_anchor_status` (`verification_status`, `artifact_status`, `last_verified_at`),
  KEY `idx_mochat_go_saas_audit_anchor_key` (`key_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SaaS 总后台审计链 HMAC 签名锚点';
