-- Structured, conversation-scoped AI results for the two supported insight pages.
-- A source fingerprint makes daily reruns incremental and keeps historical
-- results immutable when the underlying archive changes.
CREATE TABLE IF NOT EXISTS `mochat_go_ai_analysis_rules` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL,
  `corp_id` int unsigned NOT NULL,
  `name` varchar(120) NOT NULL,
  `objective` varchar(500) NOT NULL,
  `conversation_types_json` json NOT NULL,
  `target_scope` varchar(24) NOT NULL DEFAULT 'all',
  `target_ids_json` json NOT NULL,
  `lookback_days` smallint unsigned NOT NULL DEFAULT 30,
  `minimum_messages` int unsigned NOT NULL DEFAULT 1,
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `current_version` int unsigned NOT NULL DEFAULT 1,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `updated_by` bigint unsigned NOT NULL DEFAULT 0,
  `deleted_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_rule_scope_status` (`tenant_id`,`corp_id`,`status`,`updated_at`),
  KEY `idx_ai_rule_scope_name` (`tenant_id`,`corp_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mochat_go_ai_analysis_rule_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL,
  `corp_id` int unsigned NOT NULL,
  `rule_id` bigint unsigned NOT NULL,
  `version` int unsigned NOT NULL,
  `objective` varchar(500) NOT NULL,
  `conversation_types_json` json NOT NULL,
  `target_scope` varchar(24) NOT NULL DEFAULT 'all',
  `target_ids_json` json NOT NULL,
  `lookback_days` smallint unsigned NOT NULL DEFAULT 30,
  `minimum_messages` int unsigned NOT NULL DEFAULT 1,
  `created_by` bigint unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_rule_version` (`tenant_id`,`corp_id`,`rule_id`,`version`),
  KEY `idx_ai_rule_version_scope` (`tenant_id`,`corp_id`,`rule_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mochat_go_ai_conversation_insights` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL,
  `corp_id` int unsigned NOT NULL,
  `analysis_type` varchar(24) NOT NULL,
  `rule_id` bigint unsigned NOT NULL DEFAULT 0,
  `rule_version_id` bigint unsigned NOT NULL DEFAULT 0,
  `conversation_key` varchar(191) NOT NULL,
  `employee_id` bigint unsigned NOT NULL DEFAULT 0,
  `employee_name` varchar(120) NOT NULL DEFAULT '',
  `employee_avatar` varchar(512) NOT NULL DEFAULT '',
  `target_type` varchar(24) NOT NULL DEFAULT '',
  `target_id` varchar(191) NOT NULL DEFAULT '',
  `target_name` varchar(191) NOT NULL DEFAULT '',
  `target_avatar` varchar(512) NOT NULL DEFAULT '',
  `source_started_at` datetime(6) NULL,
  `source_ended_at` datetime(6) NULL,
  `source_message_count` int unsigned NOT NULL DEFAULT 0,
  `source_fingerprint` char(64) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `summary` varchar(1200) NOT NULL DEFAULT '',
  `result_json` json NOT NULL,
  `error_summary` varchar(500) NOT NULL DEFAULT '',
  `provider` varchar(64) NOT NULL DEFAULT '',
  `model` varchar(128) NOT NULL DEFAULT '',
  `prompt_version` varchar(32) NOT NULL DEFAULT '',
  `generated_at` datetime(6) NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ai_conversation_source` (`tenant_id`,`corp_id`,`analysis_type`,`rule_version_id`,`conversation_key`,`source_fingerprint`),
  KEY `idx_ai_insight_scope_page` (`tenant_id`,`corp_id`,`analysis_type`,`status`,`generated_at`),
  KEY `idx_ai_insight_employee_page` (`tenant_id`,`corp_id`,`employee_id`,`analysis_type`,`generated_at`),
  KEY `idx_ai_insight_target_page` (`tenant_id`,`corp_id`,`target_id`,`analysis_type`,`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mochat_go_ai_insight_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int unsigned NOT NULL,
  `corp_id` int unsigned NOT NULL,
  `analysis_type` varchar(24) NOT NULL,
  `rule_version_id` bigint unsigned NOT NULL DEFAULT 0,
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `planned_at` datetime(6) NULL,
  `started_at` datetime(6) NULL,
  `finished_at` datetime(6) NULL,
  `candidate_count` int unsigned NOT NULL DEFAULT 0,
  `success_count` int unsigned NOT NULL DEFAULT 0,
  `failure_count` int unsigned NOT NULL DEFAULT 0,
  `backlog_count` int unsigned NOT NULL DEFAULT 0,
  `error_summary` varchar(500) NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ai_run_scope_type` (`tenant_id`,`corp_id`,`analysis_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
