CREATE TABLE IF NOT EXISTS `mochat_go_wework_callback_inbox` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` int(10) unsigned NOT NULL,
  `corp_id` int(10) unsigned NOT NULL,
  `event_key` char(64) COLLATE utf8mb4_bin NOT NULL,
  `payload_fingerprint` char(64) COLLATE utf8mb4_bin NOT NULL,
  `event_path` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `event_json` mediumtext COLLATE utf8mb4_bin NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  `attempt` int(10) unsigned NOT NULL DEFAULT 0,
  `lease_token` varchar(96) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `lease_fence` bigint(20) unsigned NOT NULL DEFAULT 0,
  `lease_expires_at` datetime(6) NULL DEFAULT NULL,
  `next_attempt_at` datetime(6) NULL DEFAULT NULL,
  `last_error` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `received_at` datetime(6) NOT NULL,
  `completed_at` datetime(6) NULL DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wework_callback_scope_event` (`tenant_id`,`corp_id`,`event_key`),
  KEY `idx_wework_callback_claim` (`status`,`next_attempt_at`,`lease_expires_at`,`id`),
  CONSTRAINT `fk_wework_callback_corp` FOREIGN KEY (`tenant_id`,`corp_id`) REFERENCES `mc_corp` (`tenant_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Durable WeWork callback acceptance and replay inbox';
