package dashboard

// These contracts are policy, not routing evidence. The catalog gate independently
// extracts reachable registrations from production Go dispatch and composition code.
var exactExemptDashboardRouteContracts = []string{
	"GET /dashboard/access/profile",
	"GET /dashboard/corp/weWorkCallback",
	"GET /dashboard/officialAccount/authEventCallback",
	"GET /dashboard/officialAccount/authRedirect/",
	"GET /dashboard/user/securityMFA",
	"POST /dashboard/corp/weWorkCallback",
	"POST /dashboard/officialAccount/authEventCallback",
	"POST /dashboard/officialAccount/authRedirect/",
	"POST /dashboard/user/auth",
	"POST /dashboard/user/authMFA",
	"POST /dashboard/auth/activate",
	"POST /dashboard/auth/activation/status",
	"POST /dashboard/auth/password/reset",
	"POST /dashboard/auth/password/reset-request",
	"GET /dashboard/auth/session",
	"POST /dashboard/auth/logout",
	"POST /dashboard/user/securityMFA",
	"PUT /dashboard/user/logout",
	"PUT /dashboard/user/securityMFA",
}

// ExactExemptDashboardRouteContracts returns a copy so callers cannot mutate
// the policy shared by the catalog gate and the runtime guard.
func ExactExemptDashboardRouteContracts() []string {
	return append([]string(nil), exactExemptDashboardRouteContracts...)
}

// publicDashboardRouteContracts are the exact exemptions that cannot have an
// authenticated tenant yet. Every other exemption still passes the tenant gate.
var publicDashboardRouteContracts = []string{
	"GET /dashboard/corp/weWorkCallback",
	"GET /dashboard/officialAccount/authEventCallback",
	"GET /dashboard/officialAccount/authRedirect/",
	"POST /dashboard/corp/weWorkCallback",
	"POST /dashboard/officialAccount/authEventCallback",
	"POST /dashboard/officialAccount/authRedirect/",
	"POST /dashboard/user/auth",
	"POST /dashboard/user/authMFA",
	"POST /dashboard/auth/activate",
	"POST /dashboard/auth/activation/status",
	"POST /dashboard/auth/password/reset",
}

func PublicDashboardRouteContracts() []string {
	return append([]string(nil), publicDashboardRouteContracts...)
}

// pageMappedDashboardRouteContracts contains registered route templates whose
// page-RBAC mapping is expressed by the catalog/migration rather than by an
// individual permission constant in this package.
var pageMappedDashboardRouteContracts = []string{
	"GET /dashboard/reports/{kind}",
	"GET /dashboard/scrm/contacts/{contactId}/follow-ups",
	"POST /dashboard/scrm/contacts/{contactId}/follow-ups",
}

func PageMappedDashboardRouteContracts() []string {
	return append([]string(nil), pageMappedDashboardRouteContracts...)
}

// denyOnlyDashboardRouteContracts are registered endpoints that are intentionally
// unavailable to ordinary Dashboard users. A same-tenant superadmin may still use them.
var denyOnlyDashboardRouteContracts = []string{
	"POST /dashboard/ai-insight/run",
	"DELETE /dashboard/ai-insight/smart-analysis/rules",
	"POST /dashboard/ai-insight/smart-analysis/rules",
	"POST /dashboard/ai-insight/smart-analysis/rules/status",
	"PUT /dashboard/ai-insight/smart-analysis/rules",
	"GET /dashboard/role/permissionByUser",
	"DELETE /dashboard/acceptance/phase35",
	"DELETE /dashboard/autoTag/destroy",
	"DELETE /dashboard/contactBatchAdd/destroy",
	"DELETE /dashboard/contactBatchAdd/importDestroy",
	"DELETE /dashboard/contactField/destroy",
	"DELETE /dashboard/contactMessageBatchSend/destroy",
	"DELETE /dashboard/contactSop/destroy",
	"DELETE /dashboard/greeting/destroy",
	"DELETE /dashboard/lottery/destroy",
	"DELETE /dashboard/medium/destroy",
	"DELETE /dashboard/mediumGroup/destroy",
	"DELETE /dashboard/radar/destroy",
	"DELETE /dashboard/roomCalendar/destroy",
	"DELETE /dashboard/roomCalendar/destroyRoom",
	"DELETE /dashboard/roomClockIn/destroy",
	"DELETE /dashboard/roomFission/destroy",
	"DELETE /dashboard/roomInfinitePull/destroy",
	"DELETE /dashboard/roomMessageBatchSend/destroy",
	"DELETE /dashboard/roomQuality/destroy",
	"DELETE /dashboard/roomRemind/destroy",
	"DELETE /dashboard/roomSop/destroy",
	"DELETE /dashboard/roomTagPull/destroy",
	"DELETE /dashboard/roomWelcome/destroy",
	"DELETE /dashboard/shopCode/destroy",
	"DELETE /dashboard/workContactTag/destroy",
	"DELETE /dashboard/workContactTagGroup/destroy",
	"DELETE /dashboard/workFission/destroy",
	"DELETE /dashboard/workRoomGroup/destroy",
	"GET /dashboard/acceptance/phase35",
	"GET /dashboard/autoTag/index",
	"GET /dashboard/autoTag/show",
	"GET /dashboard/autoTag/showContactKeyWord",
	"GET /dashboard/autoTag/showContactRoom",
	"GET /dashboard/autoTag/showContactTime",
	"GET /dashboard/channelCode/contact",
	"GET /dashboard/channelCode/show",
	"GET /dashboard/channelCode/statistics",
	"GET /dashboard/channelCode/statisticsIndex",
	"GET /dashboard/channelCodeGroup/detail",
	"GET /dashboard/channelCodeGroup/index",
	"GET /dashboard/chat/media/{id}/content",
	"GET /dashboard/chatTool/config",
	"GET /dashboard/clockIn/index",
	"GET /dashboard/contactBatchAdd/dataStatistic",
	"GET /dashboard/contactBatchAdd/importIndex",
	"GET /dashboard/contactBatchAdd/index",
	"GET /dashboard/contactBatchAdd/remind",
	"GET /dashboard/contactBatchAdd/settingEdit",
	"GET /dashboard/contactField/index",
	"GET /dashboard/contactField/portrait",
	"GET /dashboard/contactField/show",
	"GET /dashboard/contactFieldPivot/index",
	"GET /dashboard/contactMessageBatchSend/contactReceiveIndex",
	"GET /dashboard/contactMessageBatchSend/employeeSendIndex",
	"GET /dashboard/contactMessageBatchSend/messageShow",
	"GET /dashboard/contactMessageBatchSend/show",
	"GET /dashboard/contactMessageBatchSend/showRoom",
	"GET /dashboard/contactSop/index",
	"GET /dashboard/contactSop/info",
	"GET /dashboard/contactSop/page",
	"GET /dashboard/contactTransfer/saveUnassignedList",
	"GET /dashboard/corpData/index",
	"GET /dashboard/corpData/lineChat",
	"GET /dashboard/external/tenantIndex",
	"GET /dashboard/friendsCircle/export",
	"GET /dashboard/greeting/index",
	"GET /dashboard/greeting/show",
	"GET /dashboard/lottery/index",
	"GET /dashboard/lottery/info",
	"GET /dashboard/lottery/page",
	"GET /dashboard/lottery/share",
	"GET /dashboard/lottery/show",
	"GET /dashboard/lottery/showContact",
	"GET /dashboard/lottery/writeOff",
	"GET /dashboard/medium/show",
	"GET /dashboard/officialAccount/getPreAuthUrl",
	"GET /dashboard/officialAccount/index",
	"GET /dashboard/officialAccount/set",
	"GET /dashboard/radar/index",
	"GET /dashboard/radar/indexChannel",
	"GET /dashboard/radar/indexChannelLink",
	"GET /dashboard/radar/info",
	"GET /dashboard/radar/page",
	"GET /dashboard/radar/radarArticle",
	"GET /dashboard/radar/show",
	"GET /dashboard/radar/showChannel",
	"GET /dashboard/radar/showContact",
	"GET /dashboard/roomCalendar/index",
	"GET /dashboard/roomCalendar/page",
	"GET /dashboard/roomCalendar/show",
	"GET /dashboard/roomClockIn/dayDetail",
	"GET /dashboard/roomClockIn/index",
	"GET /dashboard/roomClockIn/info",
	"GET /dashboard/roomClockIn/page",
	"GET /dashboard/roomClockIn/show",
	"GET /dashboard/roomClockIn/showContact",
	"GET /dashboard/roomFission/index",
	"GET /dashboard/roomFission/info",
	"GET /dashboard/roomFission/page",
	"GET /dashboard/roomFission/show",
	"GET /dashboard/roomFission/showContact",
	"GET /dashboard/roomFission/showRoom",
	"GET /dashboard/roomFission/writeOff",
	"GET /dashboard/roomInfinitePull/index",
	"GET /dashboard/roomInfinitePull/info",
	"GET /dashboard/roomInfinitePull/page",
	"GET /dashboard/roomMessageBatchSend/remind",
	"GET /dashboard/roomMessageBatchSend/roomOwnerSendIndex",
	"GET /dashboard/roomMessageBatchSend/roomReceiveIndex",
	"GET /dashboard/roomMessageBatchSend/show",
	"GET /dashboard/roomQuality/contactDetail",
	"GET /dashboard/roomQuality/index",
	"GET /dashboard/roomQuality/info",
	"GET /dashboard/roomQuality/page",
	"GET /dashboard/roomQuality/showContact",
	"GET /dashboard/roomRemind/index",
	"GET /dashboard/roomRemind/info",
	"GET /dashboard/roomRemind/page",
	"GET /dashboard/roomRemind/status",
	"GET /dashboard/roomSop/index",
	"GET /dashboard/roomSop/info",
	"GET /dashboard/roomSop/page",
	"GET /dashboard/roomTagPull/chooseContact",
	"GET /dashboard/roomTagPull/contactDetail",
	"GET /dashboard/roomTagPull/index",
	"GET /dashboard/roomTagPull/remindSend",
	"GET /dashboard/roomTagPull/roomList",
	"GET /dashboard/roomTagPull/show",
	"GET /dashboard/roomTagPull/showContact",
	"GET /dashboard/roomWelcome/index",
	"GET /dashboard/roomWelcome/select",
	"GET /dashboard/roomWelcome/show",
	"GET /dashboard/scrm/tag-groups",
	"GET /dashboard/sensitiveWords/page",
	"GET /dashboard/shopCode/addressKeyWordList",
	"GET /dashboard/shopCode/index",
	"GET /dashboard/shopCode/info",
	"GET /dashboard/shopCode/location",
	"GET /dashboard/shopCode/page",
	"GET /dashboard/shopCode/pageInfo",
	"GET /dashboard/shopCode/searchCity",
	"GET /dashboard/shopCode/share",
	"GET /dashboard/shopCode/show",
	"GET /dashboard/shopCode/showContact",
	"GET /dashboard/shopCode/showShop",
	"GET /dashboard/statistic/employeeCounts",
	"GET /dashboard/statistic/employees",
	"GET /dashboard/statistic/employeesTrend",
	"GET /dashboard/statistic/index",
	"GET /dashboard/statistic/topList",
	"GET /dashboard/Task/AutoTag/KeyWordTag",
	"GET /dashboard/task/roomRemind",
	"GET /dashboard/workContact/source",
	"GET /dashboard/workContact/track",
	"GET /dashboard/workContactRoom/index",
	"GET /dashboard/workContactTag/allTag",
	"GET /dashboard/workContactTag/contactTagList",
	"GET /dashboard/workContactTag/detail",
	"GET /dashboard/workContactTag/index",
	"GET /dashboard/workContactTagGroup/detail",
	"GET /dashboard/workContactTagGroup/index",
	"GET /dashboard/workDepartment/index",
	"GET /dashboard/workDepartment/memberIndex",
	"GET /dashboard/workDepartment/showEmployee",
	"GET /dashboard/workEmployee/searchCondition",
	"GET /dashboard/workEmployeeDepartment/memberIndex",
	"GET /dashboard/workFission/chooseContact",
	"GET /dashboard/workFission/index",
	"GET /dashboard/workFission/info",
	"GET /dashboard/workFission/inviteData",
	"GET /dashboard/workFission/inviteDetail",
	"GET /dashboard/workFission/show",
	"GET /dashboard/workFission/statistics",
	"GET /dashboard/workMessage/index",
	"GET /dashboard/workMessageConfig/corpIndex",
	"GET /dashboard/workMessageConfig/corpShow",
	"GET /dashboard/workMessageConfig/stepCreate",
	"GET /dashboard/workRoom/statistics",
	"GET /dashboard/workRoom/statisticsIndex",
	"GET /dashboard/workRoomAutoPull/show",
	"GET /dashboard/workRoomGroup/index",
	"PATCH /dashboard/scrm/orders/{id}/transition",
	"POST /dashboard/acceptance/phase35",
	"POST /dashboard/agent/store",
	"POST /dashboard/agent/txtVerifyUpload",
	"POST /dashboard/autoTag/store",
	"POST /dashboard/channelCodeGroup/store",
	"POST /dashboard/common/upload",
	"POST /dashboard/common/uploadFile",
	"POST /dashboard/contactBatchAdd/allot",
	"POST /dashboard/contactBatchAdd/importStore",
	"POST /dashboard/contactBatchAdd/remind",
	"POST /dashboard/contactBatchAdd/settingUpdate",
	"POST /dashboard/contactField/store",
	"POST /dashboard/contactMessageBatchSend/remind",
	"POST /dashboard/contactSop/store",
	"POST /dashboard/friendsCircle/providerCallback",
	"POST /dashboard/greeting/store",
	"POST /dashboard/lottery/store",
	"POST /dashboard/medium/referenceCheck",
	"POST /dashboard/message-intercept/evaluate",
	"POST /dashboard/radar/store",
	"POST /dashboard/radar/storeChannel",
	"POST /dashboard/radar/storeChannelLink",
	"POST /dashboard/refuse-archive/sync",
	"POST /dashboard/risk/evaluate",
	"POST /dashboard/roomCalendar/addRoom",
	"POST /dashboard/roomCalendar/store",
	"POST /dashboard/roomClockIn/store",
	"POST /dashboard/roomFission/invite",
	"POST /dashboard/roomFission/store",
	"POST /dashboard/roomInfinitePull/store",
	"POST /dashboard/roomQuality/store",
	"POST /dashboard/roomRemind/store",
	"POST /dashboard/roomSop/store",
	"POST /dashboard/roomTagPull/filterContact",
	"POST /dashboard/roomTagPull/store",
	"POST /dashboard/roomWelcome/store",
	"POST /dashboard/shopCode/pageSet",
	"POST /dashboard/shopCode/store",
	"POST /dashboard/shopCode/updateEmployee",
	"POST /dashboard/shopCode/updateQrcode",
	"POST /dashboard/silent-customer/evaluate",
	"POST /dashboard/timeout-warning/evaluate",
	"POST /dashboard/workContact/batchLabeling",
	"POST /dashboard/workContactTag/store",
	"POST /dashboard/workContactTagGroup/store",
	"POST /dashboard/workFission/invite",
	"POST /dashboard/workFission/store",
	"POST /dashboard/workMessageConfig/corpStore",
	"POST /dashboard/workRoomGroup/store",
	"PUT /dashboard/autoTag/onOff",
	"PUT /dashboard/channelCodeGroup/move",
	"PUT /dashboard/channelCodeGroup/update",
	"PUT /dashboard/contactField/batchUpdate",
	"PUT /dashboard/contactField/statusUpdate",
	"PUT /dashboard/contactField/update",
	"PUT /dashboard/contactFieldPivot/update",
	"PUT /dashboard/contactSop/setEmployee",
	"PUT /dashboard/contactSop/state",
	"PUT /dashboard/contactSop/update",
	"PUT /dashboard/greeting/update",
	"PUT /dashboard/lottery/batchContactTags",
	"PUT /dashboard/lottery/update",
	"PUT /dashboard/medium/groupUpdate",
	"PUT /dashboard/medium/update",
	"PUT /dashboard/mediumGroup/update",
	"PUT /dashboard/radar/update",
	"PUT /dashboard/roomCalendar/update",
	"PUT /dashboard/roomClockIn/batchContactTags",
	"PUT /dashboard/roomClockIn/update",
	"PUT /dashboard/roomFission/update",
	"PUT /dashboard/roomInfinitePull/update",
	"PUT /dashboard/roomQuality/status",
	"PUT /dashboard/roomQuality/update",
	"PUT /dashboard/roomRemind/update",
	"PUT /dashboard/roomSop/setRoom",
	"PUT /dashboard/roomSop/state",
	"PUT /dashboard/roomSop/update",
	"PUT /dashboard/roomWelcome/update",
	"PUT /dashboard/shopCode/batchContactTags",
	"PUT /dashboard/shopCode/status",
	"PUT /dashboard/shopCode/update",
	"PUT /dashboard/user/passwordUpdate",
	"PUT /dashboard/workContact/synContact",
	"PUT /dashboard/workContact/update",
	"PUT /dashboard/workContactTag/move",
	"PUT /dashboard/workContactTag/synContactTag",
	"PUT /dashboard/workContactTag/update",
	"PUT /dashboard/workContactTagGroup/update",
	"PUT /dashboard/workEmployee/synEmployee",
	"PUT /dashboard/workFission/update",
	"PUT /dashboard/workMessageConfig/stepUpdate",
	"PUT /dashboard/workRoom/batchUpdate",
	"PUT /dashboard/workRoom/syn",
	"PUT /dashboard/workRoomAutoPull/move",
	"PUT /dashboard/workRoomAutoPull/update",
	"PUT /dashboard/workRoomGroup/update",
}

// DenyOnlyDashboardRouteContracts returns the exact registered contracts that
// ordinary Dashboard sessions must never inherit from a page permission.
func DenyOnlyDashboardRouteContracts() []string {
	return append([]string(nil), denyOnlyDashboardRouteContracts...)
}
