package dashboard

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestSaaSAdminPageRedirectsToMVPApp(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/dashboard/saasAdmin/page", nil)
	rec := httptest.NewRecorder()

	ServeSaaSAdminPage(rec, req)

	if rec.Code != http.StatusTemporaryRedirect {
		t.Fatalf("status = %d body=%s", rec.Code, rec.Body.String())
	}
	if location := rec.Header().Get("Location"); location != "/saas-admin/" {
		t.Fatalf("Location = %q", location)
	}
	if cacheControl := rec.Header().Get("Cache-Control"); cacheControl != "no-store" {
		t.Fatalf("Cache-Control = %q", cacheControl)
	}
}

func TestSaaSAdminPageIncludesDailyReportWindowControls(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/dashboard/saasAdmin/page", nil)
	rec := httptest.NewRecorder()

	ServeSaaSAdminLegacyPage(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d body=%s", rec.Code, rec.Body.String())
	}
	body := rec.Body.String()
	for _, want := range []string{
		`aria-label="当前平台权限"`,
		`id="accessProfileState"`,
		`id="accessPermissionSummary"`,
		`aria-label="平台权限治理"`,
		`id="accessRoleCode"`,
		`id="accessPermissionOptions"`,
		`id="accessRoles"`,
		`id="accessAssignments"`,
		`function hasPlatformPermission(permission)`,
		`localStorage.getItem('ACCESS_TOKEN')`,
		`function normalizeStoredToken(value)`,
		`const parsed = JSON.parse(raw)`,
		`const raw = normalizeStoredToken(tokenInput.value)`,
		`function loadAccessProfile()`,
		`function loadAccessGovernance()`,
		`function saveAccessRole()`,
		`function saveAccessAssignment(userId, version)`,
		`fetch('/dashboard/saasAdmin/accessProfile'`,
		`fetch('/dashboard/saasAdmin/accessRoles'`,
		`fetch('/dashboard/saasAdmin/accessAssignments?'`,
		`fetch('/dashboard/saasAdmin/accessRole'`,
		`fetch('/dashboard/saasAdmin/accessAssignment'`,
		`aria-label="租户上线准备度"`,
		`id="tenantReadinessFilterState"`,
		`id="tenantReadinessTenantId"`,
		`id="tenantReadinessKeyword"`,
		`id="tenantReadinessSummary"`,
		`id="tenantReadinessTenants"`,
		`function renderTenantReadiness(data)`,
		`async function loadTenantReadiness()`,
		`function focusTenantReadinessAction(button)`,
		`业务租户核心就绪`,
		`当前筛选没有业务租户`,
		`fetch('/dashboard/saasAdmin/tenantReadiness?'`,
		`data-readiness-workspace=`,
		`function renderSummary(summary, tenantPopulation)`,
		`tenantPopulation === 'business_tenants' ? '业务租户' : '租户数'`,
		`renderSummary(data.summary || {}, data.tenantPopulation || '')`,
		`aria-label="品牌与白标中心"`,
		`id="brandingTenantFilter"`,
		`id="brandingProfiles"`,
		`id="brandingEditor"`,
		`id="brandingPrimaryColor" type="color"`,
		`id="brandingPreview"`,
		`id="saveBrandingProfile"`,
		`function renderBrandingProfiles(items)`,
		`function fillBrandingEditor(profile)`,
		`function renderBrandingPreview()`,
		`/saas$/i.test(baseTitle)`,
		`async function loadBrandingProfiles()`,
		`async function saveBrandingProfile()`,
		`fetch('/dashboard/saasAdmin/brandingProfiles?'`,
		`fetch('/dashboard/saasAdmin/brandingProfile'`,
		`'platform.branding.manage'`,
		`aria-label="租户自定义域名中心"`,
		`id="tenantDomainTenantFilter"`,
		`id="tenantDomainCreateHostname"`,
		`id="tenantDomains"`,
		`id="tenantDomainDeliveryStatus"`,
		`id="tenantDomainDeliveryJobs"`,
		`id="tenantDomainActionDialog"`,
		`function renderTenantDomains(items)`,
		`function renderTenantDomainDeliveryJobs(items)`,
		`async function loadTenantDomains()`,
		`async function loadTenantDomainDeliveryJobs()`,
		`async function applyTenantDomainDeliveryAction(payload)`,
		`async function createTenantDomain()`,
		`async function applyTenantDomainAction(action)`,
		`function requestTenantDomainAction(button)`,
		`async function copyTenantDomainValue(value)`,
		`approvalActionRequired('tenant.domain.create', 0)`,
		`requestHighRiskApproval('tenant.domain.create'`,
		`提交添加审批`,
		`approvalActionRequired('tenant.domain.command', 0)`,
		`requestHighRiskApproval('tenant.domain.command'`,
		`提交主域名审批`,
		`提交停用审批`,
		`function renderTenantStatusApprovalState()`,
		`approvalActionRequired(actionType, 0)`,
		`'tenant.enable'`,
		`提交启用审批`,
		`提交删除审批`,
		`fetch('/dashboard/saasAdmin/tenantDomains?'`,
		`fetch('/dashboard/saasAdmin/tenantDomain'`,
		`fetch('/dashboard/saasAdmin/tenantDomainDeliveryJobs?'`,
		`fetch('/dashboard/saasAdmin/tenantDomainDelivery'`,
		`'platform.domains.manage'`,
		`路由 / TLS 交付`,
		`轮换后域名会立即退出路由`,
		`aria-label="身份与访问安全中心"`,
		`id="identityTenantFilter"`,
		`id="identitySecuritySummary"`,
		`id="identityPolicyEditor"`,
		`id="identityRequireMfa"`,
		`id="identityUsers"`,
		`id="identitySessions"`,
		`id="identityIncidents"`,
		`id="identityEvents"`,
		`function renderIdentitySecuritySummary(summary, policy, config)`,
		`function renderIdentityUsers(items)`,
		`function renderIdentitySessions(items)`,
		`function renderIdentityIncidents(items)`,
		`function renderIdentityEvents(items)`,
		`async function loadIdentitySecurity()`,
		`async function saveIdentityPolicy()`,
		`function renderIdentityPolicyApprovalState()`,
		`requestHighRiskApproval('identity.policy.update'`,
		`approvalActionRequired('identity.mfa.reset'`,
		`requestHighRiskApproval(approvalAction, payload`,
		`全部活动会话将立即失效`,
		`async function updateIdentityUser(button)`,
		`async function revokeIdentitySession(button)`,
		`async function updateIdentityIncident(button)`,
		`fetch('/dashboard/saasAdmin/identityOverview?'`,
		`fetch('/dashboard/saasAdmin/identitySessions?'`,
		`fetch('/dashboard/saasAdmin/identityLoginEvents?'`,
		`fetch('/dashboard/saasAdmin/identityIncidents?'`,
		`'/dashboard/saasAdmin/identityPolicy'`,
		`'/dashboard/saasAdmin/identitySession'`,
		`'/dashboard/saasAdmin/identityUser'`,
		`'/dashboard/saasAdmin/identityMFA'`,
		`'/dashboard/saasAdmin/identityIncident'`,
		`'platform.identity.manage'`,
		`id="notificationPolicySecurity"`,
		`function renderNotificationWebhookSecurity(security)`,
		`DNS 绑定 / 同源重定向 / 直连出站`,
		`aria-label="通知凭据保护"`,
		`id="notificationCredentialProtection"`,
		`id="notificationCredentialTenantId"`,
		`id="notificationCredentialLimit"`,
		`id="rotateNotificationCredentials"`,
		`function renderNotificationCredentialProtection(protection)`,
		`function applyNotificationCredentialRotationControl()`,
		`Number(notificationCredentialProtection.rotationRequiredCount || 0) > 0`,
		`async function rotateNotificationCredentials()`,
		`fetch('/dashboard/saasAdmin/notificationCredentialRotation'`,
		`webhookCredentialProtection === 'encrypted'`,
		`aria-label="平台健康中心"`,
		`id="systemHealthFailureWindow"`,
		`id="systemHealthNotificationStale"`,
		`id="systemIncidentStatus"`,
		`id="systemIncidentSeverity"`,
		`id="systemHealthSummary"`,
		`id="systemHealthChecks"`,
		`id="systemIncidents"`,
		`id="systemHealthScans"`,
		`function renderSystemHealthSummary(summary, activeIncidentCount)`,
		`function renderSystemHealthChecks(items)`,
		`function renderSystemIncidents(items)`,
		`function renderSystemHealthScans(items)`,
		`async function loadSystemHealth()`,
		`async function runSystemHealthScan()`,
		`async function updateSystemIncident(button)`,
		`fetch('/dashboard/saasAdmin/systemHealth?'`,
		`fetch('/dashboard/saasAdmin/systemHealthScans?limit=30'`,
		`fetch('/dashboard/saasAdmin/systemIncidents?'`,
		`fetch('/dashboard/saasAdmin/systemHealthScan'`,
		`fetch('/dashboard/saasAdmin/systemIncident'`,
		`aria-label="备份与恢复治理"`,
		`id="backupConfigState"`,
		`id="backupPolicyEditor"`,
		`id="backupRequireEncryption"`,
		`id="backupRequireOffsiteReplica"`,
		`class="backup-run-table"`,
		`id="backupRuns"`,
		`class="backup-cleanup-table"`,
		`id="backupCleanupRuns"`,
		`id="restoreDrills"`,
		`id="backupRestoreDialog"`,
		`function renderBackupRuns(items)`,
		`function renderBackupCleanupRuns(items)`,
		`function renderRestoreDrills(items)`,
		`function renderInlineErrorDetails(value)`,
		`<details class="inline-error">`,
		`async function loadBackupOverview()`,
		`async function saveBackupPolicy()`,
		`async function requestBackupCleanup()`,
		`async function runBackupAction(action, backupRunId, cleanupRunId)`,
		`async function confirmBackupRestore()`,
		`action === 'replicate'`,
		`requestHighRiskApproval('backup.retention.cleanup'`,
		`data-backup-cleanup-retry=`,
		`检查/修复副本`,
		`自动创建临时隔离库，校验后立即销毁`,
		`fetch('/dashboard/saasAdmin/backupOverview?limit=100'`,
		`fetch('/dashboard/saasAdmin/backupPolicy'`,
		`fetch('/dashboard/saasAdmin/backupRun'`,
		`fetch('/dashboard/saasAdmin/restoreDrill'`,
		`'platform.backups.manage'`,
		`aria-label="租户数据合规中心"`,
		`id="complianceConfigState"`,
		`id="complianceInventoryState"`,
		`id="compliancePolicyEditor"`,
		`id="complianceRequireRecentExport"`,
		`id="complianceActions"`,
		`id="complianceHolds"`,
		`id="complianceExports"`,
		`id="complianceErasures"`,
		`id="complianceStepsDialog"`,
		`function renderComplianceHolds(items)`,
		`function renderComplianceExports(items)`,
		`requestHighRiskApproval('compliance.export.delete'`,
		`item.deletionStatus === 'pending'`,
		`继续删除`,
		`重试删除`,
		`function renderComplianceErasures(items)`,
		`async function loadComplianceOverview()`,
		`async function saveCompliancePolicy()`,
		`function renderCompliancePolicyApprovalState()`,
		`requestHighRiskApproval('compliance.policy.update'`,
		`async function requestComplianceErasure()`,
		`async function requestComplianceErasureApproval(erasure, reason, refresh)`,
		`async function loadComplianceErasureSteps(requestId)`,
		`fetch('/dashboard/saasAdmin/complianceOverview?tenantId='`,
		`compliancePost('/dashboard/saasAdmin/compliancePolicy'`,
		`compliancePost('/dashboard/saasAdmin/complianceLegalHold'`,
		`compliancePost('/dashboard/saasAdmin/complianceExport'`,
		`fetch('/dashboard/saasAdmin/complianceExportDownload?exportId='`,
		`compliancePost('/dashboard/saasAdmin/complianceErasure'`,
		`compliancePost('/dashboard/saasAdmin/approvalRequest'`,
		`fetch('/dashboard/saasAdmin/complianceErasureSteps?requestId='`,
		`'platform.compliance.manage'`,
		`aria-label="企业微信凭据保护"`,
		`id="weComCredentialTenantId"`,
		`id="weComCredentialLimit"`,
		`id="weComCredentialSummary"`,
		`id="rotateWeComCredentials"`,
		`function renderWeComCredentialProtection(protection)`,
		`function applyWeComCredentialRotationControl()`,
		`Number(weComCredentialProtection.rotationRequiredCount || 0) > 0`,
		`async function loadWeComCredentialProtection()`,
		`void loadWeComCredentialProtection()`,
		`async function rotateWeComCredentials()`,
		`fetch('/dashboard/saasAdmin/wecomCredentialProtection'`,
		`fetch('/dashboard/saasAdmin/wecomCredentialRotation'`,
		`aria-label="服务账号与 API Key"`,
		`id="serviceAccountTenantFilter"`,
		`id="serviceAccountSummary"`,
		`id="serviceAccountUsageAlertEnabled"`,
		`id="serviceAccountUsageWarningPercent"`,
		`id="serviceAccountRejectionWarningCount"`,
		`id="serviceAccountUsageAlertCooldownMinutes"`,
		`id="evaluateServiceAccountUsageAlerts"`,
		`id="viewServiceAccountUsageAlerts"`,
		`id="serviceAccountEditor"`,
		`id="serviceAccountScopes"`,
		`id="serviceAccountSecret"`,
		`.service-account-secret[hidden] { display: none; }`,
		`id="serviceAccountPlainTextKey"`,
		`id="serviceAccountKeyEditor"`,
		`id="serviceAccounts"`,
		`id="serviceAccountRevokeDialog"`,
		`id="confirmServiceAccountKeyRevoke"`,
		`id="serviceAccountRevokeReason"`,
		`function renderServiceAccounts(items)`,
		`function renderServiceAccountSummary(summary, protection, clientIPResolution)`,
		`clientIPResolution.trustProxyHeaders`,
		`来源 IP 解析`,
		`function serviceAccountKeyRetireExpired(key)`,
		`pepper 主密钥`,
		`密钥台账`,
		`宽限已结束`,
		`protection.legacyUsableKeyCount`,
		`key.hashKeyId`,
		`async function loadServiceAccounts()`,
		`async function saveServiceAccount()`,
		`async function evaluateServiceAccountUsageAlerts()`,
		`function viewServiceAccountUsageAlerts()`,
		`result.notificationsClosed`,
		`.service-account-history > .status`,
		`async function rotateServiceAccountKey()`,
		`function revokeServiceAccountKey(button)`,
		`async function confirmRevokeServiceAccountKey()`,
		`async function copyServiceAccountKey()`,
		`fetch('/dashboard/saasAdmin/serviceAccounts?'`,
		`fetch('/dashboard/saasAdmin/serviceAccount'`,
		`requestHighRiskApproval('service_account.create'`,
		`提交创建审批`,
		`requestHighRiskApproval('service_account.update'`,
		`提交修改审批`,
		`requestHighRiskApproval('service_account.key.rotate'`,
		`提交轮换审批`,
		`result.plainTextKey`,
		`fetch('/dashboard/saasAdmin/serviceAccountKeyRotate'`,
		`requestHighRiskApproval('service_account.key.revoke'`,
		`fetch('/dashboard/saasAdmin/serviceAccountUsageAlertEvaluate'`,
		`'platform.integrations.manage'`,
		`'platform.notifications.read'`,
		`aria-label="审计完整性治理"`,
		`id="auditIntegrityTenantId"`,
		`id="auditIntegritySummary"`,
		`id="auditIntegrityChains"`,
		`id="auditIntegrityVerifications"`,
		`id="verifyAuditIntegrity"`,
		`function renderAuditIntegrity(data)`,
		`async function loadAuditIntegrity()`,
		`async function verifyAuditIntegrity()`,
		`fetch('/dashboard/saasAdmin/auditIntegrity?'`,
		`fetch('/dashboard/saasAdmin/auditIntegrityVerify'`,
		`id="auditAnchorState"`,
		`id="createAuditAnchor"`,
		`id="verifyAuditAnchor"`,
		`id="auditAnchors"`,
		`id="auditAnchorRemoteSummary"`,
		`id="auditAnchorRetentionSummary"`,
		`异地 Object Lock`,
		`remoteRetainUntil`,
		`function renderAuditAnchors(data)`,
		`async function loadAuditAnchors()`,
		`async function runAuditAnchorAction(action)`,
		`fetch('/dashboard/saasAdmin/auditAnchors?'`,
		`fetch('/dashboard/saasAdmin/auditAnchor'`,
		`'platform.audit.manage'`,
		`aria-label="高风险审批中心"`,
		`id="approvalStatus"`,
		`id="approvalAction"`,
		`id="approvalSummary"`,
		`id="approvalPolicies"`,
		`id="approvalDelegations"`,
		`id="approvalDecisions"`,
		`id="approvals"`,
		`id="approvalEvents"`,
		`function requestHighRiskApproval(actionType, payload, reason, options)`,
		`requestHighRiskApproval('tenant.provision'`,
		`approvalActionRequired('tenant.renewal', 0)`,
		`expectedTaskVersion`,
		`批量提交开户审批`,
		`批量提交续费审批`,
		`requestHighRiskApproval('release.candidate.gate'`,
		`requestHighRiskApproval('approval.policy.update'`,
		`requestHighRiskApproval('compliance.legal_hold.release'`,
		`const governancePolicy = item.governanceLocked === true`,
		`const minimumApprovals = Number(item.minimumApprovals`,
		`const amountThresholdLocked = item.amountThresholdLocked === true`,
		`提交解除审批`,
		`强制启用`,
		`function loadApprovalPolicies()`,
		`function saveApprovalPolicy(button)`,
		`function saveApprovalDelegation()`,
		`function createApprovalReminders()`,
		`function loadApprovals()`,
		`function decideApproval(button, decision)`,
		`撤销批准`,
		`function executeApproval(button)`,
		`fetch('/dashboard/saasAdmin/approvalRequest'`,
		`fetch('/dashboard/saasAdmin/approvalDecision'`,
		`fetch('/dashboard/saasAdmin/approvalPolicy'`,
		`fetch('/dashboard/saasAdmin/approvalDelegation'`,
		`fetch('/dashboard/saasAdmin/approvalReminders'`,
		`fetch('/dashboard/saasAdmin/approvalExecute'`,
		`aria-label="运营日报筛选"`,
		`id="dailyReportDate"`,
		`id="dailyReportDays"`,
		`id="applyDailyReport"`,
		`刷新日报`,
		`aria-label="运营日报明细"`,
		`id="dailyReportOwners"`,
		`id="dailyReportNotifications"`,
		`id="dailyReportActions"`,
		`id="dailyReportBilling"`,
		`日报负责人`,
		`日报通知`,
		`日报操作动作`,
		`日报账单流水`,
		`aria-label="客户成功队列"`,
		`id="customerSuccessCount"`,
		`aria-label="客户成功队列筛选"`,
		`id="customerSuccessPriority"`,
		`id="customerSuccessOwner"`,
		`id="customerSuccessTenantLimit"`,
		`id="applyCustomerSuccess"`,
		`aria-label="客户成功批量分派"`,
		`id="customerSuccessAssignOwner"`,
		`id="customerSuccessAssignNextAt"`,
		`id="customerSuccessAssignRemark"`,
		`id="assignCustomerSuccess"`,
		`aria-label="客户成功续费任务"`,
		`id="customerSuccessRenewMonths"`,
		`id="customerSuccessRenewAmount"`,
		`id="customerSuccessRenewRemark"`,
		`id="createCustomerSuccessRenewalTasks"`,
		`id="customerSuccess"`,
		`客户成功队列`,
		`筛队列`,
		`批量分派`,
		`生成续费任务`,
		`function customerSuccessParams(limit)`,
		`params.set('priority', customerSuccessPriorityInput.value.trim())`,
		`params.set('owner', customerSuccessOwnerInput.value.trim())`,
		`function renderCustomerSuccess(data)`,
		`function loadCustomerSuccess()`,
		`function assignCustomerSuccess()`,
		`function createCustomerSuccessRenewalTasks()`,
		`fetch('/dashboard/saasAdmin/customerSuccess?'`,
		`fetch('/dashboard/saasAdmin/customerSuccessAssign?'`,
		`fetch('/dashboard/saasAdmin/customerSuccessRenewalTasks?'`,
		`data-action="customer-success-tenant"`,
		`id="exportCustomerSuccess"`,
		`导出客户成功 CSV`,
		`id="exportRenewalForecast"`,
		`导出续费预测 CSV`,
		`id="exportRenewalForecastOwners"`,
		`导出续费预测负责人 CSV`,
		`aria-label="套餐变更影响"`,
		`id="editPackageDescription"`,
		`id="editPackageVersion"`,
		`提交套餐审批`,
		`approvalActionRequired('package.upsert', 0)`,
		`requestHighRiskApproval('package.upsert', payload`,
		`expectedVersion: Number(editPackageVersionInput.value || '0')`,
		`id="packageImpactSummary"`,
		`id="packageImpactChanges"`,
		`套餐变更影响`,
		`超新额度租户`,
		`租户套餐快照未自动改写`,
		`aria-label="订阅生命周期"`,
		`aria-label="订阅筛选"`,
		`aria-label="订阅状态迁移"`,
		`aria-label="订阅列表"`,
		`aria-label="订阅事件"`,
		`id="subscriptionStatus"`,
		`id="subscriptionAccess"`,
		`id="subscriptionKeyword"`,
		`id="subscriptionSummary"`,
		`id="subscriptions"`,
		`id="subscriptionTenantId"`,
		`id="subscriptionTransitionStatus"`,
		`id="subscriptionVersion"`,
		`id="subscriptionTrialEndsAt"`,
		`id="subscriptionPeriodEndsAt"`,
		`id="subscriptionGraceEndsAt"`,
		`id="subscriptionCancelAtPeriodEnd"`,
		`id="transitionSubscription"`,
		`提交订阅审批`,
		`approvalActionRequired('tenant.subscription.transition', 0)`,
		`'tenant.subscription.transition'`,
		`id="previewSubscriptionReconcile"`,
		`id="applySubscriptionReconcile"`,
		`id="exportSubscriptions"`,
		`function subscriptionParams(limit)`,
		`function renderSubscriptions(items)`,
		`function loadSubscriptions()`,
		`function transitionSubscription()`,
		`function reconcileSubscriptions(dryRun)`,
		`fetch('/dashboard/saasAdmin/subscriptions?'`,
		`fetch('/dashboard/saasAdmin/subscriptionEvents?'`,
		`fetch('/dashboard/saasAdmin/subscriptionTransition'`,
		`fetch('/dashboard/saasAdmin/subscriptionReconcile'`,
		`subscriptions: { params: subscriptionParams(1000)`,
		`aria-label="支付收款"`,
		`aria-label="支付订单筛选"`,
		`aria-label="支付概览"`,
		`aria-label="支付订单"`,
		`aria-label="创建支付订单"`,
		`aria-label="支付回调事件"`,
		`id="paymentOrderStatus"`,
		`id="paymentProvider"`,
		`id="paymentKeyword"`,
		`id="paymentSummary"`,
		`id="paymentOrders"`,
		`id="paymentTenantId"`,
		`id="paymentPackageCode"`,
		`id="paymentAmount"`,
		`id="paymentIdempotencyKey"`,
		`id="createPaymentOrder"`,
		`id="previewPaymentDunning"`,
		`id="applyPaymentDunning"`,
		`id="paymentWebhookEvents"`,
		`id="exportPaymentOrders"`,
		`aria-label="退款筛选"`,
		`aria-label="退款概览"`,
		`aria-label="支付退款"`,
		`aria-label="创建支付退款"`,
		`id="paymentRefundStatus"`,
		`id="paymentRefundOrderFilter"`,
		`id="paymentRefundSummary"`,
		`id="paymentRefunds"`,
		`id="paymentRefundOrderNo"`,
		`id="paymentRefundAmount"`,
		`id="paymentRefundEntitlement"`,
		`id="createPaymentRefund"`,
		`id="exportPaymentRefunds"`,
		`function paymentOrderParams(limit)`,
		`function paymentRefundParams(limit)`,
		`function renderPaymentOrders(items)`,
		`function renderPaymentRefunds(items)`,
		`function loadPaymentRefunds()`,
		`function createPaymentRefund()`,
		`function cancelPaymentRefund(button)`,
		`function renderPaymentWebhookEvents(items)`,
		`function loadPaymentOrders()`,
		`tenantId !== String(data.platformAdminTenantId || 0)`,
		`function createPaymentOrder()`,
		`approvalActionRequired('payment.order.create', 0)`,
		`'payment.order.create'`,
		`'提交收款审批'`,
		`function cancelPaymentOrder(button)`,
		`function runPaymentDunning(dryRun)`,
		`fetch('/dashboard/saasAdmin/paymentOrders?'`,
		`fetch('/dashboard/saasAdmin/paymentWebhookEvents?'`,
		`fetch('/dashboard/saasAdmin/paymentOrder'`,
		`fetch('/dashboard/saasAdmin/paymentOrderCancel'`,
		`fetch('/dashboard/saasAdmin/paymentDunning'`,
		`paymentOrders: { params: paymentOrderParams(1000)`,
		`fetch('/dashboard/saasAdmin/paymentRefunds?'`,
		`fetch('/dashboard/saasAdmin/paymentRefund'`,
		`fetch('/dashboard/saasAdmin/paymentRefundCancel'`,
		`paymentRefunds: { params: paymentRefundParams(1000)`,
		`aria-label="发票台账筛选"`,
		`aria-label="发票台账概览"`,
		`aria-label="发票台账"`,
		`aria-label="租户开票资料"`,
		`aria-label="创建发票单据"`,
		`aria-label="处理发票单据"`,
		`id="invoiceKindFilter"`,
		`id="invoiceStatusFilter"`,
		`id="invoiceTenantFilter"`,
		`id="invoiceDocumentSummary"`,
		`id="invoiceDocuments"`,
		`id="invoiceProfileTenantId"`,
		`id="saveInvoiceProfile"`,
		`id="invoiceCreateKind"`,
		`id="invoiceOriginalDocumentNo"`,
		`id="createInvoiceDocument"`,
		`id="invoiceTransitionDocumentNo"`,
		`id="transitionInvoiceDocument"`,
		`id="exportInvoiceDocuments"`,
		`function invoiceDocumentParams(limit)`,
		`function renderInvoiceDocuments(items)`,
		`function loadInvoiceDocuments()`,
		`function loadInvoiceProfile(tenantId)`,
		`function saveInvoiceProfile()`,
		`function createInvoiceDocument()`,
		`function transitionInvoiceDocument(statusOverride, button)`,
		`function renderInvoiceIssueApprovalState()`,
		`approvalActionRequired('billing.invoice.issue', 0)`,
		`'billing.invoice.issue'`,
		`'开具审批已提交，等待两人复核'`,
		`fetch('/dashboard/saasAdmin/invoiceDocuments?'`,
		`fetch('/dashboard/saasAdmin/invoiceProfile?tenantId='`,
		`fetch('/dashboard/saasAdmin/invoiceProfile'`,
		`'/dashboard/saasAdmin/creditNote'`,
		`fetch('/dashboard/saasAdmin/invoiceTransition'`,
		`invoiceDocuments: { params: invoiceDocumentParams(1000)`,
		`aria-label="渠道结算批次筛选"`,
		`aria-label="结算自动同步筛选"`,
		`aria-label="结算同步概览"`,
		`aria-label="结算同步渠道状态"`,
		`aria-label="结算同步运行记录"`,
		`id="paymentSettlementSyncProvider"`,
		`id="previewPaymentSettlementSync"`,
		`id="runPaymentSettlementSync"`,
		`id="paymentSettlementSyncStates"`,
		`id="paymentSettlementSyncRuns"`,
		`function paymentSettlementSyncParams(limit)`,
		`function loadPaymentSettlementSyncRuns()`,
		`function triggerPaymentSettlementSync(dryRun)`,
		`fetch('/dashboard/saasAdmin/paymentSettlementSyncRuns?'`,
		`fetch('/dashboard/saasAdmin/paymentSettlementSync'`,
		`aria-label="渠道结算概览"`,
		`aria-label="渠道结算批次"`,
		`aria-label="导入渠道结算单"`,
		`aria-label="渠道结算明细筛选"`,
		`aria-label="渠道结算明细"`,
		`id="paymentSettlementBatches"`,
		`id="paymentSettlementEntries"`,
		`id="paymentSettlementFile"`,
		`id="paymentSettlementCSV"`,
		`id="importPaymentSettlement"`,
		`id="exportPaymentSettlementBatches"`,
		`id="exportPaymentSettlementEntries"`,
		`function paymentSettlementBatchParams(limit)`,
		`function paymentSettlementEntryParams(limit)`,
		`function renderPaymentSettlementBatches(items)`,
		`function renderPaymentSettlementEntries(items, summary)`,
		`function loadPaymentSettlementBatches()`,
		`function loadPaymentSettlementEntries()`,
		`function importPaymentSettlement()`,
		`function reconcilePaymentSettlement(dryRun, button)`,
		`function resolvePaymentSettlementEntry(button)`,
		`function transitionPaymentSettlement(action, button)`,
		`fetch('/dashboard/saasAdmin/paymentSettlementBatches?'`,
		`fetch('/dashboard/saasAdmin/paymentSettlementEntries?'`,
		`fetch('/dashboard/saasAdmin/paymentSettlementImport'`,
		`fetch('/dashboard/saasAdmin/paymentSettlementReconcile'`,
		`fetch('/dashboard/saasAdmin/paymentSettlementResolve'`,
		`fetch('/dashboard/saasAdmin/paymentSettlementTransition'`,
		`paymentSettlementBatches: { params: paymentSettlementBatchParams(1000)`,
		`paymentSettlementEntries: { params: paymentSettlementEntryParams(1000)`,
		`aria-label="运营任务中心筛选"`,
		`aria-label="运营任务中心"`,
		`id="adminTaskType"`,
		`id="adminTaskStatus"`,
		`id="adminTaskTenantId"`,
		`id="adminTaskPackageCode"`,
		`id="adminTaskSlaWarningHours"`,
		`id="adminTaskSlaOverdueHours"`,
		`id="loadAdminTasks"`,
		`id="loadAdminTaskOwners"`,
		`id="loadAdminTaskSla"`,
		`id="createTaskSlaNotifications"`,
		`id="bulkCancelAdminTasks"`,
		`id="bulkResetAdminTasks"`,
		`id="bulkApplyRenewalTasks"`,
		`id="adminTasks"`,
		`aria-label="运营任务负责人"`,
		`id="adminTaskOwnerSummary"`,
		`id="adminTaskOwners"`,
		`aria-label="运营任务SLA"`,
		`id="adminTaskSlaSummary"`,
		`id="adminTaskSla"`,
		`id="exportTasks"`,
		`id="exportTaskSla"`,
		`id="createCustomerSuccessRenewalNotifications"`,
		`aria-label="客户成功负责人工作台"`,
		`id="customerSuccessOwners"`,
		`id="exportCustomerSuccessOwners"`,
		`<option value="canceled">已取消</option>`,
		`运营任务中心`,
		`任务负责人`,
		`任务SLA`,
		`生成SLA提醒`,
		`function bulkApplyRenewalTasks()`,
		`fetch('/dashboard/saasAdmin/tenantRenewalTaskBulkApply'`,
		`function createCustomerSuccessRenewalNotifications()`,
		`fetch('/dashboard/saasAdmin/customerSuccessRenewalNotifications?'`,
		`function loadCustomerSuccessOwners()`,
		`fetch('/dashboard/saasAdmin/customerSuccessOwners?'`,
		`aria-label="套餐快照同步"`,
		`id="packageAssignmentVersion"`,
		`id="packageAssignmentRemark"`,
		`提交分配审批`,
		`tenant.package.update`,
		`data-action="adjust-tenant-package"`,
		`function resolveTenantPackageSnapshot(tenantId)`,
		`aria-label="套餐快照同步结果"`,
		`id="syncPackageCode"`,
		`id="syncTenantId"`,
		`id="syncAllowOverLimit"`,
		`id="previewPackageSync"`,
		`id="applyPackageSync"`,
		`aria-label="套餐同步任务"`,
		`id="syncTaskId"`,
		`id="createPackageSyncTask"`,
		`id="applyPackageSyncTask"`,
		`id="loadPackageSyncTasks"`,
		`id="packageSyncSummary"`,
		`id="packageSyncTenants"`,
		`id="packageSyncTasks"`,
		`aria-label="平台开户任务"`,
		`id="provisionTaskId"`,
		`id="createProvisionTask"`,
		`id="applyProvisionTask"`,
		`id="loadProvisionTasks"`,
		`id="provisionTasks"`,
		`aria-label="续费任务"`,
		`id="renewalTaskId"`,
		`id="createRenewalTask"`,
		`id="applyRenewalTask"`,
		`id="loadRenewalTasks"`,
		`id="renewalTasks"`,
		`套餐快照同步`,
		`套餐同步任务`,
		`续费任务`,
		`预览同步`,
		`应用同步`,
		`创建任务`,
		`应用任务`,
		`params.set('date', dailyReportDateInput.value.trim())`,
		`params.set('days', dailyReportDaysInput.value.trim())`,
		`日报待办认领`,
		`id="dailyReportQueueAssignmentCount"`,
		`id="dailyReportQueueAssignments"`,
		`const dailyReportQueueAssignmentsEl = document.getElementById('dailyReportQueueAssignments')`,
		`data.operationQueueAssignments || {}`,
		`renderDailyReportDetails(data || {})`,
		`aria-label="经营指标"`,
		`id="businessMetrics"`,
		`id="businessPackages"`,
		`function loadBusinessMetrics()`,
		`fetch('/dashboard/saasAdmin/businessMetrics?'`,
		`aria-label="经营趋势"`,
		`id="businessTrends"`,
		`id="businessTrendMonths"`,
		`id="businessRenewalFunnel"`,
		`function businessTrendsParams()`,
		`function renderBusinessTrends(data)`,
		`function loadBusinessTrends()`,
		`fetch('/dashboard/saasAdmin/businessTrends?'`,
		`aria-label="运营待办队列"`,
		`id="operationQueueCount"`,
		`id="operationQueueSource"`,
		`<option value="notification_health">通知健康</option>`,
		`id="operationQueuePriority"`,
		`id="operationQueueOwner"`,
		`id="operationQueueAssignmentDueState"`,
		`id="operationQueueAssignmentCurrentOnly"`,
		`认领到期`,
		`认领视图`,
		`id="operationQueueKeyword"`,
		`id="applyOperationQueue"`,
		`id="operationQueue"`,
		`id="exportOperationQueue"`,
		`导出待办 CSV`,
		`aria-label="运营待办批量分派"`,
		`id="operationQueueAssignOwner"`,
		`id="operationQueueAssignStatus"`,
		`id="operationQueueAssignNextAt"`,
		`id="operationQueueAssignRemark"`,
		`id="assignOperationQueue"`,
		`分派当前待办`,
		`id="createOperationQueueAssignmentNotifications"`,
		`生成认领到期提醒`,
		`aria-label="运营待办负责人工作台"`,
		`id="operationQueueOwnerCount"`,
		`id="operationQueueOwners"`,
		`id="exportOperationQueueOwners"`,
		`导出待办负责人 CSV`,
		`id="exportOperationQueueAssignments"`,
		`导出待办认领 CSV`,
		`aria-label="运营待办认领记录"`,
		`id="operationQueueAssignmentCount"`,
		`id="operationQueueAssignments"`,
		`function operationQueueParams(limit)`,
		`function operationQueueAssignmentParams(limit)`,
		`function renderOperationQueue(data)`,
		`function renderOperationQueueOwners(data)`,
		`function renderOperationQueueAssignments(data)`,
		`function loadOperationQueue()`,
		`function loadOperationQueueOwners()`,
		`function loadOperationQueueAssignments()`,
		`function assignOperationQueue()`,
		`function assignNotificationHealthQueue()`,
		`function recoverNotificationHealthQueue()`,
		`function createOperationQueueAssignmentNotifications()`,
		`function closeOperationQueueAssignment(operationId, closeStatus)`,
		`fetch('/dashboard/saasAdmin/operationQueue?'`,
		`fetch('/dashboard/saasAdmin/operationQueueOwners?'`,
		`fetch('/dashboard/saasAdmin/operationQueueAssignments?'`,
		`fetch('/dashboard/saasAdmin/operationQueueAssignmentNotifications?'`,
		`fetch('/dashboard/saasAdmin/operationQueueAssignmentClose'`,
		`fetch('/dashboard/saasAdmin/operationQueueAssign?'`,
		`operationQueue: { params: operationQueueParams(1000), fallback: 'mochat-saas-operationQueue.csv' }`,
		`operationQueueOwners: { params: operationQueueParams(1000), fallback: 'mochat-saas-operationQueueOwners.csv' }`,
		`operationQueueAssignments: { params: operationQueueAssignmentParams(1000), fallback: 'mochat-saas-operationQueueAssignments.csv' }`,
		`document.getElementById('exportOperationQueue').addEventListener('click', () => downloadCSV('operationQueue'))`,
		`document.getElementById('exportOperationQueueOwners').addEventListener('click', () => downloadCSV('operationQueueOwners'))`,
		`document.getElementById('exportOperationQueueAssignments').addEventListener('click', () => downloadCSV('operationQueueAssignments'))`,
		`document.getElementById('createOperationQueueAssignmentNotifications').addEventListener('click', createOperationQueueAssignmentNotifications)`,
		`data-operation-queue-assignment-close="resolved"`,
		`data-operation-queue-assignment-close="ignored"`,
		`document.getElementById('assignOperationQueue').addEventListener('click', assignOperationQueue)`,
		`aria-label="续费预测"`,
		`id="renewalForecast"`,
		`id="renewalForecastBuckets"`,
		`id="renewalForecastOwners"`,
		`id="renewalForecastTenants"`,
		`aria-label="续费预测筛选"`,
		`id="renewalForecastDays"`,
		`id="renewalForecastBucket"`,
		`id="renewalForecastPriced"`,
		`id="renewalForecastPackageCode"`,
		`id="renewalForecastOwner"`,
		`id="renewalForecastTaskStatus"`,
		`id="applyRenewalForecastFilters"`,
		`aria-label="续费预测分派"`,
		`id="renewalForecastAssignOwner"`,
		`id="renewalForecastAssignNextAt"`,
		`id="renewalForecastAssignStatus"`,
		`id="renewalForecastAssignRemark"`,
		`id="assignRenewalForecast"`,
		`aria-label="续费预测任务"`,
		`id="renewalForecastTaskMonths"`,
		`id="renewalForecastTaskOrderPrefix"`,
		`id="renewalForecastTaskForce"`,
		`id="createRenewalForecastTasks"`,
		`aria-label="续费预测提醒"`,
		`id="renewalForecastReminderDays"`,
		`id="renewalForecastMaxAttempts"`,
		`id="renewalForecastNotifyRemark"`,
		`id="renewalForecastForceNotify"`,
		`id="createRenewalForecastNotifications"`,
		`aria-label="续费预测负责人工作台"`,
		`function renewalForecastParams()`,
		`params.set('bucket', renewalForecastBucketInput.value)`,
		`params.set('priced', renewalForecastPricedInput.value)`,
		`params.set('packageCode', renewalForecastPackageCodeInput.value.trim())`,
		`params.set('owner', renewalForecastOwnerInput.value.trim())`,
		`params.set('taskStatus', renewalForecastTaskStatusInput.value)`,
		`function renderRenewalForecast(data)`,
		`function loadRenewalForecast()`,
		`function assignRenewalForecast()`,
		`function createRenewalForecastTasks()`,
		`function createRenewalForecastNotifications()`,
		`fetch('/dashboard/saasAdmin/renewalForecast?'`,
		`fetch('/dashboard/saasAdmin/renewalForecastAssign?'`,
		`fetch('/dashboard/saasAdmin/renewalForecastTasks?'`,
		`fetch('/dashboard/saasAdmin/renewalForecastNotifications?'`,
		`renderPackageImpact(saved.impact)`,
		`function renderAdminTasks(tasks, summary, returnedCount)`,
		`function renderAdminTaskOwners(owners, summary, ownerCount, returnedCount, scannedTaskCount, partial)`,
		`function loadAdminTaskOwners()`,
		`fetch('/dashboard/saasAdmin/taskOwners?'`,
		`function adminTaskSlaParams(limit)`,
		`function renderAdminTaskSla(items, summary, taskSummary, returnedCount, ownerCount, scannedTaskCount, partial)`,
		`function loadAdminTaskSla()`,
		`fetch('/dashboard/saasAdmin/taskSla?'`,
		`function applyAdminTask(taskId, taskType, taskVersion)`,
		`function cancelAdminTask(taskId)`,
		`function resetAdminTask(taskId)`,
		`function bulkCancelAdminTasks()`,
		`function bulkResetAdminTasks()`,
		`function traceAdminTaskOperations(taskId)`,
		`function operationJSONText(value)`,
		`function operationChangeDetails(item)`,
		`function renderOperations(items, summary)`,
		`function renderBillingEvents(items, summary)`,
		`aria-label="账单对账"`,
		`id="billingMismatchOnly"`,
		`id="billingReconciliationCount"`,
		`id="billingReconciliation"`,
		`账单对账`,
		`只看对账异常`,
		`导出对账 CSV`,
		`导出账单跟进 CSV`,
		`导出风险负责人 CSV`,
		`导出账单负责人 CSV`,
		`function billingReconciliationParams(limit)`,
		`function renderBillingReconciliation(items, summary)`,
		`function billingReconciliationReasonText(reason)`,
		`function followUpBillingReconciliation(billingEventId)`,
		`function renderAlerts(items, summary, returnedCount)`,
		`summary.alertCount`,
		`renderAlerts(data.alerts || [], data.summary || {}, data.returnedCount)`,
		`function renderNotifications(items, summary, returnedCount)`,
		`summary.notificationCount`,
		`renderNotifications(data.notifications || [], data.summary || {}, data.returnedCount)`,
		`aria-label="通知送达健康度筛选"`,
		`aria-label="通知送达健康度"`,
		`aria-label="通知失败原因"`,
		`id="notificationHealthWindowHours"`,
		`id="notificationHealthState"`,
		`id="notificationHealthStaleMinutes"`,
		`id="notificationHealthKeyword"`,
		`id="notificationHealthAssignOwner"`,
		`id="notificationHealthAssignNextAt"`,
		`id="notificationHealthTenants"`,
		`id="notificationFailureReasons"`,
		`id="loadNotificationHealth"`,
		`id="exportNotificationHealth"`,
		`id="assignNotificationHealthQueue"`,
		`id="recoverNotificationHealthQueue"`,
		`function notificationHealthParams(limit)`,
		`function renderNotificationHealth(data)`,
		`async function loadNotificationHealth()`,
		`fetch('/dashboard/saasAdmin/notificationHealth?'`,
		`fetch('/dashboard/saasAdmin/notificationHealthRecovery?'`,
		`downloadCSV('notificationHealth')`,
		`aria-label="通知 SLO 筛选"`,
		`aria-label="通知 SLO 日趋势"`,
		`aria-label="通知 SLO 租户排行"`,
		`id="notificationSloWindowDays"`,
		`id="notificationSloSuccessTarget"`,
		`id="notificationSloLatencySeconds"`,
		`id="notificationSloLatencyTarget"`,
		`id="notificationSloKeyword"`,
		`id="notificationSloDays"`,
		`id="notificationSloTenants"`,
		`id="notificationSloCount"`,
		`id="notificationSloTenantCount"`,
		`id="loadNotificationSlo"`,
		`id="exportNotificationSlo"`,
		`function notificationSloParams(limit)`,
		`function renderNotificationSlo(data)`,
		`async function loadNotificationSlo()`,
		`fetch('/dashboard/saasAdmin/notificationSlo?'`,
		`downloadCSV('notificationSlo')`,
		`aria-label="租户通知策略筛选"`,
		`aria-label="租户通知策略"`,
		`aria-label="通知策略编辑"`,
		`id="notificationPolicyState"`,
		`id="notificationPolicyKeyword"`,
		`id="notificationPolicyTenantId"`,
		`id="notificationPolicyEnabled"`,
		`id="notificationPolicyWebhookUrl"`,
		`id="notificationPolicyWebhookSecret"`,
		`id="notificationPolicyClearSecret"`,
		`id="notificationPolicyTitleTemplate"`,
		`id="notificationPolicyBodyTemplate"`,
		`id="notificationPolicyMinimumSeverity"`,
		`id="notificationPolicyAlertQuota"`,
		`id="notificationPolicyAlertRenewal"`,
		`id="notificationPolicyAlertPaymentFailed"`,
		`payment_failed_reminder`,
		`id="notificationPolicyQuietEnabled"`,
		`id="notificationPolicyQuietStart"`,
		`id="notificationPolicyQuietEnd"`,
		`id="notificationPolicyTimezone"`,
		`id="notificationPolicyHourlyLimit"`,
		`id="notificationPolicies"`,
		`id="saveNotificationPolicy"`,
		`id="testNotificationPolicy"`,
		`生成测试通知`,
		`function notificationPolicyParams(limit)`,
		`function renderNotificationPolicies(items, summary, returnedCount)`,
		`function fillNotificationPolicy(policy)`,
		`function selectedNotificationPolicyAlertTypes()`,
		`async function loadNotificationPolicies()`,
		`async function loadNotificationPolicy(tenantId)`,
		`async function saveNotificationPolicy()`,
		`async function testNotificationPolicy()`,
		`fetch('/dashboard/saasAdmin/notificationPolicies?'`,
		`fetch('/dashboard/saasAdmin/notificationPolicy?'`,
		`fetch('/dashboard/saasAdmin/notificationPolicy',`,
		`fetch('/dashboard/saasAdmin/notificationPolicyTest',`,
		`data-action="edit-notification-policy"`,
		`id="exportAlerts"`,
		`id="exportNotifications"`,
		`aria-label="生命周期审计"`,
		`aria-label="生命周期筛选"`,
		`id="tenantLifecycle"`,
		`id="loadTenantLifecycle"`,
		`id="tenantLifecycleSource"`,
		`id="tenantLifecycleEventType"`,
		`id="tenantLifecycleStatus"`,
		`id="tenantLifecycleKeyword"`,
		`id="exportTenantLifecycle"`,
		`导出审计 CSV`,
		`function renderTenantLifecycle(data)`,
		`function tenantLifecycleParams(limit)`,
		`summary.rawTimelineCount`,
		`summary.filterActive`,
		`params.set('source', source)`,
		`params.set('eventType', eventType)`,
		`params.set('status', status)`,
		`params.set('keyword', keyword)`,
		`tenantLifecycle: { params: tenantLifecycleParams(1000), fallback: 'mochat-saas-tenantLifecycle.csv' }`,
		`document.getElementById('exportTenantLifecycle').addEventListener('click', () => downloadCSV('tenantLifecycle'))`,
		`fetch('/dashboard/saasAdmin/tenantLifecycle?'`,
		`alerts: { params: alertParams(1000), fallback: 'mochat-saas-alerts.csv' }`,
		`notifications: { params: notificationParams(1000), fallback: 'mochat-saas-notifications.csv' }`,
		`document.getElementById('exportAlerts').addEventListener('click', () => downloadCSV('alerts'))`,
		`document.getElementById('exportNotifications').addEventListener('click', () => downloadCSV('notifications'))`,
		`fetch('/dashboard/saasAdmin/billingReconciliation?'`,
		`fetch('/dashboard/saasAdmin/billingReconciliationFollowUp'`,
		`data-action="follow-up-billing-reconciliation"`,
		`账单跟进`,
		`aria-label="账单跟进任务筛选"`,
		`aria-label="账单跟进任务"`,
		`aria-label="账单跟进负责人工作台"`,
		`id="billingFollowStatus"`,
		`id="billingFollowDueState"`,
		`id="billingFollowOwner"`,
		`id="billingFollowKeyword"`,
		`id="applyBillingFollowFilters"`,
		`id="bulkCloseBillingFollowUps"`,
		`批量关闭账单跟进`,
		`id="billingFollowUps"`,
		`id="billingFollowUpOwners"`,
		`function billingFollowParams(limit)`,
		`function renderBillingReconciliationFollowUps(items, summary)`,
		`function renderBillingReconciliationFollowUpOwners(items, summary)`,
		`function loadBillingReconciliationFollowUps()`,
		`function loadBillingReconciliationFollowUpOwners()`,
		`function bulkCloseBillingReconciliationFollowUps()`,
		`fetch('/dashboard/saasAdmin/billingReconciliationFollowUps?'`,
		`fetch('/dashboard/saasAdmin/billingReconciliationFollowUpOwners?'`,
		`fetch('/dashboard/saasAdmin/billingReconciliationFollowUpBulkClose'`,
		`document.getElementById('applyBillingFollowFilters').addEventListener`,
		`document.getElementById('bulkCloseBillingFollowUps').addEventListener`,
		`riskFollowUpOwners: { params: riskTaskParams(1000), fallback: 'mochat-saas-riskFollowUpOwners.csv' }`,
		`customerSuccess: { params: customerSuccessParams(1000), fallback: 'mochat-saas-customerSuccess.csv' }`,
		`renewalForecast: { params: renewalForecastParams(), fallback: 'mochat-saas-renewalForecast.csv' }`,
		`renewalForecastOwners: { params: renewalForecastParams(), fallback: 'mochat-saas-renewalForecastOwners.csv' }`,
		`document.getElementById('exportCustomerSuccess').addEventListener('click', () => downloadCSV('customerSuccess'))`,
		`document.getElementById('exportRenewalForecast').addEventListener('click', () => downloadCSV('renewalForecast'))`,
		`document.getElementById('exportRenewalForecastOwners').addEventListener('click', () => downloadCSV('renewalForecastOwners'))`,
		`document.getElementById('applyRenewalForecastFilters').addEventListener('click'`,
		`document.getElementById('assignRenewalForecast').addEventListener('click', assignRenewalForecast)`,
		`document.getElementById('assignCustomerSuccess').addEventListener('click', assignCustomerSuccess)`,
		`document.getElementById('exportRiskFollowUpOwners').addEventListener('click', () => downloadCSV('riskFollowUpOwners'))`,
		`billingReconciliation: { params: billingReconciliationParams(1000), fallback: 'mochat-saas-billingReconciliation.csv' }`,
		`billingReconciliationFollowUps: { params: billingFollowParams(1000), fallback: 'mochat-saas-billingReconciliationFollowUps.csv' }`,
		`billingReconciliationFollowUpOwners: { params: billingFollowParams(1000), fallback: 'mochat-saas-billingReconciliationFollowUpOwners.csv' }`,
		`document.getElementById('exportBillingReconciliation').addEventListener('click', () => downloadCSV('billingReconciliation'))`,
		`document.getElementById('exportBillingFollowUps').addEventListener('click', () => downloadCSV('billingReconciliationFollowUps'))`,
		`document.getElementById('exportBillingFollowUpOwners').addEventListener('click', () => downloadCSV('billingReconciliationFollowUpOwners'))`,
		`billingMismatchOnlyInput.addEventListener('change', loadBillingReconciliation)`,
		`data.summary || {}`,
		`summary.operationCount`,
		`租户 ' + tenantCount + ' 个`,
		`renderOperations(data.operations || [], data.summary || {})`,
		`毛收入 ' + gross`,
		`/ 退款 ' + refunded`,
		`/ 净收入 ' + amount + ' CNY`,
		`显示 ' + items.length + ' 条`,
		`data-action="apply-admin-task"`,
		`data-action="cancel-admin-task"`,
		`data-action="reset-admin-task"`,
		`data-action="trace-admin-task"`,
		`summary.taskCount`,
		`summary.pendingCount`,
		`summary.actionableCount`,
		`data.returnedCount`,
		`fetch('/dashboard/saasAdmin/taskReset'`,
		`id="bulkResetAdminTasks"`,
		`<th>变更</th>`,
		`查看变更`,
		`无变更 JSON`,
		`operationTargetTypeInput.value = 'admin_task'`,
		`adminTaskTypeInput.addEventListener('change', loadAdminTasks)`,
		`document.getElementById('loadAdminTaskOwners').addEventListener('click', loadAdminTaskOwners)`,
		`document.getElementById('loadAdminTaskSla').addEventListener('click', loadAdminTaskSla)`,
		`document.getElementById('createTaskSlaNotifications').addEventListener('click', createTaskSlaNotifications)`,
		`document.getElementById('bulkCancelAdminTasks').addEventListener('click', bulkCancelAdminTasks)`,
		`document.getElementById('bulkResetAdminTasks').addEventListener('click', bulkResetAdminTasks)`,
		`tasks: { params: adminTaskParams(1000), fallback: 'mochat-saas-tasks.csv' }`,
		`taskSla: { params: adminTaskSlaParams(1000), fallback: 'mochat-saas-taskSla.csv' }`,
		`document.getElementById('exportTasks').addEventListener('click', () => downloadCSV('tasks'))`,
		`document.getElementById('exportTaskSla').addEventListener('click', () => downloadCSV('taskSla'))`,
		`fetch('/dashboard/saasAdmin/taskCancel'`,
		`fetch('/dashboard/saasAdmin/taskSlaNotifications?'`,
		`fetch('/dashboard/saasAdmin/taskBulkCancel'`,
		`fetch('/dashboard/saasAdmin/taskBulkReset'`,
		`fetch('/dashboard/saasAdmin/packageSync'`,
		`fetch('/dashboard/saasAdmin/packageSyncTask'`,
		`fetch('/dashboard/saasAdmin/packageSyncTaskApply'`,
		`fetch('/dashboard/saasAdmin/tenantProvisionTask'`,
		`fetch('/dashboard/saasAdmin/tenantProvisionTaskApply'`,
		`fetch('/dashboard/saasAdmin/tenantRenewalTask'`,
		`fetch('/dashboard/saasAdmin/tenantRenewalTaskApply'`,
		`fetch('/dashboard/saasAdmin/tasks?'`,
		`renderPackageSyncResult(data)`,
		`renderPackageSyncTasks((body.data || {}).tasks || [])`,
		`renderProvisionTasks((body.data || {}).tasks || [])`,
		`renderRenewalTasks((body.data || {}).tasks || [])`,
		`downloadCSV('dailyReport')`,
		`downloadCSV('tasks')`,
		`downloadCSV('taskSla')`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("missing %q in page", want)
		}
	}
}

func TestSaaSAdminPageIncludesPermissionAwareWorkspaceNavigation(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/dashboard/saasAdmin/page", nil)
	rec := httptest.NewRecorder()

	ServeSaaSAdminLegacyPage(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d body=%s", rec.Code, rec.Body.String())
	}
	body := rec.Body.String()
	for _, want := range []string{
		`id="workspaceNav"`,
		`aria-label="工作区切换"`,
		`data-workspace="overview"`,
		`data-workspace="tenant"`,
		`data-workspace="operations"`,
		`data-workspace="finance"`,
		`data-workspace="notifications"`,
		`data-workspace="governance"`,
		`data-workspace="security"`,
		`data-workspace="delivery"`,
		`id="workspaceSectionJump"`,
		`aria-label="租户风险与额度"`,
		`function workspaceForSection(section)`,
		`const workspacePermissionMap = {`,
		`requiredPermissions.some(hasPlatformPermission)`,
		`function accessibleWorkspaceSections(workspace)`,
		`function revealCurrentWorkspaceTab(smooth)`,
		`function applyWorkspaceView(workspace, scrollToTop, persistSelection = true)`,
		`function refreshWorkspaceNavigation()`,
		`function initWorkspaceNavigation()`,
		`applyWorkspaceView(preferredWorkspace, false, false)`,
		`localStorage.setItem(workspaceStorageKey, currentWorkspace)`,
		`refreshWorkspaceNavigation();`,
		`initWorkspaceNavigation();`,
		`.workspace-section-hidden { display: none !important; }`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("page missing workspace navigation marker %q", want)
		}
	}
}

func TestSaaSAdminPageIncludesReleaseEvidenceActionTracking(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/dashboard/saasAdmin/page", nil)
	rec := httptest.NewRecorder()

	ServeSaaSAdminLegacyPage(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d body=%s", rec.Code, rec.Body.String())
	}
	body := rec.Body.String()
	for _, want := range []string{
		`id="releaseEvidenceActions"`,
		`id="releaseEvidenceActionOwner"`,
		`id="releaseEvidenceActionDueAt"`,
		`id="saveReleaseEvidenceAction"`,
		`function releaseEvidenceActionState(value)`,
		`function openReleaseEvidenceActionEditor(key)`,
		`fetch('/dashboard/saasAdmin/releaseEvidenceAction'`,
		`data-release-action-edit=`,
		`生产补证行动清单`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("page missing release evidence action marker %q", want)
		}
	}
}
