import { useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import type { BusinessWorkbenchApi } from '../business-workbench/business-workbench-page';
import { useDashboardAccess } from '../../app/access-context';
import { pageStateForError, PageState } from '../../components/page-state/page-state';

type Row = Record<string, unknown>;
function rows(value: unknown): Row[] { if (Array.isArray(value)) return value.filter((v): v is Row => !!v && typeof v === 'object'); if (!value || typeof value !== 'object') return []; const v = value as Row; const b = v.data && typeof v.data === 'object' ? v.data as Row : v; const list = [b.list, b.items, b.rows].find(Array.isArray); return Array.isArray(list) ? list.filter((x): x is Row => !!x && typeof x === 'object') : []; }
function text(value: unknown): string { return value == null || value === '' ? '--' : typeof value === 'object' ? JSON.stringify(value) : String(value); }

export function CustomerTransferPage({ api, mode }: { api: BusinessWorkbenchApi; mode: 'inheritance' | 'resign' }) {
  const access = useDashboardAccess();
  const [draft, setDraft] = useState(''); const [name, setName] = useState(''); const [selected, setSelected] = useState<Row | null>(null);
  const endpoint = mode === 'inheritance' ? '/contactTransfer/unassignedList' : '/contactTransfer/info';
  const title = mode === 'inheritance' ? '客户继承' : '离职员工';
  const query = useQuery({ queryKey: ['phase33-transfer', access.corp.id, mode, name], queryFn: () => api.read(endpoint, { ...(name ? { contactName: name } : {}), page: 1, perPage: 20 }), enabled: access.corp.authorized });
  const data = useMemo(() => rows(query.data), [query.data]); const columns = useMemo(() => Object.keys(data[0] ?? {}).slice(0, 7), [data]);
  return <section className="phase33-operations-page"><header className="phase33-operations-header dashboard-page-header dashboard-data-card"><div><p className="phase33-operations-eyebrow">客户运营</p><h1>{title}</h1><p>{mode === 'inheritance' ? '查看待分配客户并进入后续转接操作。' : '查看离职员工相关客户转接记录。'}</p></div><button type="button" disabled={query.isFetching} onClick={() => void query.refetch()}>刷新</button></header><div className="dashboard-filter-bar phase33-operations-filters"><label>客户名称<input aria-label="客户名称" value={draft} onChange={(e) => setDraft(e.target.value)} /></label><div className="dashboard-table-actions"><button type="button" onClick={() => { setSelected(null); setName(draft.trim()); }}>查询</button><button type="button" onClick={() => { setDraft(''); setName(''); setSelected(null); }}>重置</button></div></div>{!access.corp.authorized ? <div className="dashboard-data-card"><PageState state="forbidden" title="无权访问当前企业数据" /></div> : <div className="dashboard-data-card phase33-operations-results"><div className="dashboard-card-heading"><div><h2>记录列表</h2><p>查看客户转接相关记录。</p></div></div>{query.isPending ? <PageState state="loading" /> : query.isError ? <PageState state={pageStateForError(query.error)} onRetry={() => void query.refetch()} /> : data.length === 0 ? <PageState state="empty" /> : <div className="dashboard-table-scroll"><table><thead><tr>{columns.map((c) => <th key={c}>{c}</th>)}<th>操作</th></tr></thead><tbody>{data.map((row, i) => <tr key={String(row.id ?? row.contactId ?? i)}>{columns.map((c) => <td key={c}>{text(row[c])}</td>)}<td><button type="button" onClick={() => setSelected(row)}>详情</button></td></tr>)}</tbody></table></div>}</div>}{selected && <aside className="phase33-operations-detail dashboard-data-card"><div className="dashboard-card-heading"><div><h2>记录详情</h2><p>查看客户转接记录的详细信息。</p></div><button type="button" onClick={() => setSelected(null)}>关闭</button></div><dl>{Object.entries(selected).map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{text(v)}</dd></div>)}</dl><button type="button" onClick={() => window.location.assign('/contactTransfer/resignIndex')}>进入转接操作</button></aside>}</section>;
}
