import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useDashboardAccess } from '../../app/access-context';
import { PageState, pageStateForError } from '../../components/page-state/page-state';
import type { BusinessWorkbenchApi } from '../business-workbench/business-workbench-page';

type Row=Record<string,unknown>;
const text=(v:unknown)=>v==null?'':String(v);
const show=(v:unknown)=>Array.isArray(v)?v.join('、'):text(v)||'-';
function unwrap(v:unknown):Row[]{if(!v||typeof v!=='object')return[];const o=v as Row;const d=o.data&&typeof o.data==='object'?o.data as Row:o;return Array.isArray(d.items)?d.items as Row[]:[]}

export function KeywordLibraryPage({api}:{api:BusinessWorkbenchApi}){
 const access=useDashboardAccess(),client=useQueryClient();const [nameFilter,setNameFilter]=useState('');const [selected,setSelected]=useState<Row|null>(null);const [editing,setEditing]=useState<Row|null>(null);const [entryEditing,setEntryEditing]=useState<Row|null>(null);const [name,setName]=useState('');const [description,setDescription]=useState('');const [mode,setMode]=useState('contains');const [keyword,setKeyword]=useState('');
 const libraries=useQuery({queryKey:['keyword-libraries',access.corp.id,nameFilter],queryFn:()=>api.read('/keyword-library/libraries',{page:1,perPage:50,...(nameFilter?{name:nameFilter}:{})}),enabled:access.corp.authorized});const rows=useMemo(()=>unwrap(libraries.data),[libraries.data]);
 const entries=useQuery({queryKey:['keyword-entries',access.corp.id,selected?.id],queryFn:()=>api.read('/keyword-library/entries',{libraryId:Number(selected?.id),page:1,perPage:100}),enabled:access.corp.authorized&&Number(selected?.id)>0});const entryRows=useMemo(()=>unwrap(entries.data),[entries.data]);
 const refresh=()=>client.invalidateQueries({queryKey:['keyword-libraries',access.corp.id]});const refreshEntries=()=>client.invalidateQueries({queryKey:['keyword-entries',access.corp.id]});
 const save=useMutation({mutationFn:()=>api.write('/keyword-library/libraries',{...(editing?.id?{id:editing.id}:{}),name,description,matchMode:mode,status:text(editing?.status)||'enabled'},editing?.id?'PUT':'POST'),onSuccess:()=>{setEditing(null);void refresh()}});
 const status=useMutation({mutationFn:(r:Row)=>api.write('/keyword-library/libraries/status',{id:r.id,status:r.status==='enabled'?'disabled':'enabled'},'PUT'),onSuccess:()=>void refresh()});
 const publish=useMutation({mutationFn:(r:Row)=>api.write('/keyword-library/libraries/publish',{id:r.id}),onSuccess:()=>void refresh()});
 const remove=useMutation({mutationFn:(r:Row)=>api.write(`/keyword-library/libraries?id=${r.id}`,{},'DELETE'),onSuccess:()=>{setSelected(null);void refresh()}});
 const saveEntry=useMutation({mutationFn:()=>api.write('/keyword-library/entries',{...(entryEditing?.id?{id:entryEditing.id}:{}),libraryId:selected?.id,keyword,status:text(entryEditing?.status)||'enabled'},entryEditing?.id?'PUT':'POST'),onSuccess:()=>{setEntryEditing(null);setKeyword('');void refreshEntries();void refresh()}});
 const entryStatus=useMutation({mutationFn:(r:Row)=>api.write('/keyword-library/entries/status',{id:r.id,status:r.status==='enabled'?'disabled':'enabled'},'PUT'),onSuccess:()=>void refreshEntries()});const deleteEntry=useMutation({mutationFn:(r:Row)=>api.write(`/keyword-library/entries?id=${r.id}`,{},'DELETE'),onSuccess:()=>{void refreshEntries();void refresh()}});
 const edit=(r?:Row)=>{setEditing(r??{});setName(text(r?.name));setDescription(text(r?.description));setMode(text(r?.matchMode)||'contains')};
 return <section className="phase33-risk-warning-page"><header className="phase33-risk-warning-header dashboard-page-header dashboard-data-card"><div><p className="phase33-risk-warning-eyebrow">风险预警</p><h1>关键词库</h1><p>维护可复用关键词，并发布不可变版本供消息拦截规则引用。</p></div><button onClick={()=>void libraries.refetch()}>刷新</button></header><div className="dashboard-filter-bar"><label>词库名称<input aria-label="词库名称筛选" value={nameFilter} onChange={e=>setNameFilter(e.target.value)}/></label><button onClick={()=>void libraries.refetch()}>查询</button><button onClick={()=>edit()}>新建词库</button></div>
 <div className="dashboard-data-card phase33-risk-warning-results"><div className="dashboard-card-heading"><div><h2>词库列表</h2><p>编辑草稿后需要重新发布，已被规则引用的历史版本不会改变。</p></div></div>{libraries.isPending?<PageState state="loading"/>:libraries.isError?<PageState state={pageStateForError(libraries.error)} onRetry={()=>void libraries.refetch()}/>:rows.length===0?<PageState state="empty"/>:<div className="dashboard-table-scroll"><table><thead><tr><th>名称</th><th>匹配方式</th><th>词条数</th><th>草稿版本</th><th>发布版本</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(r=><tr key={text(r.id)}><td>{show(r.name)}</td><td>{r.matchMode==='exact'?'完全匹配':'包含匹配'}</td><td>{show(r.entryCount)}</td><td>v{show(r.draftVersion)}</td><td>{Number(r.publishedVersion)>0?`v${r.publishedVersion}`:'未发布'}</td><td>{r.status==='enabled'?'启用':'停用'}</td><td><button onClick={()=>setSelected(r)}>词条</button><button onClick={()=>edit(r)}>编辑</button><button onClick={()=>status.mutate(r)}>{r.status==='enabled'?'停用':'启用'}</button><button disabled={Number(r.entryCount)<=0} onClick={()=>publish.mutate(r)}>发布</button><button onClick={()=>remove.mutate(r)}>删除</button></td></tr>)}</tbody></table></div>}</div>
 {editing&&<aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="词库编辑"><div className="dashboard-card-heading"><h2>{editing.id?'编辑词库':'新建词库'}</h2><button onClick={()=>setEditing(null)}>关闭</button></div><div className="dashboard-filter-bar"><label>名称<input aria-label="词库名称" value={name} onChange={e=>setName(e.target.value)}/></label><label>说明<input aria-label="词库说明" value={description} onChange={e=>setDescription(e.target.value)}/></label><label>匹配方式<select aria-label="匹配方式" value={mode} onChange={e=>setMode(e.target.value)}><option value="contains">包含匹配</option><option value="exact">完全匹配</option></select></label><button disabled={!name.trim()||save.isPending} onClick={()=>save.mutate()}>保存</button></div></aside>}
 {selected&&<aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="关键词维护"><div className="dashboard-card-heading"><div><h2>{text(selected.name)} · 关键词</h2><p>当前草稿词条，修改后发布新版本才会影响新规则。</p></div><button onClick={()=>setSelected(null)}>关闭</button></div><div className="dashboard-filter-bar"><label>关键词<input aria-label="关键词" value={keyword} onChange={e=>setKeyword(e.target.value)}/></label><button disabled={!keyword.trim()} onClick={()=>saveEntry.mutate()}>{entryEditing?.id?'保存词条':'添加词条'}</button>{entryEditing&&<button onClick={()=>{setEntryEditing(null);setKeyword('')}}>取消</button>}</div>{entries.isPending?<PageState state="loading"/>:entryRows.length===0?<PageState state="empty"/>:<div className="dashboard-table-scroll"><table><thead><tr><th>关键词</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{entryRows.map(r=><tr key={text(r.id)}><td>{show(r.keyword)}</td><td>{r.status==='enabled'?'启用':'停用'}</td><td>{show(r.updatedAt)}</td><td><button onClick={()=>{setEntryEditing(r);setKeyword(text(r.keyword))}}>编辑</button><button onClick={()=>entryStatus.mutate(r)}>{r.status==='enabled'?'停用':'启用'}</button><button onClick={()=>deleteEntry.mutate(r)}>删除</button></td></tr>)}</tbody></table></div>}</aside>}
 </section>
}

export function MessageInterceptPage({api}:{api:BusinessWorkbenchApi}){
 const access=useDashboardAccess(),client=useQueryClient();const [tab,setTab]=useState<'records'|'rules'>('records');const [keyword,setKeyword]=useState('');const [decision,setDecision]=useState('');const [selected,setSelected]=useState<Row|null>(null);const [checked,setChecked]=useState<Set<number>>(new Set());const [editing,setEditing]=useState<Row|null>(null);const [name,setName]=useState('');const [libraryId,setLibraryId]=useState('');const [scopeSingle,setScopeSingle]=useState(true);const [scopeGroup,setScopeGroup]=useState(false);const [ruleDecision,setRuleDecision]=useState('blocked');
 const query=useQuery({queryKey:['message-intercept',access.corp.id,tab,keyword,decision],queryFn:()=>api.read(tab==='records'?'/message-intercept/records':'/message-intercept/rules',{page:1,perPage:50,...(tab==='records'&&keyword?{keyword}:{}),...(tab==='records'&&decision?{decision}:{})}),enabled:access.corp.authorized});const data=useMemo(()=>unwrap(query.data),[query.data]);
 const libs=useQuery({queryKey:['keyword-libraries-for-rules',access.corp.id],queryFn:()=>api.read('/keyword-library/libraries',{page:1,perPage:100,status:'enabled'}),enabled:access.corp.authorized&&tab==='rules'});const libraryRows=useMemo(()=>unwrap(libs.data).filter(r=>Number(r.publishedVersion)>0),[libs.data]);const chosen=libraryRows.find(r=>text(r.id)===libraryId);
 const refresh=()=>client.invalidateQueries({queryKey:['message-intercept',access.corp.id]});const save=useMutation({mutationFn:()=>api.write('/message-intercept/rules',{...(editing?.id?{id:editing.id}:{}),name,libraryId:Number(libraryId),libraryVersion:Number(chosen?.publishedVersion||editing?.libraryVersion),conversationScopes:[...(scopeSingle?['single']:[]),...(scopeGroup?['group']:[])],decision:ruleDecision,status:text(editing?.status)||'enabled'},editing?.id?'PUT':'POST'),onSuccess:()=>{setEditing(null);void refresh()}});const status=useMutation({mutationFn:(r:Row)=>api.write('/message-intercept/rules/status',{id:r.id,status:r.status==='enabled'?'disabled':'enabled'},'PUT'),onSuccess:()=>void refresh()});const remove=useMutation({mutationFn:(r:Row)=>api.write(`/message-intercept/rules?id=${r.id}`,{},'DELETE'),onSuccess:()=>void refresh()});const audit=useMutation({mutationFn:(action:string)=>api.write('/message-intercept/records/audit',{ids:[...checked],action,remark:''}),onSuccess:()=>{setChecked(new Set());void refresh()}});
 const edit=(r?:Row)=>{setEditing(r??{});setName(text(r?.name));setLibraryId(text(r?.libraryId));const scopes=Array.isArray(r?.conversationScopes)?r.conversationScopes.map(text):['single'];setScopeSingle(scopes.includes('single'));setScopeGroup(scopes.includes('group'));setRuleDecision(text(r?.decision)||'blocked')};
 return <section className="phase33-risk-warning-page"><header className="phase33-risk-warning-header dashboard-page-header dashboard-data-card"><div><p className="phase33-risk-warning-eyebrow">风险预警</p><h1>消息拦截</h1><p>按已发布词库版本评估消息，查看拦截解释并完成合规复核。</p></div><button onClick={()=>void query.refetch()}>刷新</button></header><div className="dashboard-tabs"><button aria-pressed={tab==='records'} onClick={()=>setTab('records')}>命中记录</button><button aria-pressed={tab==='rules'} onClick={()=>setTab('rules')}>拦截规则</button></div>{tab==='records'?<div className="dashboard-filter-bar"><label>内容或关键词<input aria-label="内容或关键词" value={keyword} onChange={e=>setKeyword(e.target.value)}/></label><label>处理决定<select aria-label="处理决定" value={decision} onChange={e=>setDecision(e.target.value)}><option value="">全部</option><option value="blocked">拦截</option><option value="review_required">需要复核</option><option value="allowed">放行</option></select></label><button onClick={()=>void query.refetch()}>查询</button>{checked.size>0&&<><button onClick={()=>audit.mutate('confirmed')}>确认违规</button><button onClick={()=>audit.mutate('ignored')}>忽略</button></>}</div>:<div className="dashboard-filter-bar"><button onClick={()=>edit()}>新建规则</button></div>}
 <div className="dashboard-data-card phase33-risk-warning-results"><div className="dashboard-card-heading"><div><h2>{tab==='records'?'命中记录':'拦截规则'}</h2><p>{tab==='records'?'每条记录固定关联命中时的规则和词库版本。':'规则只引用已发布的词库版本。'}</p></div></div>{query.isPending?<PageState state="loading"/>:query.isError?<PageState state={pageStateForError(query.error)} onRetry={()=>void query.refetch()}/>:data.length===0?<PageState state="empty"/>:<div className="dashboard-table-scroll"><table><thead><tr>{tab==='records'&&<th>选择</th>}<th>{tab==='records'?'发送者':'规则名称'}</th><th>{tab==='records'?'消息内容':'词库'}</th><th>{tab==='records'?'命中词':'版本'}</th><th>决定</th><th>{tab==='records'?'复核状态':'状态'}</th><th>操作</th></tr></thead><tbody>{data.map(r=><tr key={text(r.id)}>{tab==='records'&&<td><input type="checkbox" aria-label={`选择记录 ${r.id}`} checked={checked.has(Number(r.id))} onChange={e=>setChecked(old=>{const n=new Set(old);e.target.checked?n.add(Number(r.id)):n.delete(Number(r.id));return n})}/></td>}<td>{show(tab==='records'?r.senderName:r.name)}</td><td>{show(tab==='records'?r.messageContent:r.libraryName)}</td><td>{show(tab==='records'?r.matchedKeywords:`v${r.libraryVersion}`)}</td><td>{show(r.decision)}</td><td>{show(tab==='records'?r.auditStatus:r.status)}</td><td>{tab==='records'?<button onClick={()=>setSelected(r)}>详情</button>:<><button onClick={()=>edit(r)}>编辑</button><button onClick={()=>status.mutate(r)}>{r.status==='enabled'?'停用':'启用'}</button><button onClick={()=>remove.mutate(r)}>删除</button></>}</td></tr>)}</tbody></table></div>}</div>
 {editing&&<aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="拦截规则编辑"><div className="dashboard-card-heading"><h2>{editing.id?'编辑规则':'新建规则'}</h2><button onClick={()=>setEditing(null)}>关闭</button></div><div className="dashboard-filter-bar"><label>规则名称<input aria-label="规则名称" value={name} onChange={e=>setName(e.target.value)}/></label><label>已发布词库<select aria-label="已发布词库" value={libraryId} onChange={e=>setLibraryId(e.target.value)}><option value="">请选择</option>{libraryRows.map(r=><option key={text(r.id)} value={text(r.id)}>{text(r.name)} · v{text(r.publishedVersion)}</option>)}</select></label><label>决定<select aria-label="规则决定" value={ruleDecision} onChange={e=>setRuleDecision(e.target.value)}><option value="blocked">拦截</option><option value="review_required">需要复核</option><option value="allowed">放行并记录</option></select></label><label><input type="checkbox" checked={scopeSingle} onChange={e=>setScopeSingle(e.target.checked)}/>单聊</label><label><input type="checkbox" checked={scopeGroup} onChange={e=>setScopeGroup(e.target.checked)}/>群聊</label><button disabled={!name.trim()||!libraryId||(!scopeSingle&&!scopeGroup)} onClick={()=>save.mutate()}>保存</button></div></aside>}{selected&&<aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="拦截记录详情"><div className="dashboard-card-heading"><h2>拦截记录详情</h2><button onClick={()=>setSelected(null)}>关闭</button></div><dl>{Object.entries(selected).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{show(v)}</dd></div>)}</dl></aside>}
 </section>
}
