import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';

import { useDashboardAccess } from '../../app/access-context';
import { ConfirmAction } from '../../components/confirm-action';
import { DashboardPagination } from '../../components/dashboard-pagination';
import { PageState, pageStateForError } from '../../components/page-state/page-state';
import { RiskWarningDrawer, RiskWarningPageHeader, RiskWarningQueryBar, RiskWarningShell, RiskWarningTabs } from '../risk-warning/risk-warning-shell';
import { auditStatusLabel, conversationTypeLabel, formatRiskDateTime } from '../risk-warning/risk-warning-format';
import type { KeywordLibrary, MessageInterceptApi, MessageInterceptRecord, MessageInterceptRule } from './message-intercept-api';

const recordDefault = { keyword: '', conversationType: '', decision: '', auditStatus: '', page: 1, perPage: 20 };
const ruleDefault = { name: '', status: '', decision: '', page: 1, perPage: 20 };
const decisionLabel: Record<string, string> = { blocked: '拦截', review_required: '需要复核', allowed: '放行并记录' };
const statusLabel: Record<string, string> = { enabled: '启用', disabled: '停用' };
const scopeLabel: Record<string, string> = { single: '客户单聊', group: '客户群聊' };
function mutationMessage(error: unknown): string {
  if (error instanceof Error && error.message) return error.message;
  return '操作未完成，请稍后重试。';
}
function readRecordFilter(params: URLSearchParams) { return { keyword: params.get('keyword') ?? '', conversationType: params.get('conversationType') ?? '', decision: params.get('decision') ?? '', auditStatus: params.get('auditStatus') ?? '', page: Number(params.get('page') ?? 1) || 1, perPage: 20 }; }
function writeRecordFilter(params: URLSearchParams, filter: typeof recordDefault) { const next = new URLSearchParams(params); ['keyword', 'conversationType', 'decision', 'auditStatus', 'page'].forEach((key) => next.delete(key)); for (const [key, value] of Object.entries(filter)) if (value !== '' && value !== undefined && value !== 1 && value !== 20) next.set(key, String(value)); return next; }
function readRuleFilter(params: URLSearchParams) { return { name: params.get('ruleName') ?? '', status: params.get('ruleStatus') ?? '', decision: params.get('ruleDecision') ?? '', page: Number(params.get('rulePage') ?? 1) || 1, perPage: 20 }; }
function writeRuleFilter(params: URLSearchParams, filter: typeof ruleDefault) { const next = new URLSearchParams(params); ['ruleName', 'ruleStatus', 'ruleDecision', 'rulePage'].forEach((key) => next.delete(key)); if (filter.name) next.set('ruleName', filter.name); if (filter.status) next.set('ruleStatus', filter.status); if (filter.decision) next.set('ruleDecision', filter.decision); if (filter.page > 1) next.set('rulePage', String(filter.page)); return next; }

function recordDetail(record: MessageInterceptRecord) {
  return <dl className="risk-warning-detail-grid"><div><dt>发送者</dt><dd>{record.senderName || record.senderId || '未标注'}</dd></div><div><dt>消息内容</dt><dd>{record.messageContent || '暂无内容'}</dd></div><div><dt>命中关键词</dt><dd>{record.matchedKeywords.length ? record.matchedKeywords.join('、') : '未返回关键词'}</dd></div><div><dt>规则与版本</dt><dd>{record.ruleName || '未标注'} · {record.libraryName || '未标注'} {record.libraryVersion ? `v${record.libraryVersion}` : ''}</dd></div><div><dt>拦截决定</dt><dd>{(decisionLabel[record.decision] ?? record.decision) || '未标注'}</dd></div><div><dt>复核状态</dt><dd>{auditStatusLabel(record.auditStatus)}</dd></div><div><dt>发生时间</dt><dd>{formatRiskDateTime(record.occurredAt)}</dd></div><div><dt>判定说明</dt><dd>{record.explanation || '暂无判定说明'}</dd></div></dl>;
}

export function MessageInterceptPage({ api }: { api: MessageInterceptApi }) {
  const access = useDashboardAccess();
  const queryClient = useQueryClient();
  const location = useLocation();
  const navigate = useNavigate();
  const params = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const setParams = (next: URLSearchParams) => { void navigate({ search: next.toString() ? `?${next.toString()}` : '' }); };
  const tab = params.get('tab') === 'rules' ? 'rules' : 'records';
  const recordFilter = useMemo(() => readRecordFilter(params), [params]);
  const ruleFilter = useMemo(() => readRuleFilter(params), [params]);
  const [recordDraft, setRecordDraft] = useState(recordFilter);
  const [ruleDraft, setRuleDraft] = useState(ruleFilter);
  const selectedId = Number(params.get('recordId') ?? 0) || null;
  const editorOpen = params.get('ruleEditor') === '1';
  const editingRuleId = Number(params.get('ruleId') ?? 0) || null;
  const [checked, setChecked] = useState<Set<number>>(new Set());
  const [editingRule, setEditingRule] = useState<MessageInterceptRule | null>(null);
  const [ruleName, setRuleName] = useState('');
  const [libraryId, setLibraryId] = useState('');
  const [decision, setDecision] = useState('blocked');
  const [scopes, setScopes] = useState<string[]>(['single']);
  const [feedback, setFeedback] = useState<{ kind: 'success' | 'error'; text: string } | null>(null);
  const records = useQuery({ queryKey: ['message-intercept-records', access.corp.id, recordFilter], queryFn: () => api.records(recordFilter), enabled: access.corp.authorized && tab === 'records', retry: false });
  const rules = useQuery({ queryKey: ['message-intercept-rules', access.corp.id, ruleFilter], queryFn: () => api.rules(ruleFilter), enabled: access.corp.authorized && tab === 'rules', retry: false });
  const libraries = useQuery({ queryKey: ['message-intercept-published-libraries', access.corp.id], queryFn: () => api.libraries({ page: 1, perPage: 100, status: 'enabled' }), enabled: access.corp.authorized && (tab === 'rules' || editorOpen), retry: false });
  const selectedRecord = records.data?.items.find((item) => item.id === selectedId) ?? null;
  const selectedRule = rules.data?.items.find((item) => item.id === editingRuleId) ?? null;
  const publishedLibraries = useMemo(() => (libraries.data?.items ?? []).filter((item) => item.publishedVersion > 0), [libraries.data]);
  useEffect(() => {
    if (!editorOpen || !editingRuleId || !selectedRule || editingRule?.id === selectedRule.id) return;
    setEditingRule(selectedRule);
    setRuleName(selectedRule.name);
    setLibraryId(String(selectedRule.libraryId));
    setDecision(selectedRule.decision);
    setScopes(selectedRule.conversationScopes.length ? selectedRule.conversationScopes : ['single']);
  }, [editorOpen, editingRule, editingRuleId, selectedRule]);
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['message-intercept-records', access.corp.id] }); void queryClient.invalidateQueries({ queryKey: ['message-intercept-rules', access.corp.id] }); void libraries.refetch(); };
  const setTab = (next: string) => { const value = new URLSearchParams(params); value.set('tab', next); value.delete('recordId'); value.delete('ruleEditor'); setParams(value); setChecked(new Set()); };
  const queryRecords = () => { const next = { ...recordDraft, keyword: recordDraft.keyword.trim(), page: 1 }; setRecordDraft(next); setParams(writeRecordFilter(new URLSearchParams(params), next)); setChecked(new Set()); };
  const resetRecords = () => { const next = { ...recordDefault }; setRecordDraft(next); setParams(writeRecordFilter(new URLSearchParams(params), next)); setChecked(new Set()); };
  const queryRules = () => { const next = { ...ruleDraft, name: ruleDraft.name.trim(), page: 1 }; setRuleDraft(next); setParams(writeRuleFilter(new URLSearchParams(params), next)); };
  const resetRules = () => { const next = { ...ruleDefault }; setRuleDraft(next); setParams(writeRuleFilter(new URLSearchParams(params), next)); };
  const openRuleEditor = (item?: MessageInterceptRule) => { const next = new URLSearchParams(params); next.set('ruleEditor', '1'); if (item) next.set('ruleId', String(item.id)); else next.delete('ruleId'); setParams(next); setEditingRule(item ?? null); setRuleName(item?.name ?? ''); setLibraryId(item ? String(item.libraryId) : ''); setDecision(item?.decision ?? 'blocked'); setScopes(item?.conversationScopes.length ? item.conversationScopes : ['single']); setFeedback(null); };
  const closeRuleEditor = () => { const next = new URLSearchParams(params); next.delete('ruleEditor'); next.delete('ruleId'); setParams(next); setEditingRule(null); };
  const openRecord = (record: MessageInterceptRecord) => { const next = new URLSearchParams(params); next.set('recordId', String(record.id)); setParams(next); };
  const closeRecord = () => { const next = new URLSearchParams(params); next.delete('recordId'); setParams(next); };
  const saveRule = useMutation({ mutationFn: () => { const library = publishedLibraries.find((item) => item.id === Number(libraryId)); return api.write('/message-intercept/rules', { ...(editingRule ? { id: editingRule.id } : {}), name: ruleName.trim(), libraryId: Number(libraryId), libraryVersion: library?.publishedVersion ?? editingRule?.libraryVersion ?? 0, conversationScopes: scopes, decision, status: editingRule?.status ?? 'enabled' }, editingRule ? 'PUT' : 'POST'); }, onSuccess: () => { closeRuleEditor(); setFeedback({ kind: 'success', text: '拦截规则已保存。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const toggleRule = useMutation({ mutationFn: (item: MessageInterceptRule) => api.write('/message-intercept/rules/status', { id: item.id, status: item.status === 'enabled' ? 'disabled' : 'enabled' }, 'PUT'), onSuccess: () => { setFeedback({ kind: 'success', text: '规则状态已更新。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const deleteRule = useMutation({ mutationFn: (item: MessageInterceptRule) => api.write(`/message-intercept/rules?id=${item.id}`, {}, 'DELETE'), onSuccess: () => { setFeedback({ kind: 'success', text: '拦截规则已删除。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const audit = useMutation({ mutationFn: (action: string) => api.write('/message-intercept/records/audit', { ids: [...checked], action, remark: '' }), onSuccess: () => { setChecked(new Set()); setFeedback({ kind: 'success', text: '复核状态已更新。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const updateRecordDraft = (key: keyof typeof recordDefault, value: string) => setRecordDraft((current) => ({ ...current, [key]: value, page: 1 }));
  const updateRuleDraft = (key: keyof typeof ruleDefault, value: string) => setRuleDraft((current) => ({ ...current, [key]: value, page: 1 }));
  return <RiskWarningShell className="message-intercept-page">
    <RiskWarningPageHeader eyebrow="风险预警" title="消息拦截" meta="查看已同步消息的命中记录，并维护引用已发布词库的拦截规则。" />
    <RiskWarningTabs active={tab} tabs={[{ id: 'records', label: '命中记录' }, { id: 'rules', label: '拦截规则' }]} onChange={setTab} />
    <RiskWarningQueryBar fetching={records.isFetching || rules.isFetching} onQuery={tab === 'records' ? queryRecords : queryRules} onReset={tab === 'records' ? resetRecords : resetRules} onRefresh={refresh}>{tab === 'records' ? <><label>内容或关键词<input aria-label="内容或关键词" placeholder="输入内容或关键词" value={recordDraft.keyword} onChange={(event) => updateRecordDraft('keyword', event.target.value)} /></label><label>会话类型<select aria-label="会话类型" value={recordDraft.conversationType} onChange={(event) => updateRecordDraft('conversationType', event.target.value)}><option value="">全部</option><option value="customer">客户单聊</option><option value="group">客户群聊</option></select></label><label>拦截决定<select aria-label="拦截决定" value={recordDraft.decision} onChange={(event) => updateRecordDraft('decision', event.target.value)}><option value="">全部</option><option value="blocked">拦截</option><option value="review_required">需要复核</option><option value="allowed">放行并记录</option></select></label><label>复核状态<select aria-label="复核状态" value={recordDraft.auditStatus} onChange={(event) => updateRecordDraft('auditStatus', event.target.value)}><option value="">全部</option><option value="pending">待复核</option><option value="confirmed">已确认</option><option value="ignored">已忽略</option><option value="reviewed">已复核</option></select></label></> : <><label>规则名称<input aria-label="规则名称" placeholder="输入规则名称" value={ruleDraft.name} onChange={(event) => updateRuleDraft('name', event.target.value)} /></label><label>状态<select aria-label="规则状态" value={ruleDraft.status} onChange={(event) => updateRuleDraft('status', event.target.value)}><option value="">全部</option><option value="enabled">启用</option><option value="disabled">停用</option></select></label><label>拦截决定<select aria-label="规则决定" value={ruleDraft.decision} onChange={(event) => updateRuleDraft('decision', event.target.value)}><option value="">全部</option><option value="blocked">拦截</option><option value="review_required">需要复核</option><option value="allowed">放行并记录</option></select></label></>}</RiskWarningQueryBar>
    {feedback ? <p className={`risk-warning-inline-feedback is-${feedback.kind}`} role="alert">{feedback.text}</p> : null}
    <div className="risk-warning-results"><div className="risk-warning-results-header"><div><h2>{tab === 'records' ? '命中记录' : '拦截规则'}</h2><p>{tab === 'records' ? '记录来自同步消息和已发布规则的评估结果。' : '规则只能引用已发布词库，修改后对新消息生效。'}</p></div>{tab === 'rules' ? <button type="button" className="risk-warning-primary-button" onClick={() => openRuleEditor()}>新增规则</button> : null}</div>{tab === 'records' ? <RecordTable page={records.data} loading={records.isPending} error={records.error} checked={checked} onChecked={(id, value) => setChecked((current) => { const next = new Set(current); if (value) next.add(id); else next.delete(id); return next; })} onOpen={openRecord} onPageChange={(page) => { const next = { ...recordFilter, page }; setParams(writeRecordFilter(new URLSearchParams(params), next)); }} onRetry={() => void records.refetch()} onAudit={(action) => audit.mutate(action)} /> : <RuleTable page={rules.data} loading={rules.isPending} error={rules.error} onOpen={openRuleEditor} onToggle={(item) => toggleRule.mutate(item)} onDelete={(item) => deleteRule.mutate(item)} onPageChange={(page) => setParams(writeRuleFilter(new URLSearchParams(params), { ...ruleFilter, page }))} onRetry={() => void rules.refetch()} />}</div>
    <RiskWarningDrawer open={selectedRecord !== null} title="消息拦截详情" {...(selectedRecord ? { description: `记录 #${selectedRecord.id}` } : {})} onClose={closeRecord}>{selectedRecord ? recordDetail(selectedRecord) : null}</RiskWarningDrawer>
    <RiskWarningDrawer open={editorOpen} title={editingRule ? '编辑拦截规则' : '新增拦截规则'} description="规则绑定已发布词库版本，避免历史记录口径变化。" onClose={closeRuleEditor}><form className="risk-warning-form" onSubmit={(event) => { event.preventDefault(); if (ruleName.trim() && Number(libraryId) > 0 && scopes.length > 0) saveRule.mutate(); }}><label>规则名称<input aria-label="编辑规则名称" value={ruleName} onChange={(event) => setRuleName(event.target.value)} autoFocus /></label><label>已发布词库<select aria-label="已发布词库" value={libraryId} onChange={(event) => setLibraryId(event.target.value)}><option value="">请选择词库</option>{publishedLibraries.map((item) => <option key={item.id} value={item.id}>{item.name} · v{item.publishedVersion}</option>)}</select></label><label>命中后的处理<select aria-label="编辑规则决定" value={decision} onChange={(event) => setDecision(event.target.value)}><option value="blocked">拦截</option><option value="review_required">需要复核</option><option value="allowed">放行并记录</option></select></label><fieldset><legend>拦截对象</legend>{([['single', '客户单聊'], ['group', '客户群聊']] as const).map(([value, label]) => <label key={value}><input type="checkbox" checked={scopes.includes(value)} onChange={(event) => setScopes((current) => event.target.checked ? [...new Set([...current, value])] : current.filter((item) => item !== value))} />{label}</label>)}</fieldset><p className="risk-warning-form-note">保存后，新同步消息会按此规则评估。</p><div className="risk-warning-drawer-actions"><button type="button" className="risk-warning-secondary-button" onClick={closeRuleEditor}>取消</button><button type="button" className="risk-warning-primary-button" disabled={!ruleName.trim() || !libraryId || scopes.length === 0 || saveRule.isPending} onClick={() => saveRule.mutate()}>保存</button></div></form></RiskWarningDrawer>
  </RiskWarningShell>;
}

function RecordTable({ page, loading, error, checked, onChecked, onOpen, onPageChange, onRetry, onAudit }: { page: { items: MessageInterceptRecord[]; total: number; page: number; perPage: number } | undefined; loading: boolean; error: unknown; checked: Set<number>; onChecked: (id: number, value: boolean) => void; onOpen: (record: MessageInterceptRecord) => void; onPageChange: (page: number) => void; onRetry: () => void; onAudit: (action: string) => void }) {
  if (loading && !page) return <PageState state="loading" />;
  if (error && !page) return <PageState state={pageStateForError(error)} onRetry={onRetry} />;
  if (!page || page.items.length === 0) return <PageState state="empty" title="暂无命中记录" description="当前筛选下没有需要展示的同步消息记录。" />;
  return <><div className="risk-warning-batch-bar">{checked.size ? <><span>已选 {checked.size} 条</span><ConfirmAction title="确认将选中记录标记为已确认？" onConfirm={() => onAudit('confirmed')}><button type="button">确认违规</button></ConfirmAction><ConfirmAction title="确认忽略选中记录？" onConfirm={() => onAudit('ignored')}><button type="button">忽略</button></ConfirmAction></> : <span className="risk-warning-muted">点击行查看判定说明；勾选后可批量复核。</span>}</div><div className="risk-warning-table-wrap"><table className="risk-warning-table message-intercept-record-table"><thead><tr><th>选择</th><th>发送者</th><th>消息内容</th><th>命中词</th><th>会话类型</th><th>决定</th><th>复核状态</th><th>发生时间</th><th>操作</th></tr></thead><tbody>{page.items.map((record) => <tr key={record.id} onClick={(event) => { if ((event.target as HTMLElement).closest('input,button,a,select')) return; onOpen(record); }}><td className="risk-warning-row-control"><input type="checkbox" aria-label={`选择记录 ${record.id}`} checked={checked.has(record.id)} onChange={(event) => onChecked(record.id, event.target.checked)} /></td><td>{record.senderName || record.senderId || '未标注'}</td><td><span className="risk-warning-inline-preview" title={record.messageContent}>{record.messageContent || '暂无内容'}</span></td><td>{record.matchedKeywords.length ? record.matchedKeywords.join('、') : '未返回'}</td><td>{conversationTypeLabel(record.conversationType)}</td><td><span className="risk-warning-pill risk-warning-pill-neutral">{(decisionLabel[record.decision] ?? record.decision) || '未标注'}</span></td><td>{auditStatusLabel(record.auditStatus)}</td><td>{formatRiskDateTime(record.occurredAt)}</td><td className="risk-warning-row-control"><button type="button" onClick={() => onOpen(record)}>查看详情</button></td></tr>)}</tbody></table></div><div className="risk-warning-pagination"><DashboardPagination page={page.page} pageSize={20} total={page.total} onPageChange={onPageChange} ariaLabel="消息拦截记录分页" /></div></>;
}

function RuleTable({ page, loading, error, onOpen, onToggle, onDelete, onPageChange, onRetry }: { page: { items: MessageInterceptRule[]; total: number; page: number; perPage: number } | undefined; loading: boolean; error: unknown; onOpen: (rule: MessageInterceptRule) => void; onToggle: (rule: MessageInterceptRule) => void; onDelete: (rule: MessageInterceptRule) => void; onPageChange: (page: number) => void; onRetry: () => void }) {
  if (loading && !page) return <PageState state="loading" />;
  if (error && !page) return <PageState state={pageStateForError(error)} onRetry={onRetry} />;
  if (!page || page.items.length === 0) return <PageState state="empty" title="暂无拦截规则" description="新增规则并选择已发布词库后开始拦截评估。" />;
  return <><div className="risk-warning-table-wrap"><table className="risk-warning-table message-intercept-rule-table"><thead><tr><th>规则名称</th><th>词库版本</th><th>拦截对象</th><th>处理决定</th><th>命中次数</th><th>状态</th><th>最后编辑</th><th>操作</th></tr></thead><tbody>{page.items.map((rule) => <tr key={rule.id}><td>{rule.name || '未命名规则'}</td><td>{rule.libraryName || '未标注'} {rule.libraryVersion ? `v${rule.libraryVersion}` : ''}</td><td>{rule.conversationScopes.length ? rule.conversationScopes.map((scope) => scopeLabel[scope] ?? scope).join('、') : '未配置'}</td><td>{(decisionLabel[rule.decision] ?? rule.decision) || '未标注'}</td><td>{rule.triggerCount}</td><td>{statusLabel[rule.status] ?? rule.status}</td><td>{formatRiskDateTime(rule.updatedAt)}</td><td className="sensitive-word-row-actions"><button type="button" onClick={() => onOpen(rule)}>编辑</button><ConfirmAction title={`确认${rule.status === 'enabled' ? '停用' : '启用'}规则“${rule.name}”？`} onConfirm={() => onToggle(rule)}><button type="button" aria-label={`${rule.status === 'enabled' ? '停用' : '启用'} ${rule.name}`}>{rule.status === 'enabled' ? '停用' : '启用'}</button></ConfirmAction><ConfirmAction title={`确认删除规则“${rule.name}”？`} description="删除后无法恢复。" onConfirm={() => onDelete(rule)}><button type="button" aria-label={`删除 ${rule.name}`}>删除</button></ConfirmAction></td></tr>)}</tbody></table></div><div className="risk-warning-pagination"><DashboardPagination page={page.page} pageSize={20} total={page.total} onPageChange={onPageChange} ariaLabel="拦截规则分页" /></div></>;
}
