import { useQuery } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { useDashboardAccess } from '../../app/access-context';
import { pageStateForError, PageState } from '../../components/page-state/page-state';
import type { BusinessWorkbenchApi } from '../business-workbench/business-workbench-page';

type Row = Record<string, unknown>;
function rows(value: unknown): Row[] { if (Array.isArray(value)) return value.filter((v): v is Row => !!v && typeof v === 'object'); if (!value || typeof value !== 'object') return []; const v=value as Row; const b=v.data&&typeof v.data==='object'?v.data as Row:v; const list=[b.items,b.list,b.rows].find(Array.isArray); return Array.isArray(list)?list.filter((x):x is Row=>!!x&&typeof x==='object'):[]; }
function text(value: unknown): string { return value == null || value === '' ? '--' : typeof value === 'object' ? JSON.stringify(value) : String(value); }
export function RiskBehaviorPage({ api }: { api: BusinessWorkbenchApi }) {
  const access=useDashboardAccess(); const [tab,setTab]=useState<'records'|'rules'>('records'); const [level,setLevel]=useState(''); const [behavior,setBehavior]=useState(''); const [selected,setSelected]=useState<Row|null>(null);
  const query=useQuery({queryKey:['phase33-risk-behavior',access.corp.id,tab,level,behavior],queryFn:()=>api.read(tab==='records'?'/risk/records':'/risk/rules',{page:1,perPage:20,...(level?{riskLevel:level}:{}),...(behavior?{behavior}: {})}),enabled:access.corp.authorized});
  const data=useMemo(()=>rows(query.data),[query.data]); const columns=useMemo(()=>Object.keys(data[0]??{}).filter(k=>!['tenantId','corpId','relatedUser'].includes(k)).slice(0,8),[data]);
  return <section className="phase33-risk-warning-page"><header className="phase33-risk-warning-header dashboard-page-header dashboard-data-card"><div><p className="phase33-risk-warning-eyebrow">风险预警</p><h1>风险行为</h1><p>识别和跟进会话中的风险行为。</p></div><button type="button" disabled={query.isFetching} onClick={()=>void query.refetch()}>刷新</button></header><div className="dashboard-tabs"><button type="button" aria-pressed={tab==='records'} onClick={()=>{setTab('records');setSelected(null);}}>风险记录</button><button type="button" aria-pressed={tab==='rules'} onClick={()=>{setTab('rules');setSelected(null);}}>规则配置</button></div>{tab==='records'&&<div className="dashboard-filter-bar phase33-risk-warning-filters"><label>风险等级<select aria-label="风险等级" value={level} onChange={e=>setLevel(e.target.value)}><option value="">全部</option><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option></select></label><label>风险行为<input aria-label="风险行为" value={behavior} onChange={e=>setBehavior(e.target.value)} placeholder="输入行为名称" /></label><button type="button" onClick={()=>void query.refetch()}>查询</button></div>}<div className="dashboard-data-card phase33-risk-warning-results"><div className="dashboard-card-heading"><div><h2>{tab==='records'?'风险记录':'规则配置'}</h2><p>{tab==='records'?'查看已识别的风险行为记录。':'管理风险行为识别规则。'}</p></div></div>{query.isPending?<PageState state="loading"/>:query.isError?<PageState state={pageStateForError(query.error)} onRetry={()=>void query.refetch()}/>:data.length===0?<PageState state="empty"/>:<div className="dashboard-table-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}<th>操作</th></tr></thead><tbody>{data.map((row,i)=><tr key={String(row.id??i)}>{columns.map(c=><td key={c}>{text(row[c])}</td>)}<td><button type="button" onClick={()=>setSelected(row)}>详情</button></td></tr>)}</tbody></table></div>}</div>{selected&&<aside className="phase33-risk-warning-detail dashboard-data-card"><div className="dashboard-card-heading"><div><h2>详情</h2><p>查看当前记录的完整信息。</p></div><button type="button" onClick={()=>setSelected(null)}>关闭</button></div><dl>{Object.entries(selected).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{text(v)}</dd></div>)}</dl></aside>}</section>;
}
