import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router';

import { useDashboardAccess } from '../../app/access-context';
import { RiskWarningDrawer, RiskWarningPageHeader, RiskWarningQueryBar, RiskWarningShell, RiskWarningTabs, ScannerStatusStrip } from '../risk-warning/risk-warning-shell';
import type { RiskBehaviorApi, RiskRecord, RiskRecordFilters } from './risk-behavior-api';
import { RiskBehaviorDetail } from './risk-behavior-detail';
import { RiskBehaviorRecords } from './risk-behavior-records';
import { RiskBehaviorRules } from './risk-behavior-rules';

const emptyFilters: RiskRecordFilters = { page: 1 };
function readFilters(params: URLSearchParams): RiskRecordFilters { return { riskLevel: params.get('riskLevel') ?? '', behavior: params.get('behavior') ?? '', auditStatus: params.get('auditStatus') ?? '', conversationType: params.get('conversationType') ?? '', employeeIds: (params.get('employeeIds') ?? '').split(',').map(Number).filter((item) => item > 0), occurredFrom: params.get('occurredFrom') ?? '', occurredTo: params.get('occurredTo') ?? '', page: Number(params.get('page') ?? 1) || 1 }; }
function writeFilters(params: URLSearchParams, filters: RiskRecordFilters): URLSearchParams { const next = new URLSearchParams(params); for (const key of ['riskLevel', 'behavior', 'auditStatus', 'conversationType', 'employeeIds', 'occurredFrom', 'occurredTo', 'page']) next.delete(key); for (const [key, value] of Object.entries(filters)) { if (key === 'employeeIds') { const ids = value as number[]; if (ids.length) next.set(key, ids.join(',')); } else if (value !== '' && value !== undefined) next.set(key, String(value)); } return next; }

export function RiskBehaviorPage({ api }: { api: RiskBehaviorApi }) {
  const access = useDashboardAccess(); const queryClient = useQueryClient(); const [params, setParams] = useSearchParams();
  const tab = params.get('tab') === 'rules' ? 'rules' : 'records';
  const initial = useMemo(() => readFilters(params), [params]);
  const [draft, setDraft] = useState<RiskRecordFilters>(initial); const [applied, setApplied] = useState<RiskRecordFilters>(initial); const [selectedID, setSelectedID] = useState<number | null>(Number(params.get('matchId')) || null); const [checked, setChecked] = useState<Set<number>>(new Set());
  const records = useQuery({ queryKey: ['risk-behavior-records', access.corp.id, applied], queryFn: () => api.records(applied), enabled: access.corp.authorized && tab === 'records', retry: false });
  const ruleName = params.get('ruleName') ?? ''; const rulePage = Number(params.get('rulePage') ?? 1) || 1; const [ruleNameDraft, setRuleNameDraft] = useState(ruleName);
  useEffect(() => setRuleNameDraft(ruleName), [ruleName]);
  const rules = useQuery({ queryKey: ['risk-behavior-rules', access.corp.id, ruleName, rulePage], queryFn: () => api.rules({ name: ruleName, page: rulePage }), enabled: access.corp.authorized && tab === 'rules', retry: false });
  const scanner = useQuery({ queryKey: ['risk-behavior-scanner-status', access.corp.id], queryFn: api.scannerStatus, enabled: access.corp.authorized, retry: false });
  const detail = useQuery({ queryKey: ['risk-behavior-detail', access.corp.id, selectedID], queryFn: () => api.recordDetail(selectedID ?? 0), enabled: selectedID !== null, retry: false });
  const setTab = (next: string) => { const value = new URLSearchParams(params); value.set('tab', next); value.delete('matchId'); setParams(value); setSelectedID(null); };
  const submit = () => { if (tab === 'rules') { const next = new URLSearchParams(params); next.set('rulePage', '1'); if (ruleNameDraft.trim()) next.set('ruleName', ruleNameDraft.trim()); else next.delete('ruleName'); setParams(next); return; } const next = { ...draft, page: 1 }; setApplied(next); setParams(writeFilters(new URLSearchParams(params), next)); setChecked(new Set()); };
  const reset = () => { if (tab === 'rules') { setRuleNameDraft(''); const next = new URLSearchParams(params); next.delete('ruleName'); next.set('rulePage', '1'); setParams(next); return; } const next = { ...emptyFilters }; setDraft(next); setApplied(next); setParams(writeFilters(new URLSearchParams(params), next)); setChecked(new Set()); };
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['risk-behavior-records', access.corp.id] }); void queryClient.invalidateQueries({ queryKey: ['risk-behavior-rules', access.corp.id] }); void scanner.refetch(); };
  const fallbackRecord = useMemo(() => selectedID === null ? undefined : records.data?.items.find((item) => item.id === selectedID), [records.data, selectedID]);
  const openDetail = (record: RiskRecord) => { setSelectedID(record.id); const next = new URLSearchParams(params); next.set('matchId', String(record.id)); setParams(next); };
  const closeDetail = () => { setSelectedID(null); const next = new URLSearchParams(params); next.delete('matchId'); setParams(next); };
  const updateDraft = (key: keyof RiskRecordFilters, value: string) => setDraft((current) => ({ ...current, [key]: value, page: 1 }));
  const audit = async (action: 'confirmed' | 'ignored') => { if (!checked.size) return; await api.audit({ ids: [...checked], action, remark: '' }); setChecked(new Set()); await records.refetch(); };
  return <RiskWarningShell className="risk-behavior-page"><RiskWarningPageHeader title="风险行为" meta="按真实会话风险记录进行识别、复核和规则维护。" /><RiskWarningTabs active={tab} tabs={[{ id: 'records', label: '风险记录' }, { id: 'rules', label: '规则配置' }]} onChange={setTab} />
    <RiskWarningQueryBar fetching={records.isFetching || rules.isFetching} onQuery={submit} onReset={reset} onRefresh={refresh}>{tab === 'records' ? <><label>风险等级<select aria-label="风险等级" value={draft.riskLevel ?? ''} onChange={(event) => updateDraft('riskLevel', event.target.value)}><option value="">全部</option><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option></select></label><label>风险行为<select aria-label="风险行为" value={draft.behavior ?? ''} onChange={(event) => updateDraft('behavior', event.target.value)}><option value="">全部</option><option value="private_transaction">私下交易</option><option value="promise_rebate">承诺返利</option><option value="sensitive_word">敏感词</option></select></label><label>审核状态<select aria-label="审核状态" value={draft.auditStatus ?? ''} onChange={(event) => updateDraft('auditStatus', event.target.value)}><option value="">全部</option><option value="pending">待审核</option><option value="confirmed">已确认</option><option value="ignored">已忽略</option><option value="reviewed">已复核</option></select></label><label>会话类型<select aria-label="会话类型" value={draft.conversationType ?? ''} onChange={(event) => updateDraft('conversationType', event.target.value)}><option value="">全部</option><option value="customer">客户会话</option><option value="group">客户群</option></select></label></> : <label>规则名称<input aria-label="规则名称" value={ruleNameDraft} onChange={(event) => setRuleNameDraft(event.target.value)} placeholder="输入规则名称后点击查询" /></label>}</RiskWarningQueryBar>
    <ScannerStatusStrip status={scanner.data} />
    <div className="risk-warning-results"><div className="risk-warning-results-header"><div><h2>{tab === 'records' ? '风险记录' : '规则配置'}</h2><p>{tab === 'records' ? '列表和汇总与当前筛选使用同一真实数据口径。' : '只维护已经接入的文本匹配规则。'}</p></div>{tab === 'rules' ? <button type="button" className="risk-warning-primary-button" onClick={() => { const next = new URLSearchParams(params); next.set('newRule', '1'); setParams(next); }}>新增规则</button> : null}</div>{tab === 'records' ? <RiskBehaviorRecords page={records.data} loading={records.isPending} error={records.error} checked={checked} onChecked={(id, value) => setChecked((current) => { const next = new Set(current); if (value) next.add(id); else next.delete(id); return next; })} onOpen={openDetail} onPageChange={(page) => { const next = { ...applied, page }; setApplied(next); setParams(writeFilters(new URLSearchParams(params), next)); }} onRetry={() => void records.refetch()} onAudit={audit} /> : <RiskBehaviorRules api={api} page={rules.data} loading={rules.isPending} error={rules.error} onChanged={refresh} onPageChange={(page) => { const next = new URLSearchParams(params); next.set('rulePage', String(page)); setParams(next); }} onRetry={() => void rules.refetch()} createOpen={params.get('newRule') === '1'} onCreateClose={() => { const next = new URLSearchParams(params); next.delete('newRule'); setParams(next); }} />}</div>
    <RiskWarningDrawer open={selectedID !== null} title="风险详情" {...(selectedID ? { description: `记录 #${selectedID}` } : {})} onClose={closeDetail}><RiskBehaviorDetail detail={detail.data ?? (fallbackRecord ? { record: fallbackRecord, audits: [], conversationAvailable: false } : undefined)} loading={detail.isPending && !fallbackRecord} error={fallbackRecord ? undefined : detail.error} onRetry={() => void detail.refetch()} {...(fallbackRecord && detail.error ? { supplementalError: detail.error } : {})} /></RiskWarningDrawer>
  </RiskWarningShell>;
}
