import { DashboardPagination } from '../../components/dashboard-pagination';
import { PageState } from '../../components/page-state/page-state';
import type { RiskRecord, RiskRecordPage } from './risk-behavior-api';
import { auditStatusLabel, conversationTypeLabel, formatRiskDateTime, riskBehaviorLabel, riskLevelLabel } from '../risk-warning/risk-warning-format';

function levelClass(level: string): string { return level === 'high' ? 'risk-warning-pill risk-warning-pill-high' : level === 'medium' ? 'risk-warning-pill risk-warning-pill-medium' : level === 'low' ? 'risk-warning-pill risk-warning-pill-low' : 'risk-warning-pill risk-warning-pill-neutral'; }
function relatedName(record: RiskRecord): string { const value = record.relatedUser.name ?? record.relatedUser.employeeName ?? record.relatedUser.customerName ?? record.relatedUser.roomName; return typeof value === 'string' && value.trim() ? value : '未标注对象'; }

export function RiskBehaviorRecords({ page, loading, error, checked, onChecked, onOpen, onPageChange, onRetry, onAudit }: { page: RiskRecordPage | undefined; loading: boolean; error: unknown; checked: Set<number>; onChecked: (id: number, checked: boolean) => void; onOpen: (record: RiskRecord) => void; onPageChange: (page: number) => void; onRetry: () => void; onAudit: (action: 'confirmed' | 'ignored') => void }) {
  if (loading && !page) return <PageState state="loading" />;
  if (error && !page) return <PageState state="error" onRetry={onRetry} />;
  if (!page || page.items.length === 0) return <PageState state="empty" />;
  return <><>{page.summary ? <div className="risk-warning-summary"><div className="risk-warning-summary-item"><span>当前筛选记录</span><strong>{page.summary.total}</strong></div><div className="risk-warning-summary-item"><span>待审核</span><strong>{page.summary.pending}</strong></div><div className="risk-warning-summary-item"><span>高风险</span><strong>{page.summary.highRisk}</strong></div><div className="risk-warning-summary-item"><span>已处置</span><strong>{page.summary.processed}</strong></div></div> : <div className="risk-warning-status-strip">当前接口未返回汇总，无法判断总量；列表数据仍按真实记录展示。</div>}</><div className="risk-warning-batch-bar">{checked.size > 0 ? <><span>已选 {checked.size} 条</span><button type="button" onClick={() => onAudit('confirmed')}>确认风险</button><button type="button" onClick={() => onAudit('ignored')}>忽略</button></> : null}</div><div className="risk-warning-table-wrap"><table className="risk-warning-table"><thead><tr><th>选择</th><th>风险行为</th><th>等级</th><th>关联对象</th><th>会话类型</th><th>触发内容</th><th>审核状态</th><th>发生时间</th><th>操作</th></tr></thead><tbody>{page.items.map((row) => <tr key={row.id} onClick={(event) => { if ((event.target as HTMLElement).closest('input,button,a,select')) return; onOpen(row); }}><td className="risk-warning-row-control"><input type="checkbox" aria-label={`选择记录 ${row.id}`} checked={checked.has(row.id)} onChange={(event) => onChecked(row.id, event.target.checked)} /></td><td>{riskBehaviorLabel(row.behavior)}</td><td><span className={levelClass(row.riskLevel)}>{riskLevelLabel(row.riskLevel)}</span></td><td>{relatedName(row)}</td><td>{conversationTypeLabel(row.conversationType)}</td><td><span className="risk-warning-inline-preview" title={row.triggerMessage}>{row.triggerMessage || '暂无触发内容'}</span></td><td>{auditStatusLabel(row.auditStatus)}</td><td>{formatRiskDateTime(row.occurredAt)}</td><td className="risk-warning-row-control"><button type="button" onClick={() => onOpen(row)}>查看详情</button></td></tr>)}</tbody></table></div><div className="risk-warning-pagination"><DashboardPagination page={page.page} pageSize={20} total={page.total} onPageChange={onPageChange} ariaLabel="风险记录分页" /></div></>;
}
