import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { useDashboardAccess } from '../../app/access-context';
import { pageStateForError, PageState } from '../../components/page-state/page-state';
import type { BusinessWorkbenchApi } from '../business-workbench/business-workbench-page';

type Row = Record<string, unknown>;
function rows(value: unknown): Row[] { if (Array.isArray(value)) return value.filter((v): v is Row => !!v && typeof v === 'object'); if (!value || typeof value !== 'object') return []; const v=value as Row; const b=v.data&&typeof v.data==='object'?v.data as Row:v; const list=[b.items,b.list,b.rows].find(Array.isArray); return Array.isArray(list)?list.filter((x):x is Row=>!!x&&typeof x==='object'):[]; }
function text(value: unknown): string { return value == null || value === '' ? '--' : typeof value === 'object' ? JSON.stringify(value) : String(value); }
const fieldLabels: Record<string,string> = {id:'ID',ruleId:'规则 ID',strategyId:'策略 ID',name:'规则名称',status:'状态',subject:'识别对象',aiInsightEnabled:'AI 分析',triggerCount:'触发次数',behavior:'风险行为',riskLevel:'风险等级',conversationType:'会话类型',conversationId:'会话 ID',messageId:'消息 ID',triggerMessage:'触发内容',relatedUser:'关联用户',aiSummary:'AI 摘要',auditStatus:'审核状态',occurredAt:'发生时间',tenantId:'租户 ID',corpId:'企业 ID'};
const valueLabels: Record<string,string> = {enabled:'启用',disabled:'停用',employee:'员工',customer:'客户',both:'员工与客户',low:'低风险',medium:'中风险',high:'高风险',single:'单聊',group:'群聊',pending:'待审核',confirmed:'已确认',ignored:'已忽略',keyword:'关键词命中',true:'是',false:'否'};
function displayValue(value: unknown): string { const raw=text(value); return valueLabels[raw]??raw; }

export function RiskBehaviorPage({ api }: { api: BusinessWorkbenchApi }) {
  const access=useDashboardAccess(); const client=useQueryClient();
  const [tab,setTab]=useState<'records'|'rules'>('records'); const [level,setLevel]=useState(''); const [behavior,setBehavior]=useState(''); const [selected,setSelected]=useState<Row|null>(null); const [checked,setChecked]=useState<Set<number>>(new Set());
  const [editing,setEditing]=useState<Row|null>(null); const [name,setName]=useState(''); const [pattern,setPattern]=useState(''); const [riskLevel,setRiskLevel]=useState('medium');
  const query=useQuery({queryKey:['phase33-risk-behavior',access.corp.id,tab,level,behavior],queryFn:()=>api.read(tab==='records'?'/risk/records':'/risk/rules',{page:1,perPage:20,...(level?{riskLevel:level}:{}),...(behavior?{behavior}: {})}),enabled:access.corp.authorized});
  const data=useMemo(()=>rows(query.data),[query.data]); const columns=useMemo(()=>Object.keys(data[0]??{}).filter(k=>!['tenantId','corpId','relatedUser','strategies','whitelist'].includes(k)).slice(0,8),[data]);
  const refresh=()=>client.invalidateQueries({queryKey:['phase33-risk-behavior',access.corp.id]});
  const save=useMutation({mutationFn:()=>api.write('/risk/rules',{...(editing?.id?{id:editing.id}:{}),name,status:String(editing?.status??'enabled'),subject:String(editing?.subject??'employee'),whitelist:[],aiInsightEnabled:true,strategies:[{behavior:'keyword',pattern,notifyType:'none',riskLevel}]},editing?.id?'PUT':'POST'),onSuccess:()=>{setEditing(null);setName('');setPattern('');void refresh();}});
  const status=useMutation({mutationFn:(row:Row)=>api.write('/risk/rules/status',{id:row.id,status:row.status==='enabled'?'disabled':'enabled'},'PUT'),onSuccess:()=>void refresh()});
  const remove=useMutation({mutationFn:(row:Row)=>api.write(`/risk/rules?id=${String(row.id)}`,{},'DELETE'),onSuccess:()=>void refresh()});
  const audit=useMutation({mutationFn:(action:string)=>api.write('/risk/records/audit',{ids:[...checked],action,remark:''}),onSuccess:()=>{setChecked(new Set());void refresh();}});
  const openEditor=(row?:Row)=>{setEditing(row??{});setName(String(row?.name??''));const strategies=Array.isArray(row?.strategies)?row.strategies as Row[]:[];setPattern(String(strategies[0]?.pattern??''));setRiskLevel(String(strategies[0]?.riskLevel??'medium'));};
  return <section className="phase33-risk-warning-page"><header className="phase33-risk-warning-header dashboard-page-header dashboard-data-card"><div><p className="phase33-risk-warning-eyebrow">风险预警</p><h1>风险行为</h1><p>识别和跟进会话中的风险行为。</p></div><button type="button" disabled={query.isFetching} onClick={()=>void query.refetch()}>刷新</button></header>
    <div className="dashboard-tabs"><button type="button" aria-pressed={tab==='records'} onClick={()=>{setTab('records');setSelected(null);}}>风险记录</button><button type="button" aria-pressed={tab==='rules'} onClick={()=>{setTab('rules');setSelected(null);}}>规则配置</button></div>
    {tab==='records'?<div className="dashboard-filter-bar phase33-risk-warning-filters"><label>风险等级<select aria-label="风险等级" value={level} onChange={e=>setLevel(e.target.value)}><option value="">全部</option><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option></select></label><label>风险行为<input aria-label="风险行为" value={behavior} onChange={e=>setBehavior(e.target.value)} placeholder="输入行为名称" /></label><button type="button" onClick={()=>void query.refetch()}>查询</button>{checked.size>0&&<><button type="button" onClick={()=>audit.mutate('confirmed')}>确认风险</button><button type="button" onClick={()=>audit.mutate('ignored')}>忽略</button></>}</div>:<div className="dashboard-filter-bar"><button type="button" onClick={()=>openEditor()}>新增规则</button></div>}
    <div className="dashboard-data-card phase33-risk-warning-results"><div className="dashboard-card-heading"><div><h2>{tab==='records'?'风险记录':'规则配置'}</h2><p>{tab==='records'?'查看已识别的风险行为记录。':'管理风险行为识别规则。'}</p></div></div>{query.isPending?<PageState state="loading"/>:query.isError?<PageState state={pageStateForError(query.error)} onRetry={()=>void query.refetch()}/>:data.length===0?<PageState state="empty"/>:<div className="dashboard-table-scroll"><table><thead><tr>{tab==='records'&&<th>选择</th>}{columns.map(c=><th key={c}>{fieldLabels[c]??c}</th>)}<th>操作</th></tr></thead><tbody>{data.map((row,i)=>{const id=Number(row.id??i);return <tr key={id}>{tab==='records'&&<td><input aria-label={`选择记录 ${id}`} type="checkbox" checked={checked.has(id)} onChange={e=>setChecked(previous=>{const next=new Set(previous);e.target.checked?next.add(id):next.delete(id);return next;})}/></td>}{columns.map(c=><td key={c}>{displayValue(row[c])}</td>)}<td>{tab==='records'?<button type="button" onClick={()=>setSelected(row)}>详情</button>:<><button type="button" onClick={()=>openEditor(row)}>编辑</button><button type="button" onClick={()=>status.mutate(row)}>{row.status==='enabled'?'停用':'启用'}</button><button type="button" onClick={()=>remove.mutate(row)}>删除</button></>}</td></tr>})}</tbody></table></div>}</div>
    {editing&&<aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="风险规则编辑"><div className="dashboard-card-heading"><div><h2>{editing.id?'编辑规则':'新增规则'}</h2></div><button type="button" onClick={()=>setEditing(null)}>关闭</button></div><div className="dashboard-filter-bar"><label>规则名称<input aria-label="规则名称" value={name} onChange={e=>setName(e.target.value)}/></label><label>匹配关键词<input aria-label="匹配关键词" value={pattern} onChange={e=>setPattern(e.target.value)}/></label><label>风险等级<select aria-label="规则风险等级" value={riskLevel} onChange={e=>setRiskLevel(e.target.value)}><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option></select></label><button type="button" disabled={!name.trim()||!pattern.trim()||save.isPending} onClick={()=>save.mutate()}>保存</button></div></aside>}
    {selected&&<aside className="phase33-risk-warning-detail dashboard-data-card"><div className="dashboard-card-heading"><div><h2>风险详情</h2><p>查看当前记录的完整信息。</p></div><button type="button" onClick={()=>setSelected(null)}>关闭</button></div><dl>{Object.entries(selected).map(([k,v])=><div key={k}><dt>{fieldLabels[k]??k}</dt><dd>{displayValue(v)}</dd></div>)}</dl></aside>}
  </section>;
}
