import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';

import { useDashboardAccess } from '../../app/access-context';
import { ConfirmAction } from '../../components/confirm-action';
import { DashboardPagination } from '../../components/dashboard-pagination';
import { PageState, pageStateForError } from '../../components/page-state/page-state';
import { RiskWarningDrawer, RiskWarningPageHeader, RiskWarningQueryBar, RiskWarningShell, RiskWarningTabs } from '../risk-warning/risk-warning-shell';
import type { SilentCustomerApi, SilentCustomerRecord, SilentCustomerRule } from './silent-customer-api';

const recordDefault = { customer: '', status: '', assignedEmployeeId: 0, page: 1, perPage: 20 };
const ruleDefault = { name: '', status: '', page: 1, perPage: 20 };
const statusLabel: Record<string, string> = { pending: '待跟进', assigned: '已分派', followed: '已跟进', awakened: '已唤醒', closed: '已关闭', ignored: '已忽略', enabled: '启用', disabled: '停用' };
function readRecordFilter(params: URLSearchParams) { return { customer: params.get('customer') ?? '', status: params.get('status') ?? '', assignedEmployeeId: Number(params.get('assignedEmployeeId') ?? 0) || 0, page: Number(params.get('page') ?? 1) || 1, perPage: 20 }; }
function writeRecordFilter(params: URLSearchParams, filter: typeof recordDefault) { const next = new URLSearchParams(params); ['customer', 'status', 'assignedEmployeeId', 'page'].forEach((key) => next.delete(key)); if (filter.customer) next.set('customer', filter.customer); if (filter.status) next.set('status', filter.status); if (filter.assignedEmployeeId > 0) next.set('assignedEmployeeId', String(filter.assignedEmployeeId)); if (filter.page > 1) next.set('page', String(filter.page)); return next; }
function readRuleFilter(params: URLSearchParams) { return { name: params.get('ruleName') ?? '', status: params.get('ruleStatus') ?? '', page: Number(params.get('rulePage') ?? 1) || 1, perPage: 20 }; }
function writeRuleFilter(params: URLSearchParams, filter: typeof ruleDefault) { const next = new URLSearchParams(params); ['ruleName', 'ruleStatus', 'rulePage'].forEach((key) => next.delete(key)); if (filter.name) next.set('ruleName', filter.name); if (filter.status) next.set('ruleStatus', filter.status); if (filter.page > 1) next.set('rulePage', String(filter.page)); return next; }
const dateText = (value: string) => value ? value.replace('T', ' ').replace(/Z$/, '') : '--';
function mutationMessage(error: unknown): string { return error instanceof Error && error.message ? error.message : '操作未完成，请刷新后重试。'; }

export function SilentCustomerPage({ api }: { api: SilentCustomerApi }) {
  const access = useDashboardAccess();
  const queryClient = useQueryClient();
  const location = useLocation();
  const navigate = useNavigate();
  const params = useMemo(() => new URLSearchParams(location.search), [location.search]);
  const setParams = (next: URLSearchParams) => { void navigate({ search: next.toString() ? `?${next.toString()}` : '' }); };
  const tab = params.get('tab') === 'rules' ? 'rules' : 'records';
  const recordFilter = useMemo(() => readRecordFilter(params), [params]);
  const ruleFilter = useMemo(() => readRuleFilter(params), [params]);
  const [recordDraft, setRecordDraft] = useState(recordFilter);
  const [ruleDraft, setRuleDraft] = useState(ruleFilter);
  const [checked, setChecked] = useState<Set<number>>(new Set());
  const [assignee, setAssignee] = useState(0);
  const [remark, setRemark] = useState('');
  const [feedback, setFeedback] = useState<{ kind: 'success' | 'error'; text: string } | null>(null);
  const [editingRule, setEditingRule] = useState<SilentCustomerRule | null>(null);
  const [ruleName, setRuleName] = useState('');
  const [silentDays, setSilentDays] = useState(30);
  const selectedId = Number(params.get('recordId') ?? 0) || null;
  const editorOpen = params.get('ruleEditor') === '1';
  const editingRuleId = Number(params.get('ruleId') ?? 0) || null;
  const records = useQuery({ queryKey: ['silent-customer-records', access.corp.id, recordFilter], queryFn: () => api.records(recordFilter), enabled: access.corp.authorized && tab === 'records', retry: false });
  const rules = useQuery({ queryKey: ['silent-customer-rules', access.corp.id, ruleFilter], queryFn: () => api.rules(ruleFilter), enabled: access.corp.authorized && tab === 'rules', retry: false });
  const staff = useQuery({ queryKey: ['silent-customer-staff', access.corp.id], queryFn: () => api.staffOptions(''), enabled: access.corp.authorized && tab === 'records', retry: false });
  const selectedRecord = records.data?.items.find((item) => item.id === selectedId) ?? null;
  const selectedRule = rules.data?.items.find((item) => item.id === editingRuleId) ?? null;
  useEffect(() => {
    if (!editorOpen || !editingRuleId || !selectedRule || editingRule?.id === selectedRule.id) return;
    setEditingRule(selectedRule);
    setRuleName(selectedRule.name);
    setSilentDays(selectedRule.silentDays);
  }, [editorOpen, editingRule, editingRuleId, selectedRule]);
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ['silent-customer-records', access.corp.id] }); void queryClient.invalidateQueries({ queryKey: ['silent-customer-rules', access.corp.id] }); };
  const setTab = (next: string) => { const value = new URLSearchParams(params); value.set('tab', next); value.delete('recordId'); value.delete('ruleEditor'); setParams(value); setChecked(new Set()); };
  const queryRecords = () => { const next = { ...recordDraft, customer: recordDraft.customer.trim(), page: 1 }; setRecordDraft(next); setParams(writeRecordFilter(new URLSearchParams(params), next)); setChecked(new Set()); };
  const resetRecords = () => { const next = { ...recordDefault }; setRecordDraft(next); setParams(writeRecordFilter(new URLSearchParams(params), next)); setChecked(new Set()); };
  const queryRules = () => { const next = { ...ruleDraft, name: ruleDraft.name.trim(), page: 1 }; setRuleDraft(next); setParams(writeRuleFilter(new URLSearchParams(params), next)); };
  const resetRules = () => { const next = { ...ruleDefault }; setRuleDraft(next); setParams(writeRuleFilter(new URLSearchParams(params), next)); };
  const openRecord = (item: SilentCustomerRecord) => { const next = new URLSearchParams(params); next.set('recordId', String(item.id)); setParams(next); };
  const closeRecord = () => { const next = new URLSearchParams(params); next.delete('recordId'); setParams(next); };
  const openRuleEditor = (item?: SilentCustomerRule) => { const next = new URLSearchParams(params); next.set('ruleEditor', '1'); if (item) next.set('ruleId', String(item.id)); else next.delete('ruleId'); setParams(next); setEditingRule(item ?? null); setRuleName(item?.name ?? ''); setSilentDays(item?.silentDays ?? 30); };
  const closeRuleEditor = () => { const next = new URLSearchParams(params); next.delete('ruleEditor'); next.delete('ruleId'); setParams(next); setEditingRule(null); };
  const saveRule = useMutation({ mutationFn: () => api.write('/silent-customer/rules', { ...(editingRule ? { id: editingRule.id } : {}), name: ruleName.trim(), silentDays, status: editingRule?.status ?? 'enabled' }, editingRule ? 'PUT' : 'POST'), onSuccess: () => { closeRuleEditor(); setFeedback({ kind: 'success', text: '沉默规则已保存。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const toggleRule = useMutation({ mutationFn: (item: SilentCustomerRule) => api.write('/silent-customer/rules/status', { id: item.id, status: item.status === 'enabled' ? 'disabled' : 'enabled' }, 'PUT'), onSuccess: () => { setFeedback({ kind: 'success', text: '规则状态已更新。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const deleteRule = useMutation({ mutationFn: (item: SilentCustomerRule) => api.write(`/silent-customer/rules?id=${item.id}`, {}, 'DELETE'), onSuccess: () => { setFeedback({ kind: 'success', text: '沉默规则已删除。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const action = useMutation({ mutationFn: (value: { action: string; assignedEmployeeId?: number }) => api.write('/silent-customer/records/action', { ids: [...checked], action: value.action, assignedEmployeeId: value.assignedEmployeeId ?? 0, remark: remark.trim() }), onSuccess: () => { setChecked(new Set()); setAssignee(0); setRemark(''); setFeedback({ kind: 'success', text: '沉默客户处置已更新。' }); refresh(); }, onError: (error) => setFeedback({ kind: 'error', text: mutationMessage(error) }) });
  const updateRecordDraft = (key: keyof typeof recordDefault, value: string | number) => setRecordDraft((current) => ({ ...current, [key]: value, page: 1 }));
  const updateRuleDraft = (key: keyof typeof ruleDefault, value: string) => setRuleDraft((current) => ({ ...current, [key]: value, page: 1 }));
  return <RiskWarningShell className="silent-customer-page">
    <RiskWarningPageHeader eyebrow="风险预警" title="沉默客户" meta="按真实客户互动时间识别沉默记录，分派跟进并留下处置结果。" />
    <RiskWarningTabs active={tab} tabs={[{ id: 'records', label: '沉默记录' }, { id: 'rules', label: '规则配置' }]} onChange={setTab} />
    <RiskWarningQueryBar fetching={records.isFetching || rules.isFetching} onQuery={tab === 'records' ? queryRecords : queryRules} onReset={tab === 'records' ? resetRecords : resetRules} onRefresh={refresh}>{tab === 'records' ? <><label>客户<input aria-label="客户" placeholder="客户名称或 ID" value={recordDraft.customer} onChange={(event) => updateRecordDraft('customer', event.target.value)} /></label><label>沉默状态<select aria-label="沉默状态" value={recordDraft.status} onChange={(event) => updateRecordDraft('status', event.target.value)}><option value="">全部</option><option value="pending">待跟进</option><option value="assigned">已分派</option><option value="followed">已跟进</option><option value="awakened">已唤醒</option><option value="closed">已关闭</option></select></label><label>负责人<select aria-label="负责人" value={recordDraft.assignedEmployeeId || ''} onChange={(event) => updateRecordDraft('assignedEmployeeId', Number(event.target.value) || 0)}><option value="">全部</option>{(staff.data ?? []).map((item) => <option key={item.id} value={item.id}>{item.name}{item.departments.length ? ` · ${item.departments.join('、')}` : ''}</option>)}</select></label></> : <><label>规则名称<input aria-label="规则名称" placeholder="输入规则名称" value={ruleDraft.name} onChange={(event) => updateRuleDraft('name', event.target.value)} /></label><label>状态<select aria-label="规则状态" value={ruleDraft.status} onChange={(event) => updateRuleDraft('status', event.target.value)}><option value="">全部</option><option value="enabled">启用</option><option value="disabled">停用</option></select></label></>}</RiskWarningQueryBar>
    {feedback ? <p className="risk-warning-inline-feedback" role={feedback.kind === 'error' ? 'alert' : 'status'}>{feedback.text}</p> : null}
    <div className="risk-warning-results"><div className="risk-warning-results-header"><div><h2>{tab === 'records' ? '沉默记录' : '规则配置'}</h2><p>{tab === 'records' ? '记录来自客户活跃度评估；页面操作会写回真实处置状态。' : '配置客户连续无互动的判定窗口。'}</p></div>{tab === 'rules' ? <button type="button" className="risk-warning-primary-button" onClick={() => openRuleEditor()}>新增规则</button> : null}</div>{tab === 'records' ? <SilentRecordTable page={records.data} loading={records.isPending} error={records.error} checked={checked} onChecked={(id, value) => setChecked((current) => { const next = new Set(current); if (value) next.add(id); else next.delete(id); return next; })} onOpen={openRecord} onPageChange={(page) => setParams(writeRecordFilter(new URLSearchParams(params), { ...recordFilter, page }))} onRetry={() => void records.refetch()} /> : <SilentRuleTable page={rules.data} loading={rules.isPending} error={rules.error} onOpen={openRuleEditor} onToggle={(item) => toggleRule.mutate(item)} onDelete={(item) => deleteRule.mutate(item)} onPageChange={(page) => setParams(writeRuleFilter(new URLSearchParams(params), { ...ruleFilter, page }))} onRetry={() => void rules.refetch()} />}</div>
    {tab === 'records' && checked.size > 0 ? <div className="risk-warning-batch-bar silent-customer-batch-bar"><span>已选 {checked.size} 条</span><label>分派给<select aria-label="分派员工" value={assignee || ''} onChange={(event) => setAssignee(Number(event.target.value) || 0)}><option value="">请选择员工</option>{(staff.data ?? []).map((item) => <option key={item.id} value={item.id}>{item.name}{item.departments.length ? ` · ${item.departments.join('、')}` : ''}</option>)}</select></label><label>处置备注<input aria-label="处置备注" value={remark} onChange={(event) => setRemark(event.target.value)} placeholder="可选" /></label><ConfirmAction title="确认分派选中的沉默客户？" onConfirm={() => action.mutate({ action: 'assign', assignedEmployeeId: assignee })}><button type="button" disabled={!assignee || action.isPending}>分派</button></ConfirmAction><ConfirmAction title="确认将选中记录标记为已跟进？" onConfirm={() => action.mutate({ action: 'followed' })}><button type="button" disabled={action.isPending}>已跟进</button></ConfirmAction><ConfirmAction title="确认将选中记录标记为已唤醒？" onConfirm={() => action.mutate({ action: 'awakened' })}><button type="button" disabled={action.isPending}>已唤醒</button></ConfirmAction><ConfirmAction title="确认关闭选中的沉默记录？" onConfirm={() => action.mutate({ action: 'closed' })}><button type="button" disabled={action.isPending}>关闭</button></ConfirmAction></div> : null}
    <RiskWarningDrawer open={selectedRecord !== null} title="沉默客户详情" {...(selectedRecord ? { description: `记录 #${selectedRecord.id}` } : {})} onClose={closeRecord}>{selectedRecord ? <dl className="risk-warning-detail-grid"><div><dt>客户</dt><dd>{selectedRecord.customerName || selectedRecord.customerId}</dd></div><div><dt>当前负责人</dt><dd>{selectedRecord.assignedEmployeeName || selectedRecord.employeeName || '未分派'}</dd></div><div><dt>最后互动</dt><dd>{dateText(selectedRecord.lastInteractionAt)}</dd></div><div><dt>沉默天数</dt><dd>{selectedRecord.silentDays} 天</dd></div><div><dt>当前状态</dt><dd>{statusLabel[selectedRecord.status] ?? selectedRecord.status}</dd></div><div><dt>处置备注</dt><dd>{selectedRecord.followUpNote || '暂无备注'}</dd></div></dl> : null}</RiskWarningDrawer>
    <RiskWarningDrawer open={editorOpen} title={editingRule ? '编辑沉默规则' : '新增沉默规则'} description="规则保存后由评估任务生成沉默记录。" onClose={closeRuleEditor}><form className="risk-warning-form" onSubmit={(event) => { event.preventDefault(); if (ruleName.trim() && silentDays >= 1 && silentDays <= 365) saveRule.mutate(); }}><label>规则名称<input aria-label="编辑规则名称" value={ruleName} onChange={(event) => setRuleName(event.target.value)} autoFocus /></label><label>连续无互动天数<input aria-label="沉默天数" type="number" min={1} max={365} value={silentDays} onChange={(event) => setSilentDays(Number(event.target.value) || 0)} /></label><p className="risk-warning-form-note">只根据同步到系统的客户互动时间判断，不展示无法追溯来源的统计。</p><div className="risk-warning-drawer-actions"><button type="button" className="risk-warning-secondary-button" onClick={closeRuleEditor}>取消</button><button type="button" className="risk-warning-primary-button" disabled={!ruleName.trim() || silentDays < 1 || silentDays > 365 || saveRule.isPending} onClick={() => saveRule.mutate()}>保存</button></div></form></RiskWarningDrawer>
  </RiskWarningShell>;
}

function SilentRecordTable({ page, loading, error, checked, onChecked, onOpen, onPageChange, onRetry }: { page: { items: SilentCustomerRecord[]; total: number; page: number; perPage: number } | undefined; loading: boolean; error: unknown; checked: Set<number>; onChecked: (id: number, value: boolean) => void; onOpen: (record: SilentCustomerRecord) => void; onPageChange: (page: number) => void; onRetry: () => void }) {
  if (loading && !page) return <PageState state="loading" />;
  if (error && !page) return <PageState state={pageStateForError(error)} onRetry={onRetry} />;
  if (!page || page.items.length === 0) return <PageState state="empty" title="暂无沉默客户" description="当前筛选下没有需要跟进的沉默记录。" />;
  return <><div className="risk-warning-table-wrap"><table className="risk-warning-table silent-customer-record-table"><thead><tr><th>选择</th><th>客户</th><th>原负责人</th><th>最后互动</th><th>沉默天数</th><th>当前负责人</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{page.items.map((record) => <tr key={record.id} onClick={(event) => { if ((event.target as HTMLElement).closest('input,button,a,select')) return; onOpen(record); }}><td className="risk-warning-row-control"><input type="checkbox" aria-label={`选择记录 ${record.id}`} checked={checked.has(record.id)} onChange={(event) => onChecked(record.id, event.target.checked)} /></td><td>{record.customerName || record.customerId}</td><td>{record.employeeName || '未标注'}</td><td>{dateText(record.lastInteractionAt)}</td><td><span className="risk-warning-pill risk-warning-pill-medium">{record.silentDays} 天</span></td><td>{record.assignedEmployeeName || '未分派'}</td><td>{statusLabel[record.status] ?? record.status}</td><td>{dateText(record.updatedAt)}</td><td className="risk-warning-row-control"><button type="button" onClick={() => onOpen(record)}>查看详情</button></td></tr>)}</tbody></table></div><div className="risk-warning-pagination"><DashboardPagination page={page.page} pageSize={20} total={page.total} onPageChange={onPageChange} ariaLabel="沉默客户分页" /></div></>;
}

function SilentRuleTable({ page, loading, error, onOpen, onToggle, onDelete, onPageChange, onRetry }: { page: { items: SilentCustomerRule[]; total: number; page: number; perPage: number } | undefined; loading: boolean; error: unknown; onOpen: (rule: SilentCustomerRule) => void; onToggle: (rule: SilentCustomerRule) => void; onDelete: (rule: SilentCustomerRule) => void; onPageChange: (page: number) => void; onRetry: () => void }) {
  if (loading && !page) return <PageState state="loading" />;
  if (error && !page) return <PageState state={pageStateForError(error)} onRetry={onRetry} />;
  if (!page || page.items.length === 0) return <PageState state="empty" title="暂无沉默规则" description="新增规则后系统才会持续评估沉默客户。" />;
  return <><div className="risk-warning-table-wrap"><table className="risk-warning-table silent-customer-rule-table"><thead><tr><th>规则名称</th><th>沉默阈值</th><th>命中次数</th><th>状态</th><th>最后编辑</th><th>操作</th></tr></thead><tbody>{page.items.map((rule) => <tr key={rule.id}><td>{rule.name || '未命名规则'}</td><td>{rule.silentDays} 天</td><td>{rule.triggerCount}</td><td>{statusLabel[rule.status] ?? rule.status}</td><td>{dateText(rule.updatedAt)}</td><td className="sensitive-word-row-actions"><button type="button" onClick={() => onOpen(rule)}>编辑</button><ConfirmAction title={`确认${rule.status === 'enabled' ? '停用' : '启用'}规则“${rule.name}”？`} onConfirm={() => onToggle(rule)}><button type="button" aria-label={`${rule.status === 'enabled' ? '停用' : '启用'} ${rule.name}`}>{rule.status === 'enabled' ? '停用' : '启用'}</button></ConfirmAction><ConfirmAction title={`确认删除规则“${rule.name}”？`} description="删除后无法恢复。" onConfirm={() => onDelete(rule)}><button type="button" aria-label={`删除 ${rule.name}`}>删除</button></ConfirmAction></td></tr>)}</tbody></table></div><div className="risk-warning-pagination"><DashboardPagination page={page.page} pageSize={20} total={page.total} onPageChange={onPageChange} ariaLabel="沉默规则分页" /></div></>;
}
