import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useMemo, useState } from 'react';
import { useDashboardAccess } from '../../app/access-context';
import { pageStateForError, PageState } from '../../components/page-state/page-state';
import type { BusinessWorkbenchApi } from '../business-workbench/business-workbench-page';
import { ConfirmAction } from '../../components/confirm-action';

type Row=Record<string,unknown>;
type Strategy={timeoutMinutes:number;notifyType:string;riskLevel:string};
function rows(payload:unknown):Row[]{if(Array.isArray(payload))return payload.filter((v):v is Row=>!!v&&typeof v==='object');if(!payload||typeof payload!=='object')return[];const body=(payload as Row).data&&typeof(payload as Row).data==='object'?(payload as Row).data as Row:payload as Row;const list=[body.items,body.list,body.rows].find(Array.isArray);return Array.isArray(list)?list.filter((v):v is Row=>!!v&&typeof v==='object'):[];}
function str(v:unknown):string{return typeof v==='string'?v:typeof v==='number'||typeof v==='boolean'?String(v):v==null?'':JSON.stringify(v);}
const labels:Record<string,string>={id:'ID',ruleName:'规则',conversationType:'会话类型',customerName:'客户',employeeName:'责任员工',triggerMessage:'触发消息',timeoutSeconds:'超时时长',riskLevel:'风险等级',auditStatus:'处置状态',aiSummary:'AI 摘要',occurredAt:'记录时间',name:'规则名称',monitorTarget:'监听对象',conversationScopes:'监听范围',triggerCount:'触发次数',status:'启用状态',createdAt:'创建时间'};
const values:Record<string,string>={single:'单聊',group:'群聊',low:'低风险',medium:'中风险',high:'高风险',pending:'待处置',confirmed:'已确认',ignored:'已忽略',closed:'已关闭',enabled:'启用',disabled:'停用',all:'全部',employee:'员工',department:'部门',none:'不通知',owner:'通知责任员工',extra:'通知额外人员'};
function show(v:unknown):string{if(Array.isArray(v))return v.map(show).join('、');const raw=str(v);return values[raw]??(raw||'--');}

export function TimeoutWarningPage({api}:{api:BusinessWorkbenchApi}){
 const access=useDashboardAccess();const client=useQueryClient();const [tab,setTab]=useState<'records'|'rules'|'settings'>('records');
 const [customer,setCustomer]=useState('');const [level,setLevel]=useState('');const [conversation,setConversation]=useState('');const [selected,setSelected]=useState<Row|null>(null);const [checked,setChecked]=useState<Set<number>>(new Set());const [assignEmployee,setAssignEmployee]=useState('');
 const [editing,setEditing]=useState<Row|null>(null);const [name,setName]=useState('');const [scopeSingle,setScopeSingle]=useState(true);const [scopeGroup,setScopeGroup]=useState(false);const [strategies,setStrategies]=useState<Strategy[]>([{timeoutMinutes:3,notifyType:'none',riskLevel:'low'}]);
 const [closingPhrases,setClosingPhrases]=useState('');const [whitelistTypes,setWhitelistTypes]=useState('');
 const endpoint=tab==='records'?'/timeout-warning/records':tab==='rules'?'/timeout-warning/rules':'/timeout-warning/settings';
 const query=useQuery({queryKey:['phase33-timeout-warning',access.corp.id,tab,customer,level,conversation],queryFn:()=>api.read(endpoint,tab==='records'?{page:1,perPage:20,...(customer?{customer}:{}),...(level?{riskLevel:level}:{}),...(conversation?{conversationType:conversation}:{})}:tab==='rules'?{page:1,perPage:20}:{}),enabled:access.corp.authorized});
 const data=useMemo(()=>rows(query.data),[query.data]);
 const refresh=()=>client.invalidateQueries({queryKey:['phase33-timeout-warning',access.corp.id]});
 const saveRule=useMutation({mutationFn:()=>api.write('/timeout-warning/rules',{...(editing?.id?{id:editing.id}:{}),name,status:str(editing?.status)||'enabled',monitorTarget:'all',monitorTargetIds:[],conversationScopes:[...(scopeSingle?['single']:[]),...(scopeGroup?['group']:[])],aiInsightEnabled:true,strategies:strategies.map((v,i)=>({...v,sortOrder:i})),quietPeriods:[],notifyTargets:[]},editing?.id?'PUT':'POST'),onSuccess:()=>{setEditing(null);void refresh();}});
 const status=useMutation({mutationFn:(row:Row)=>api.write('/timeout-warning/rules/status',{id:row.id,status:row.status==='enabled'?'disabled':'enabled'},'PUT'),onSuccess:()=>void refresh()});
 const remove=useMutation({mutationFn:(row:Row)=>api.write(`/timeout-warning/rules?id=${str(row.id)}`,{},'DELETE'),onSuccess:()=>void refresh()});
 const audit=useMutation({mutationFn:(action:string)=>api.write('/timeout-warning/records/audit',{ids:[...checked],action,remark:''}),onSuccess:()=>{setChecked(new Set());void refresh();}});
 const assign=useMutation({mutationFn:()=>api.write('/timeout-warning/records/assign',{ids:[...checked],employeeId:Number(assignEmployee),remark:''},'PUT'),onSuccess:()=>{setChecked(new Set());setAssignEmployee('');void refresh();}});
 const saveSettings=useMutation({mutationFn:()=>api.write('/timeout-warning/settings',{closingPhraseGroups:closingPhrases.split(';').map(g=>g.split(',').map(v=>v.trim()).filter(Boolean)).filter(g=>g.length>0),whitelistMessageTypes:whitelistTypes.split(',').map(v=>v.trim()).filter(Boolean)},'PUT'),onSuccess:()=>void refresh()});
 const openEditor=(row?:Row)=>{setEditing(row??{});setName(str(row?.name));const scopes=Array.isArray(row?.conversationScopes)?row.conversationScopes.map(str):['single'];setScopeSingle(scopes.includes('single'));setScopeGroup(scopes.includes('group'));const source=Array.isArray(row?.strategies)?row.strategies as Row[]:[];setStrategies(source.length?source.map(v=>({timeoutMinutes:Number(v.timeoutMinutes)||3,notifyType:str(v.notifyType)||'none',riskLevel:str(v.riskLevel)||'low'})):[{timeoutMinutes:3,notifyType:'none',riskLevel:'low'}]);};
 const recordColumns=['id','customerName','employeeName','conversationType','timeoutSeconds','riskLevel','ruleName','auditStatus'];const ruleColumns=['id','name','monitorTarget','conversationScopes','triggerCount','status','createdAt'];
 return <section className="phase33-risk-warning-page"><header className="phase33-risk-warning-header dashboard-page-header dashboard-data-card"><div><p className="phase33-risk-warning-eyebrow">风险预警</p><h1>超时预警</h1><p>配置响应时效规则，跟进并处置客户消息超时记录。</p></div><button type="button" disabled={query.isFetching} onClick={()=>void query.refetch()}>刷新</button></header>
  <div className="dashboard-tabs"><button type="button" aria-pressed={tab==='records'} onClick={()=>{setTab('records');setSelected(null);}}>超时记录</button><button type="button" aria-pressed={tab==='rules'} onClick={()=>{setTab('rules');setSelected(null);}}>规则配置</button><button type="button" aria-pressed={tab==='settings'} onClick={()=>{setTab('settings');setSelected(null);}}>高级设置</button></div>
  {tab==='records'&&<div className="dashboard-filter-bar phase33-risk-warning-filters"><label>客户<input aria-label="客户" value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="客户名称或 ID"/></label><label>风险等级<select aria-label="风险等级" value={level} onChange={e=>setLevel(e.target.value)}><option value="">全部</option><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option></select></label><label>会话类型<select aria-label="会话类型" value={conversation} onChange={e=>setConversation(e.target.value)}><option value="">全部</option><option value="single">单聊</option><option value="group">群聊</option></select></label><button type="button" onClick={()=>void query.refetch()}>查询</button>{checked.size>0&&<><button type="button" onClick={()=>audit.mutate('confirmed')}>确认超时</button><button type="button" onClick={()=>audit.mutate('ignored')}>忽略</button><button type="button" onClick={()=>audit.mutate('closed')}>关闭</button><label>分派员工 ID<input aria-label="分派员工 ID" inputMode="numeric" value={assignEmployee} onChange={e=>setAssignEmployee(e.target.value)}/></label><button type="button" disabled={Number(assignEmployee)<=0} onClick={()=>assign.mutate()}>分派</button></>}</div>}
  {tab==='rules'&&<div className="dashboard-filter-bar"><button type="button" onClick={()=>openEditor()}>新增规则</button></div>}
  {tab==='settings'?<SettingsPanel queryData={query.data} closingPhrases={closingPhrases} whitelistTypes={whitelistTypes} onClosing={setClosingPhrases} onWhitelist={setWhitelistTypes} onLoad={(groups,types)=>{setClosingPhrases(groups);setWhitelistTypes(types);}} onSave={()=>saveSettings.mutate()} pending={saveSettings.isPending}/>:<div className="dashboard-data-card phase33-risk-warning-results"><div className="dashboard-card-heading"><div><h2>{tab==='records'?'超时记录':'规则配置'}</h2><p>{tab==='records'?'查看已识别的客户消息超时记录。':'管理监听范围和分级超时策略。'}</p></div></div>{query.isPending?<PageState state="loading"/>:query.isError?<PageState state={pageStateForError(query.error)} onRetry={()=>void query.refetch()}/>:data.length===0?<PageState state="empty"/>:<div className="dashboard-table-scroll"><table><thead><tr>{tab==='records'&&<th>选择</th>}{(tab==='records'?recordColumns:ruleColumns).map(c=><th key={c}>{labels[c]??c}</th>)}<th>操作</th></tr></thead><tbody>{data.map((row,i)=>{const id=Number(row.id??i);const target=str(row.name)||`${id}`;return <tr key={id}>{tab==='records'&&<td><input type="checkbox" aria-label={`选择记录 ${id}`} checked={checked.has(id)} onChange={e=>setChecked(old=>{const next=new Set(old);if(e.target.checked)next.add(id);else next.delete(id);return next;})}/></td>}{(tab==='records'?recordColumns:ruleColumns).map(c=><td key={c}>{c==='timeoutSeconds'?`${Math.floor(Number(row[c]??0)/60)} 分钟`:show(row[c])}</td>)}<td>{tab==='records'?<button type="button" onClick={()=>setSelected(row)}>详情</button>:<><button type="button" onClick={()=>openEditor(row)}>编辑</button><ConfirmAction title={row.status==='enabled'?`确认停用规则“${target}”？`:`确认启用规则“${target}”？`} onConfirm={()=>status.mutate(row)}><button type="button">{row.status==='enabled'?`停用 ${target}`:`启用 ${target}`}</button></ConfirmAction><ConfirmAction title={`确认删除规则“${target}”？`} onConfirm={()=>remove.mutate(row)}><button type="button">{`删除 ${target}`}</button></ConfirmAction></>}</td></tr>})}</tbody></table></div>}</div>}
  {editing&&<RuleEditor name={name} setName={setName} scopeSingle={scopeSingle} setScopeSingle={setScopeSingle} scopeGroup={scopeGroup} setScopeGroup={setScopeGroup} strategies={strategies} setStrategies={setStrategies} editing={editing} onClose={()=>setEditing(null)} onSave={()=>saveRule.mutate()} pending={saveRule.isPending}/>} 
  {selected&&<aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="超时详情"><div className="dashboard-card-heading"><div><h2>超时详情</h2><p>查看当前记录的完整信息。</p></div><button type="button" onClick={()=>setSelected(null)}>关闭</button></div><dl>{Object.entries(selected).map(([k,v])=><div key={k}><dt>{labels[k]??k}</dt><dd>{show(v)}</dd></div>)}</dl></aside>}
 </section>;
}

function RuleEditor(p:{name:string;setName:(v:string)=>void;scopeSingle:boolean;setScopeSingle:(v:boolean)=>void;scopeGroup:boolean;setScopeGroup:(v:boolean)=>void;strategies:Strategy[];setStrategies:(v:Strategy[])=>void;editing:Row;onClose:()=>void;onSave:()=>void;pending:boolean}){return <aside className="phase33-risk-warning-detail dashboard-data-card" aria-label="超时规则编辑"><div className="dashboard-card-heading"><h2>{p.editing.id?'编辑规则':'新增规则'}</h2><button type="button" onClick={p.onClose}>关闭</button></div><div className="dashboard-filter-bar"><label>规则名称<input aria-label="规则名称" value={p.name} onChange={e=>p.setName(e.target.value)}/></label><label><input type="checkbox" checked={p.scopeSingle} onChange={e=>p.setScopeSingle(e.target.checked)}/>单聊中客户发言</label><label><input type="checkbox" checked={p.scopeGroup} onChange={e=>p.setScopeGroup(e.target.checked)}/>群聊中客户发言</label></div><div className="dashboard-table-scroll"><table><thead><tr><th>配置时长（分钟）</th><th>通知类型</th><th>风险等级</th><th>操作</th></tr></thead><tbody>{p.strategies.map((v,i)=><tr key={i}><td><input aria-label={`超时时长 ${i+1}`} type="number" min={3} max={180} value={v.timeoutMinutes} onChange={e=>p.setStrategies(p.strategies.map((x,j)=>j===i?{...x,timeoutMinutes:Number(e.target.value)}:x))}/></td><td><select aria-label={`通知类型 ${i+1}`} value={v.notifyType} onChange={e=>p.setStrategies(p.strategies.map((x,j)=>j===i?{...x,notifyType:e.target.value}:x))}><option value="none">不通知</option><option value="owner">通知责任员工</option><option value="extra">通知额外人员</option></select></td><td><select aria-label={`策略风险等级 ${i+1}`} value={v.riskLevel} onChange={e=>p.setStrategies(p.strategies.map((x,j)=>j===i?{...x,riskLevel:e.target.value}:x))}><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险</option></select></td><td><button type="button" disabled={p.strategies.length===1} onClick={()=>p.setStrategies(p.strategies.filter((_,j)=>j!==i))}>删除策略</button></td></tr>)}</tbody></table></div><div className="dashboard-filter-bar"><button type="button" disabled={p.strategies.length>=5} onClick={()=>p.setStrategies([...p.strategies,{timeoutMinutes:3,notifyType:'none',riskLevel:'low'}])}>添加超时策略</button><button type="button" disabled={!p.name.trim()||(!p.scopeSingle&&!p.scopeGroup)||p.pending} onClick={p.onSave}>保存</button></div></aside>}

function SettingsPanel(p:{queryData:unknown;closingPhrases:string;whitelistTypes:string;onClosing:(v:string)=>void;onWhitelist:(v:string)=>void;onLoad:(g:string,t:string)=>void;onSave:()=>void;pending:boolean}){const loaded=useMemo(()=>{const body=p.queryData&&typeof p.queryData==='object'?((p.queryData as Row).data&&typeof(p.queryData as Row).data==='object'?(p.queryData as Row).data as Row:p.queryData as Row):{};const groups=Array.isArray(body.closingPhraseGroups)?body.closingPhraseGroups as unknown[][]:[];const types=Array.isArray(body.whitelistMessageTypes)?body.whitelistMessageTypes.map(str):[];return{groups:groups.map(g=>g.map(str).join(',')).join(';'),types:types.join(',')}} ,[p.queryData]);return <div className="dashboard-data-card phase33-risk-warning-results"><div className="dashboard-card-heading"><div><h2>高级设置</h2><p>配置不触发超时记录的结束语和消息类型。</p></div><button type="button" onClick={()=>p.onLoad(loaded.groups,loaded.types)}>载入当前设置</button></div><div className="dashboard-filter-bar"><label>结束语词表<input aria-label="结束语词表" value={p.closingPhrases} onChange={e=>p.onClosing(e.target.value)} placeholder="词用逗号分隔，词表用分号分隔"/></label><label>白名单消息类型<input aria-label="白名单消息类型" value={p.whitelistTypes} onChange={e=>p.onWhitelist(e.target.value)} placeholder="image,file,voice"/></label><button type="button" disabled={p.pending} onClick={p.onSave}>保存设置</button></div></div>}
