import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import type { Phase35Api, Row } from './api';
import { numericId, records, text } from './api';
import { Phase35PageShell } from './components/phase35-page-shell';
import { Phase35DataState } from './components/data-state';
import { Phase35DetailDrawer } from './components/detail-drawer';
import { MetricCardGrid } from './components/metric-card-grid';
export function FriendsPage({ api }: { api: Phase35Api }) {
  const [keyword,setKeyword]=useState(''); const [owner,setOwner]=useState(''); const [applied,setApplied]=useState({keyword:'',owner:''}); const [page,setPage]=useState(1); const [selected,setSelected]=useState<Row>();
  const list=useQuery({queryKey:['phase35-friends',applied,page],queryFn:()=>api.read('/workContact/index',{name:applied.keyword,employeeName:applied.owner,page,perPage:20})});
  const detail=useQuery({queryKey:['phase35-friend',selected?numericId(selected):0],enabled:!!selected,queryFn:()=>api.read('/workContact/show',{id:numericId(selected!)})});
  const rows=records(list.data); const payload=(list.data??{}) as Row; const detailRow=(detail.data??{}) as Row; const total=Number(payload.total??rows.length);
  return <Phase35PageShell title="好友" description="查询企业微信联系人、负责人、标签和关联业务记录"><form className="dashboard-filter-bar" onSubmit={(e)=>{e.preventDefault();setPage(1);setApplied({keyword:keyword.trim(),owner:owner.trim()});}}><label>好友名称<input aria-label="好友名称" value={keyword} onChange={(e)=>setKeyword(e.target.value)}/></label><label>负责人<input aria-label="负责人" value={owner} onChange={(e)=>setOwner(e.target.value)}/></label><button type="submit">查询</button><button type="button" onClick={()=>{setKeyword('');setOwner('');setPage(1);setApplied({keyword:'',owner:''});}}>重置</button></form><MetricCardGrid items={[{label:'好友总数',value:total},{label:'当前页',value:page},{label:'已展示',value:rows.length}]}/><Phase35DataState loading={list.isLoading} error={list.isError} empty={!list.isLoading&&!rows.length} onRetry={()=>void list.refetch()}><table><thead><tr><th>好友</th><th>手机号</th><th>负责人</th><th>标签</th><th>来源</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map((row)=><tr key={numericId(row)}><td>{text(row.name??row.contactName)}</td><td>{maskPhone(row.phone)}</td><td>{text(row.employeeName??row.ownerName)}</td><td>{Array.isArray(row.tags)?row.tags.map(text).join('、'):text(row.tagNames)}</td><td>{text(row.source)}</td><td>{text(row.updatedAt)}</td><td><button type="button" aria-label={`查看 ${text(row.name??row.contactName)}`} onClick={()=>setSelected(row)}>查看详情</button></td></tr>)}</tbody></table><nav aria-label="好友分页"><button type="button" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>上一页</button><span>第 {page} 页</span><button type="button" disabled={page*20>=total} onClick={()=>setPage(v=>v+1)}>下一页</button></nav></Phase35DataState><Phase35DetailDrawer title="好友详情" open={Boolean(selected)} onClose={()=>setSelected(undefined)}>{detail.isLoading?<p>正在加载详情…</p>:detail.isError?<p role="alert">详情加载失败</p>:<dl><dt>姓名</dt><dd>{text(detailRow.name??selected?.name)}</dd><dt>负责人</dt><dd>{text(detailRow.employeeName??detailRow.ownerName)}</dd><dt>标签</dt><dd>{text(detailRow.tagNames)}</dd><dt>来源</dt><dd>{text(detailRow.source)}</dd><dt>关联线索</dt><dd>{text(detailRow.leadCount)}</dd><dt>关联商机/订单</dt><dd>{text(detailRow.opportunityCount)} / {text(detailRow.orderCount)}</dd></dl>}</Phase35DetailDrawer></Phase35PageShell>;
}
const maskPhone=(value:unknown)=>{const phone=String(value??'');return /^\d{7,}$/.test(phone)?`${phone.slice(0,3)}****${phone.slice(-4)}`:text(value)};
