import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import type { Phase35Api, Row } from './api';
import { numericId, records, text } from './api';
import { Phase35PageShell } from './components/phase35-page-shell';
import { Phase35DataState } from './components/data-state';
import { Phase35DetailDrawer } from './components/detail-drawer';
import { MetricCardGrid } from './components/metric-card-grid';
export function GroupPage({ api }: { api: Phase35Api }) {
  const [keyword,setKeyword]=useState('');const [status,setStatus]=useState('');const [applied,setApplied]=useState({keyword:'',status:''});const [page,setPage]=useState(1);const [memberPage,setMemberPage]=useState(1);const [selected,setSelected]=useState<Row>();
  const list=useQuery({queryKey:['phase35-groups',applied,page],queryFn:()=>api.read('/workRoom/index',{name:applied.keyword,status:applied.status,page,perPage:20})});
  const detail=useQuery({queryKey:['phase35-group',selected?numericId(selected):0,memberPage],enabled:!!selected,queryFn:()=>api.read('/workRoom/roomIndex',{roomId:numericId(selected!),page:memberPage,perPage:20})});
  const rows=records(list.data);const payload=(list.data??{}) as Row;const detailPayload=(detail.data??{}) as Row;const members=records(detailPayload.members);const total=Number(payload.total??rows.length);
  return <Phase35PageShell title="客户群" description="查询客户群、群主、活跃状态和分页成员明细"><form className="dashboard-filter-bar" onSubmit={(e)=>{e.preventDefault();setPage(1);setApplied({keyword:keyword.trim(),status});}}><label>群名称<input aria-label="群名称" value={keyword} onChange={(e)=>setKeyword(e.target.value)}/></label><label>群状态<select aria-label="群状态" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">全部</option><option value="active">活跃</option><option value="inactive">不活跃</option></select></label><button type="submit">查询</button><button type="button" onClick={()=>{setKeyword('');setStatus('');setPage(1);setApplied({keyword:'',status:''});}}>重置</button></form><MetricCardGrid items={[{label:'群总数',value:total},{label:'成员总数',value:Number(payload.memberTotal??0)},{label:'活跃群',value:Number(payload.activeTotal??0)}]}/><Phase35DataState loading={list.isLoading} error={list.isError} empty={!list.isLoading&&!rows.length} onRetry={()=>void list.refetch()}><table><thead><tr><th>群名称</th><th>群主</th><th>成员数</th><th>活跃状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{rows.map((row)=><tr key={numericId(row)}><td>{text(row.name??row.roomName)}</td><td>{text(row.ownerName)}</td><td>{text(row.memberCount)}</td><td>{String(row.activeStatus??row.status)==='active'?'活跃':'不活跃'}</td><td>{text(row.createdAt)}</td><td><button type="button" aria-label={`查看 ${text(row.name??row.roomName)}`} onClick={()=>{setMemberPage(1);setSelected(row);}}>查看成员</button></td></tr>)}</tbody></table><nav aria-label="客户群分页"><button type="button" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>上一页</button><span>第 {page} 页</span><button type="button" disabled={page*20>=total} onClick={()=>setPage(v=>v+1)}>下一页</button></nav></Phase35DataState><Phase35DetailDrawer title="客户群成员明细" open={Boolean(selected)} onClose={()=>setSelected(undefined)}>{detail.isLoading?<p>正在加载成员…</p>:detail.isError?<p role="alert">成员加载失败</p>:<><dl><dt>群名称</dt><dd>{text(detailPayload.name??selected?.name)}</dd><dt>群主</dt><dd>{text(detailPayload.ownerName??selected?.ownerName)}</dd></dl><table><thead><tr><th>成员</th><th>角色</th><th>入群时间</th></tr></thead><tbody>{members.map((member,index)=><tr key={numericId(member)||index}><td>{text(member.name)}</td><td>{text(member.role)}</td><td>{text(member.joinedAt)}</td></tr>)}</tbody></table><nav aria-label="群成员分页"><button type="button" disabled={memberPage<=1} onClick={()=>setMemberPage(v=>v-1)}>上一页</button><span>第 {memberPage} 页</span><button type="button" disabled={members.length<20} onClick={()=>setMemberPage(v=>v+1)}>下一页</button></nav></>}</Phase35DetailDrawer></Phase35PageShell>;
}
