import { useMutation, useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { useOptionalDashboardAccess } from '../../app/access-context';
import type { Phase35Api } from './api';
import { records, text } from './api';
import { Phase35PageShell } from './components/phase35-page-shell';
import { Phase35DataState } from './components/data-state';
import { Phase35DetailDrawer } from './components/detail-drawer';
export function OrderPage({ api }: { api: Phase35Api }) {
  const corpId = useOptionalDashboardAccess()?.corp.id; const [contactId, setContactId] = useState(''); const [amount, setAmount] = useState(''); const [selected, setSelected] = useState<Record<string, unknown>>();
  const orders = useQuery({ queryKey: ['p35-orders', corpId], queryFn: () => api.read('/scrm/orders', { corpId: Number(corpId) }), enabled: Boolean(corpId) });
  const contacts = useQuery({ queryKey: ['p35-order-contacts', corpId], queryFn: () => api.read('/workContact/index', { corpId: Number(corpId), page: 1, perPage: 50 }), enabled: Boolean(corpId) });
  const detail = useQuery({ queryKey: ['p35-order-detail', selected?.id, corpId], queryFn: () => api.read(`/scrm/orders/${String(selected?.id)}`, { corpId: Number(corpId) }), enabled: Boolean(selected?.id && corpId) });
  const create = useMutation({ mutationFn: () => api.write('/scrm/orders', { corpId: Number(corpId), contactId, amountCents: Math.round(Number(amount) * 100), currency: 'CNY', status: 'pending' }, 'POST'), onSuccess: () => { setContactId(''); setAmount(''); void orders.refetch(); } });
  const transition = useMutation({ mutationFn: (status: string) => api.write(`/scrm/orders/${String(selected?.id)}/transition?corpId=${Number(corpId)}`, { status, version: Number(selected?.version ?? 1) }, 'PUT'), onSuccess: () => { void orders.refetch(); void detail.refetch(); } });
  const rows = records(orders.data); const options = records(contacts.data); const detailPayload = detail.data as { data?: unknown } | undefined; const valid = Boolean(corpId && contactId && Number(amount) > 0);
  return <Phase35PageShell title="订单" description="创建、查看、流转订单并追溯审计时间线"><form className="dashboard-filter-bar" onSubmit={(event) => { event.preventDefault(); if (valid) create.mutate(); }}><label>联系人<select aria-label="联系人" value={contactId} onChange={(event) => setContactId(event.target.value)}><option value="">请选择联系人</option>{options.map((row, index) => <option key={index} value={String(row.id ?? row.contactId)}>{text(row.name ?? row.contactName)}</option>)}</select></label><label>金额（元）<input aria-label="金额（元）" value={amount} onChange={(event) => setAmount(event.target.value.replace(/[^\d.]/g, ''))} /></label><button type="submit" disabled={!valid || create.isPending}>创建订单</button></form>{create.isError && <p role="alert">创建失败，请检查联系人、金额和权限</p>}<Phase35DataState loading={orders.isLoading} error={orders.isError} empty={!orders.isLoading && !rows.length}><table><thead><tr><th>订单号</th><th>金额（元）</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td>{text(row.id)}</td><td>{(Number(row.amountCents ?? 0) / 100).toFixed(2)}</td><td>{text(row.status)}</td><td><button type="button" onClick={() => setSelected(row)}>查看详情</button></td></tr>)}</tbody></table></Phase35DataState><Phase35DetailDrawer title="订单详情" open={Boolean(selected)} onClose={() => setSelected(undefined)}>{detail.isLoading ? <p>正在加载…</p> : detail.isError ? <p role="alert">详情加载失败</p> : <><pre>{JSON.stringify(detailPayload?.data ?? detail.data, null, 2)}</pre><button type="button" onClick={() => transition.mutate('processing')}>处理中</button><button type="button" onClick={() => transition.mutate('completed')}>已完成</button><button type="button" onClick={() => transition.mutate('cancelled')}>取消</button>{transition.isError && <p role="alert">状态更新失败，可能是版本冲突，请刷新重试</p>}</>}</Phase35DetailDrawer></Phase35PageShell>;
}
