#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
unset GOROOT

COMPOSE_FILE="deploy/mysql57/docker-compose.yml"
PROJECT_NAME="${MOCHAT_STACK_PROJECT:-mochat-go-mysql57-schema-check}"
MYSQL_PORT="${MOCHAT_MYSQL57_PORT:-13332}"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/mochat-go-mysql57-schema.XXXXXX")"
MIGRATE_BIN="$WORK_DIR/mochat-migrate"

ARCH="$(uname -m)"
if [ "$ARCH" = "arm64" ] || [ "$ARCH" = "aarch64" ]; then
  if [ "${MOCHAT_FORCE_MYSQL57:-0}" != "1" ]; then
    echo "mysql 5.7 schema migration smoke skipped on $ARCH: mysql:5.7 is amd64-only and crashes under qemu on this host; run this script on amd64 CI or set MOCHAT_FORCE_MYSQL57=1 to force it" >&2
    exit 0
  fi
fi

compose() {
  MOCHAT_MYSQL57_PORT="$MYSQL_PORT" docker compose -p "$PROJECT_NAME" -f "$COMPOSE_FILE" "$@"
}

cleanup() {
  rm -rf "$WORK_DIR"
  if [ "${KEEP_STACK:-0}" != "1" ]; then
    compose down -v --remove-orphans >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT INT TERM

assert_port_free() {
  local port="$1"
  if lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "port $port is already in use" >&2
    exit 1
  fi
}

wait_service_healthy() {
  local service="$1"
  local deadline=$((SECONDS + 240))
  while [ "$SECONDS" -lt "$deadline" ]; do
    local status
    status="$(compose ps --format json "$service" 2>/dev/null | python3 -c 'import json,sys; data=sys.stdin.read().strip(); print(json.loads(data).get("Health", "")) if data else print("")' 2>/dev/null || true)"
    if [ "$status" = "healthy" ]; then
      return 0
    fi
    sleep 2
  done
  echo "$service did not become healthy" >&2
  compose ps >&2 || true
  compose logs --tail=160 "$service" >&2 || true
  exit 1
}

mysql_scalar() {
  local query="$1"
  compose exec -T mysql57 mysql -umochat -pmochat_pass -N -B mochat -e "$query" | tr -d '\r'
}

assert_port_free "$MYSQL_PORT"

compose up -d mysql57
wait_service_healthy mysql57

env -u GOROOT go build -o "$MIGRATE_BIN" ./cmd/mochat-migrate

MYSQL57_DSN="mochat:mochat_pass@tcp(127.0.0.1:$MYSQL_PORT)/mochat?parseTime=true&loc=Local"

"$MIGRATE_BIN" -dsn "$MYSQL57_DSN" -project-root "$PWD" -action apply >"$WORK_DIR/apply.out"
grep -q $'0001_initial_schema\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0002_seed_core_data\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0003_saas_provisioning\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0004_saas_storage_objects\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0005_background_tasks\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0006_saas_alerts\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0007_wechat_component_tickets\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0008_saas_alert_notifications\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0009_contact_batch_add_rbac\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0010_sensitive_words\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0011_sop_rbac\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0012_shop_code\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0013_radar\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0014_auto_tag\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0015_lottery\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0016_room_fission\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0017_room_clock_in\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0018_room_quality\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0019_room_calendar\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0020_room_remind\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0021_room_infinite_pull\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0022_work_message_archive_sync\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0023_saas_alert_settings\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0024_saas_package_extended_limits\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0025_saas_radar_limit\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0026_saas_lottery_limit\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0027_saas_room_infinite_pull_limit\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0028_saas_room_fission_limit\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0029_saas_room_clock_in_limit\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0030_saas_room_operation_limits\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0031_saas_sop_limits\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0032_saas_sensitive_word_limit\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0060_saas_service_account_usage_retention\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0061_saas_service_account_usage_alerts\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0062_saas_audit_integrity\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0063_saas_audit_anchor_signatures\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0064_saas_audit_anchor_remote_immutability\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0066_saas_alert_credential_encryption\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0067_wecom_credential_encryption\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0068_wechat_open_credential_encryption\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0069_saas_release_candidate_approval\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0070_saas_approval_policy_change_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0073_saas_compliance_export_deletion_saga\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0074_saas_compliance_legal_hold_release_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0076_saas_identity_policy_change_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0077_saas_tenant_disable_approval_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0078_saas_critical_approval_policy_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0079_saas_service_account_key_revoke_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0080_saas_service_account_update_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0081_saas_service_account_key_rotate_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0082_saas_service_account_create_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0083_saas_identity_mfa_reset_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0085_saas_tenant_package_assignment_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0088_saas_subscription_transition_approval_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0089_saas_invoice_issue_approval_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0090_saas_payment_order_create_approval_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0091_saas_payment_settlement_close_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0092_saas_payment_settlement_reopen_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0093_saas_payment_settlement_resolve_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0094_saas_tenant_domain_command_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0095_saas_tenant_domain_create_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0096_saas_tenant_enable_approval_guard\tapplied_now' "$WORK_DIR/apply.out"
grep -q $'0097_saas_release_evidence_action_tracking\tapplied_now' "$WORK_DIR/apply.out"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations")" = "97"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type IN ('tenant.disable','tenant.enable','tenant.provision','tenant.renewal','tenant.subscription.transition','package.upsert','tenant.package.update','tenant.domain.create','tenant.domain.command','payment.order.create','payment.refund.create','payment.settlement.close','payment.settlement.reopen','payment.settlement.resolve','billing.invoice.issue','access.role.save','access.assignment.save','tenant.data.erase','release.candidate.gate','approval.policy.update','backup.policy.update','backup.retention.cleanup','compliance.policy.update','compliance.export.delete','compliance.legal_hold.release','identity.policy.update','identity.mfa.reset','service_account.create','service_account.update','service_account.key.rotate','service_account.key.revoke') AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals >= 2")" = "31"
test "$(mysql_scalar "SELECT required_approvals FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'payment.refund.create'")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'approval.policy.update' AND enabled = 1 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'compliance.export.delete' AND enabled = 1 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'compliance.legal_hold.release' AND enabled = 1 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'compliance.policy.update' AND enabled = 1 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'identity.policy.update' AND enabled = 1 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.disable' AND enabled = 1 AND required_approvals = 2")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_data_exports' AND COLUMN_NAME LIKE 'deletion_%'")" = "12"
test "$(mysql_scalar "SELECT COUNT(DISTINCT INDEX_NAME) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_data_exports' AND INDEX_NAME IN ('uni_mochat_go_saas_data_export_deletion_approval', 'idx_mochat_go_saas_data_export_deletion')")" = "2"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_service_account_usage_daily'")" = "mochat_go_saas_service_account_usage_daily"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_service_accounts' AND COLUMN_NAME IN ('rate_limit_per_minute', 'daily_request_limit', 'minute_window_started_at', 'minute_request_count', 'minute_rejected_count', 'daily_window_date', 'daily_request_count', 'daily_rejected_count')")" = "8"
test "$(mysql_scalar "SELECT service_account_usage_retention_days FROM mochat_go_saas_compliance_policies WHERE id = 1")" = "90"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_service_accounts' AND COLUMN_NAME IN ('usage_alert_enabled', 'usage_warning_percent', 'rejection_warning_count', 'usage_alert_cooldown_minutes', 'usage_alert_last_evaluated_at', 'usage_alert_last_notified_at', 'rejection_alert_last_notified_at')")" = "7"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_service_accounts' AND INDEX_NAME = 'idx_mochat_go_saas_service_account_usage_alert_eval'")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_admin_operation_logs' AND COLUMN_NAME IN ('integrity_prev_hash', 'integrity_hash', 'integrity_version')")" = "3"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_admin_audit_chains'")" = "mochat_go_saas_admin_audit_chains"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_admin_audit_verifications'")" = "mochat_go_saas_admin_audit_verifications"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_admin_audit_anchor_checkpoints'")" = "mochat_go_saas_admin_audit_anchor_checkpoints"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_admin_audit_anchor_checkpoints' AND COLUMN_NAME IN ('remote_status', 'remote_provider', 'remote_bucket', 'remote_object_key', 'remote_etag', 'remote_version_id', 'remote_sha256', 'remote_size_bytes', 'remote_retention_mode', 'remote_retain_until', 'remote_error', 'remote_exported_at', 'remote_verified_at')")" = "13"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_admin_audit_anchor_checkpoints' AND INDEX_NAME = 'idx_mochat_go_saas_audit_anchor_remote'")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_service_account_keys' AND COLUMN_NAME = 'hash_key_id' AND REPLACE(COLUMN_DEFAULT, CHAR(39), '') = 'legacy-jwt'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_service_account_keys' AND INDEX_NAME = 'idx_mochat_go_saas_service_account_key_hash_key'")" = "3"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_corp' AND COLUMN_NAME IN ('wecom_credentials_ciphertext', 'wecom_credentials_key_id')")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_corp' AND INDEX_NAME = 'idx_mc_corp_wecom_credential_key'")" = "3"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_work_agent' AND COLUMN_NAME IN ('wecom_credentials_ciphertext', 'wecom_credentials_key_id')")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_work_agent' AND INDEX_NAME = 'idx_mc_work_agent_wecom_credential_key'")" = "3"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_wechat_component_tickets' AND COLUMN_NAME IN ('component_verify_ticket_ciphertext', 'credential_key_id')")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_wechat_component_tickets' AND INDEX_NAME = 'idx_mochat_go_wechat_component_ticket_credential_key'")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_official_account' AND COLUMN_NAME IN ('wechat_credentials_ciphertext', 'wechat_credentials_key_id')")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_official_account' AND INDEX_NAME = 'idx_mc_official_account_wechat_credential_key'")" = "3"
test "$(mysql_scalar "SELECT VERSION() LIKE '5.7.%';")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0001_initial_schema' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0002_seed_core_data' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0003_saas_provisioning' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0004_saas_storage_objects' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0005_background_tasks' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0006_saas_alerts' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0007_wechat_component_tickets' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0008_saas_alert_notifications' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0009_contact_batch_add_rbac' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0010_sensitive_words' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0011_sop_rbac' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0012_shop_code' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0013_radar' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0014_auto_tag' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0015_lottery' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0016_room_fission' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0017_room_clock_in' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0018_room_quality' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0019_room_calendar' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0020_room_remind' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0021_room_infinite_pull' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0022_work_message_archive_sync' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0023_saas_alert_settings' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0024_saas_package_extended_limits' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0025_saas_radar_limit' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0026_saas_lottery_limit' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0027_saas_room_infinite_pull_limit' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0028_saas_room_fission_limit' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0029_saas_room_clock_in_limit' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0030_saas_room_operation_limits' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0031_saas_sop_limits' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0032_saas_sensitive_word_limit' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0061_saas_service_account_usage_alerts' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0062_saas_audit_integrity' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0063_saas_audit_anchor_signatures' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0064_saas_audit_anchor_remote_immutability' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0065_saas_service_account_key_pepper_ring' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0066_saas_alert_credential_encryption' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0067_wecom_credential_encryption' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0068_wechat_open_credential_encryption' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0069_saas_release_candidate_approval' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0070_saas_approval_policy_change_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0073_saas_compliance_export_deletion_saga' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0074_saas_compliance_legal_hold_release_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0076_saas_identity_policy_change_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0077_saas_tenant_disable_approval_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0078_saas_critical_approval_policy_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0079_saas_service_account_key_revoke_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0080_saas_service_account_update_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0081_saas_service_account_key_rotate_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0082_saas_service_account_create_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0083_saas_identity_mfa_reset_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0085_saas_tenant_package_assignment_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0088_saas_subscription_transition_approval_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0089_saas_invoice_issue_approval_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0090_saas_payment_order_create_approval_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0091_saas_payment_settlement_close_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0092_saas_payment_settlement_reopen_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0093_saas_payment_settlement_resolve_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0094_saas_tenant_domain_command_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0095_saas_tenant_domain_create_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0096_saas_tenant_enable_approval_guard' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0097_saas_release_evidence_action_tracking' AND CHAR_LENGTH(checksum) = 64")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_release_evidence_actions WHERE CHAR_LENGTH(next_action) > 0 AND version = 1")" = "6"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.enable' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND sla_minutes = 240 AND reminder_minutes = 60 AND expiry_hours = 24")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '$DATABASE' AND TABLE_NAME = 'mochat_go_saas_admin_tasks' AND COLUMN_NAME = 'version'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.provision' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.renewal' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.subscription.transition' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'billing.invoice.issue' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'payment.order.create' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'payment.settlement.close' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.domain.command' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'tenant.domain.create' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '$DATABASE' AND TABLE_NAME = 'mochat_go_saas_payment_orders' AND COLUMN_NAME IN ('package_version', 'package_limits_json')")" = "2"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '$DATABASE' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'version'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_saas_admin_approval_policies WHERE action_type = 'package.upsert' AND enabled = 1 AND amount_threshold_cents = 0 AND required_approvals = 2 AND expiry_hours = 12")" = "1"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_user'")" = "mc_user"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_contact_sop'")" = "mc_contact_sop"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_contact_sop_log'")" = "mc_contact_sop_log"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_sop'")" = "mc_room_sop"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_sop_log'")" = "mc_room_sop_log"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_contact_batch_add_import'")" = "mc_contact_batch_add_import"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_contact_batch_add_import_record'")" = "mc_contact_batch_add_import_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_packages'")" = "mochat_go_saas_packages"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_storage_objects'")" = "mochat_go_saas_storage_objects"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_background_task_executions'")" = "mochat_go_background_task_executions"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_alerts'")" = "mochat_go_saas_alerts"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_wechat_component_tickets'")" = "mochat_go_wechat_component_tickets"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_alert_notifications'")" = "mochat_go_saas_alert_notifications"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_saas_alert_settings'")" = "mochat_go_saas_alert_settings"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'shop_codes'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'radars'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'lotteries'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_infinite_pulls'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_fissions'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_clock_ins'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_qualities'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_calendars'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_reminds'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'contact_sops'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'room_sops'")" = "1"
test "$(mysql_scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mochat_go_saas_packages' AND COLUMN_NAME = 'sensitive_words'")" = "1"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_sensitive_word_group'")" = "mc_sensitive_word_group"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_sensitive_word'")" = "mc_sensitive_word"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_sensitive_words_monitor'")" = "mc_sensitive_words_monitor"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_shop_code'")" = "mc_shop_code"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_shop_code_page'")" = "mc_shop_code_page"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_shop_code_record'")" = "mc_shop_code_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_radar'")" = "mc_radar"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_radar_channel'")" = "mc_radar_channel"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_radar_channel_link'")" = "mc_radar_channel_link"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_radar_record'")" = "mc_radar_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_auto_tag'")" = "mc_auto_tag"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_auto_tag_record'")" = "mc_auto_tag_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_work_message_id'")" = "mc_work_message_id"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_work_message_1'")" = "mc_work_message_1"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_work_message_10'")" = "mc_work_message_10"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_lottery'")" = "mc_lottery"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_lottery_contact'")" = "mc_lottery_contact"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_lottery_contact_record'")" = "mc_lottery_contact_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_lottery_prize'")" = "mc_lottery_prize"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_fission'")" = "mc_room_fission"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_fission_contact'")" = "mc_room_fission_contact"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_fission_invite'")" = "mc_room_fission_invite"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_fission_poster'")" = "mc_room_fission_poster"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_fission_room'")" = "mc_room_fission_room"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_fission_welcome'")" = "mc_room_fission_welcome"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_clock_in'")" = "mc_room_clock_in"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_clock_in_contact'")" = "mc_room_clock_in_contact"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_clock_in_record'")" = "mc_room_clock_in_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_quality'")" = "mc_room_quality"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_quality_contact'")" = "mc_room_quality_contact"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_calendar'")" = "mc_room_calendar"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_calendar_push'")" = "mc_room_calendar_push"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_calendar_record'")" = "mc_room_calendar_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_remind'")" = "mc_room_remind"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_remind_record'")" = "mc_room_remind_record"
test "$(mysql_scalar "SHOW TABLES LIKE 'mc_room_infinite'")" = "mc_room_infinite"
test "$(mysql_scalar "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'mochat' AND TABLE_NAME = 'mc_corp' AND COLUMN_NAME IN ('chat_apply_status', 'chat_status', 'chat_secret', 'chat_whitelist_ip', 'chat_rsa_key')")" = "5"
test "$(mysql_scalar "SELECT COUNT(*) FROM mc_rbac_menu")" = "458"

"$MIGRATE_BIN" -dsn "$MYSQL57_DSN" -project-root "$PWD" -action status >"$WORK_DIR/status.out"
grep -q $'0001_initial_schema\tapplied' "$WORK_DIR/status.out"
grep -q $'0002_seed_core_data\tapplied' "$WORK_DIR/status.out"
grep -q $'0003_saas_provisioning\tapplied' "$WORK_DIR/status.out"
grep -q $'0004_saas_storage_objects\tapplied' "$WORK_DIR/status.out"
grep -q $'0005_background_tasks\tapplied' "$WORK_DIR/status.out"
grep -q $'0006_saas_alerts\tapplied' "$WORK_DIR/status.out"
grep -q $'0007_wechat_component_tickets\tapplied' "$WORK_DIR/status.out"
grep -q $'0008_saas_alert_notifications\tapplied' "$WORK_DIR/status.out"
grep -q $'0009_contact_batch_add_rbac\tapplied' "$WORK_DIR/status.out"
grep -q $'0010_sensitive_words\tapplied' "$WORK_DIR/status.out"
grep -q $'0011_sop_rbac\tapplied' "$WORK_DIR/status.out"
grep -q $'0012_shop_code\tapplied' "$WORK_DIR/status.out"
grep -q $'0013_radar\tapplied' "$WORK_DIR/status.out"
grep -q $'0014_auto_tag\tapplied' "$WORK_DIR/status.out"
grep -q $'0015_lottery\tapplied' "$WORK_DIR/status.out"
grep -q $'0016_room_fission\tapplied' "$WORK_DIR/status.out"
grep -q $'0017_room_clock_in\tapplied' "$WORK_DIR/status.out"
grep -q $'0018_room_quality\tapplied' "$WORK_DIR/status.out"
grep -q $'0019_room_calendar\tapplied' "$WORK_DIR/status.out"
grep -q $'0020_room_remind\tapplied' "$WORK_DIR/status.out"
grep -q $'0021_room_infinite_pull\tapplied' "$WORK_DIR/status.out"
grep -q $'0022_work_message_archive_sync\tapplied' "$WORK_DIR/status.out"
grep -q $'0023_saas_alert_settings\tapplied' "$WORK_DIR/status.out"
grep -q $'0024_saas_package_extended_limits\tapplied' "$WORK_DIR/status.out"
grep -q $'0025_saas_radar_limit\tapplied' "$WORK_DIR/status.out"
grep -q $'0026_saas_lottery_limit\tapplied' "$WORK_DIR/status.out"
grep -q $'0027_saas_room_infinite_pull_limit\tapplied' "$WORK_DIR/status.out"
grep -q $'0028_saas_room_fission_limit\tapplied' "$WORK_DIR/status.out"
grep -q $'0029_saas_room_clock_in_limit\tapplied' "$WORK_DIR/status.out"
grep -q $'0030_saas_room_operation_limits\tapplied' "$WORK_DIR/status.out"
grep -q $'0031_saas_sop_limits\tapplied' "$WORK_DIR/status.out"
grep -q $'0032_saas_sensitive_word_limit\tapplied' "$WORK_DIR/status.out"
grep -q $'0059_saas_service_account_rate_limits\tapplied' "$WORK_DIR/status.out"
grep -q $'0060_saas_service_account_usage_retention\tapplied' "$WORK_DIR/status.out"
grep -q $'0061_saas_service_account_usage_alerts\tapplied' "$WORK_DIR/status.out"
grep -q $'0062_saas_audit_integrity\tapplied' "$WORK_DIR/status.out"
grep -q $'0063_saas_audit_anchor_signatures\tapplied' "$WORK_DIR/status.out"
grep -q $'0064_saas_audit_anchor_remote_immutability\tapplied' "$WORK_DIR/status.out"
grep -q $'0066_saas_alert_credential_encryption\tapplied' "$WORK_DIR/status.out"
grep -q $'0067_wecom_credential_encryption\tapplied' "$WORK_DIR/status.out"
grep -q $'0068_wechat_open_credential_encryption\tapplied' "$WORK_DIR/status.out"
grep -q $'0069_saas_release_candidate_approval\tapplied' "$WORK_DIR/status.out"
grep -q $'0070_saas_approval_policy_change_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0073_saas_compliance_export_deletion_saga\tapplied' "$WORK_DIR/status.out"
grep -q $'0074_saas_compliance_legal_hold_release_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0076_saas_identity_policy_change_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0077_saas_tenant_disable_approval_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0078_saas_critical_approval_policy_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0079_saas_service_account_key_revoke_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0080_saas_service_account_update_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0081_saas_service_account_key_rotate_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0082_saas_service_account_create_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0083_saas_identity_mfa_reset_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0085_saas_tenant_package_assignment_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0088_saas_subscription_transition_approval_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0089_saas_invoice_issue_approval_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0090_saas_payment_order_create_approval_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0091_saas_payment_settlement_close_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0092_saas_payment_settlement_reopen_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0093_saas_payment_settlement_resolve_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0094_saas_tenant_domain_command_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0095_saas_tenant_domain_create_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0096_saas_tenant_enable_approval_guard\tapplied' "$WORK_DIR/status.out"
grep -q $'0097_saas_release_evidence_action_tracking\tapplied' "$WORK_DIR/status.out"

ROLLBACK_PROJECT="$WORK_DIR/project"
mkdir -p "$ROLLBACK_PROJECT/deploy/standalone/schema" "$ROLLBACK_PROJECT/deploy/standalone/migrations"
cp deploy/standalone/schema/mochat.sql "$ROLLBACK_PROJECT/deploy/standalone/schema/mochat.sql"
cat >"$ROLLBACK_PROJECT/deploy/standalone/migrations/0002_mysql57_rollback.up.sql" <<'SQL'
CREATE TABLE IF NOT EXISTS mochat_go_mysql57_smoke (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  name varchar(64) NOT NULL DEFAULT '',
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SQL
cat >"$ROLLBACK_PROJECT/deploy/standalone/migrations/0002_mysql57_rollback.down.sql" <<'SQL'
DROP TABLE IF EXISTS mochat_go_mysql57_smoke;
SQL

"$MIGRATE_BIN" -dsn "$MYSQL57_DSN" -project-root "$ROLLBACK_PROJECT" -action apply >"$WORK_DIR/apply-incremental.out"
grep -q $'0002_mysql57_rollback\tapplied_now' "$WORK_DIR/apply-incremental.out"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_mysql57_smoke'")" = "mochat_go_mysql57_smoke"

"$MIGRATE_BIN" -dsn "$MYSQL57_DSN" -project-root "$ROLLBACK_PROJECT" -action rollback >"$WORK_DIR/rollback.out"
grep -q $'0002_mysql57_rollback\trolled_back' "$WORK_DIR/rollback.out"
test "$(mysql_scalar "SHOW TABLES LIKE 'mochat_go_mysql57_smoke'")" = ""
test "$(mysql_scalar "SELECT COUNT(*) FROM mochat_go_schema_migrations WHERE version = '0002_mysql57_rollback'")" = "0"

echo "mysql 5.7 schema migration smoke passed"
